# -*- coding: utf-8 -*-
"""Data part 1: Companies 1 to 100"""

DATA_PART1 = [
    {
        "rank": 1,
        "name_cn": "亚马逊",
        "name_en": "Amazon.com, Inc.",
        "founder_en": "Jeff Bezos",
        "founder_cn": "杰夫·贝索斯",
        "country": "🇺🇸 美国",
        "hq": "华盛顿州 西雅图",
        "founded_year": 1994,
        "industry": "电子商务与云计算",
        "revenue_m": "716,924"
    },
    {
        "rank": 2,
        "name_cn": "沃尔玛",
        "name_en": "Walmart Inc.",
        "founder_en": "Sam Walton",
        "founder_cn": "萨姆·沃尔顿",
        "country": "🇺🇸 美国",
        "hq": "阿肯色州 本顿维尔",
        "founded_year": 1962,
        "industry": "综合连锁零售",
        "revenue_m": "713,163"
    },
    {
        "rank": 3,
        "name_cn": "国家电网有限公司",
        "name_en": "State Grid Corporation of China",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (电力体制改革分立设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 2002,
        "industry": "电力与公共公用事业",
        "revenue_m": "555,371"
    },
    {
        "rank": 4,
        "name_cn": "联合健康集团",
        "name_en": "UnitedHealth Group Inc.",
        "founder_en": "Richard Burke",
        "founder_cn": "理查德·伯克",
        "country": "🇺🇸 美国",
        "hq": "明尼苏达州 明尼阿波利斯",
        "founded_year": 1977,
        "industry": "医疗健康与健康保险",
        "revenue_m": "447,567"
    },
    {
        "rank": 5,
        "name_cn": "沙特阿美公司",
        "name_en": "Saudi Aramco (Saudi Arabian Oil Group)",
        "founder_en": "Government of Saudi Arabia & SOCAL",
        "founder_cn": "沙特阿拉伯政府 / 加州标准石油",
        "country": "🇸🇦 沙特阿拉伯",
        "hq": "达兰",
        "founded_year": 1933,
        "industry": "石油天然气与综合石化",
        "revenue_m": "445,529"
    },
    {
        "rank": 6,
        "name_cn": "苹果公司",
        "name_en": "Apple Inc.",
        "founder_en": "Steve Jobs, Steve Wozniak, Ronald Wayne",
        "founder_cn": "史蒂夫·乔布斯、斯蒂夫·沃兹尼亚克、罗纳德·韦恩",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 库比蒂诺",
        "founded_year": 1976,
        "industry": "消费电子与操作系统平台",
        "revenue_m": "416,161"
    },
    {
        "rank": 7,
        "name_cn": "麦克森公司",
        "name_en": "McKesson Corporation",
        "founder_en": "John McKesson, Charles Olcott",
        "founder_cn": "约翰·麦克森、查尔斯·奥尔科特",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 欧文",
        "founded_year": 1833,
        "industry": "医药流通分销与医疗IT",
        "revenue_m": "403,430"
    },
    {
        "rank": 8,
        "name_cn": "Alphabet公司",
        "name_en": "Alphabet Inc. (Google)",
        "founder_en": "Larry Page, Sergey Brin",
        "founder_cn": "拉里·佩奇、谢尔盖·布林",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 山景城",
        "founded_year": 1998,
        "industry": "互联网搜索、人工智能与云计算",
        "revenue_m": "402,836"
    },
    {
        "rank": 9,
        "name_cn": "CVS Health公司",
        "name_en": "CVS Health Corporation",
        "founder_en": "Stanley Goldstein, Sidney Goldstein, Ralph Hoagland",
        "founder_cn": "斯坦利·戈德斯坦、西德尼·戈德斯坦、拉尔夫·霍格兰",
        "country": "🇺🇸 美国",
        "hq": "罗德岛州 文索基特",
        "founded_year": 1963,
        "industry": "医药零售、PBM与健康险",
        "revenue_m": "402,067"
    },
    {
        "rank": 10,
        "name_cn": "中国石油天然气集团有限公司",
        "name_en": "China National Petroleum Corporation (CNPC)",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (原石油工业部改制)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1988,
        "industry": "石油勘探开发与石化",
        "revenue_m": "401,927"
    },
    {
        "rank": 11,
        "name_cn": "伯克希尔－哈撒韦公司",
        "name_en": "Berkshire Hathaway Inc.",
        "founder_en": "Oliver Chace / Warren Buffett",
        "founder_cn": "奥利弗·蔡斯 / 沃伦·巴菲特 (重组)",
        "country": "🇺🇸 美国",
        "hq": "内布拉斯加州 奥马哈",
        "founded_year": 1839,
        "industry": "多元化投资、保险与实业控股",
        "revenue_m": "371,444"
    },
    {
        "rank": 12,
        "name_cn": "中国石油化工集团有限公司",
        "name_en": "China Petrochemical Corporation (Sinopec Group)",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (中国石油化工总公司演变)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1983,
        "industry": "石油炼化、化纤与能源销售",
        "revenue_m": "364,033"
    },
    {
        "rank": 13,
        "name_cn": "大众公司",
        "name_en": "Volkswagen Group (Volkswagen AG)",
        "founder_en": "German Labour Front / Ferdinand Porsche",
        "founder_cn": "德国劳动阵线 / 费迪南德·保时捷",
        "country": "🇩🇪 德国",
        "hq": "沃尔夫斯堡",
        "founded_year": 1937,
        "industry": "汽车制造与出行服务",
        "revenue_m": "363,091"
    },
    {
        "rank": 14,
        "name_cn": "丰田汽车公司",
        "name_en": "Toyota Motor Corporation",
        "founder_en": "Kiichiro Toyoda",
        "founder_cn": "丰田喜一郎",
        "country": "🇯🇵 日本",
        "hq": "爱知县 丰田市",
        "founded_year": 1937,
        "industry": "汽车制造与智能出行",
        "revenue_m": "336,305"
    },
    {
        "rank": 15,
        "name_cn": "埃克森美孚",
        "name_en": "ExxonMobil Corporation",
        "founder_en": "John D. Rockefeller (Standard Oil)",
        "founder_cn": "约翰·D·洛克菲勒 (标准石油重组)",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 斯普林",
        "founded_year": 1870,
        "industry": "综合石油天然气与化学品",
        "revenue_m": "332,238"
    },
    {
        "rank": 16,
        "name_cn": "Cencora公司",
        "name_en": "Cencora, Inc. (AmerisourceBergen)",
        "founder_en": "Lucien Napoleon Brunswig, Robert Bergen",
        "founder_cn": "吕西安·布伦斯威格、罗伯特·卑尔根",
        "country": "🇺🇸 美国",
        "hq": "宾夕法尼亚州 康舍霍肯",
        "founded_year": 2001,
        "industry": "药品分销与特种药健康服务",
        "revenue_m": "321,333"
    },
    {
        "rank": 17,
        "name_cn": "中国建筑集团有限公司",
        "name_en": "China State Construction Engineering Corp. (CSCEC)",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (原国家建工总局改制)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1982,
        "industry": "建筑工程总承包与城市开发",
        "revenue_m": "289,893"
    },
    {
        "rank": 18,
        "name_cn": "微软",
        "name_en": "Microsoft Corporation",
        "founder_en": "Bill Gates, Paul Allen",
        "founder_cn": "比尔·盖茨、保罗·艾伦",
        "country": "🇺🇸 美国",
        "hq": "华盛顿州 雷德蒙德",
        "founded_year": 1975,
        "industry": "操作系统、企业软件、云与AI",
        "revenue_m": "281,724"
    },
    {
        "rank": 19,
        "name_cn": "摩根大通公司",
        "name_en": "JPMorgan Chase & Co.",
        "founder_en": "J. Pierpont Morgan, Aaron Burr, John Thompson",
        "founder_cn": "J.P. 摩根、阿伦·伯尔、约翰·汤普森",
        "country": "🇺🇸 美国",
        "hq": "纽约州 纽约",
        "founded_year": 1799,
        "industry": "投资银行、资产管理与综合金融",
        "revenue_m": "280,345"
    },
    {
        "rank": 20,
        "name_cn": "开市客",
        "name_en": "Costco Wholesale Corporation",
        "founder_en": "James Sinegal, Jeffrey Brotman",
        "founder_cn": "詹姆斯·辛内格尔、杰弗里·布罗特曼",
        "country": "🇺🇸 美国",
        "hq": "华盛顿州 伊萨夸",
        "founded_year": 1983,
        "industry": "仓储会员制连锁零售",
        "revenue_m": "275,235"
    },
    {
        "rank": 21,
        "name_cn": "信诺集团",
        "name_en": "The Cigna Group",
        "founder_en": "INA & CG Merger (INA founded 1792)",
        "founder_cn": "北美洲保险公司与康涅狄格通用人寿合并",
        "country": "🇺🇸 美国",
        "hq": "康涅狄格州 布卢姆菲尔德",
        "founded_year": 1792,
        "industry": "医疗健康保险与药事服务",
        "revenue_m": "274,900"
    },
    {
        "rank": 22,
        "name_cn": "壳牌公司",
        "name_en": "Shell plc",
        "founder_en": "Marcus Samuel, Samuel Samuel, Henri Deterding",
        "founder_cn": "马库斯·萨缪尔、塞缪尔·萨缪尔、亨利·德特丁",
        "country": "🇬🇧 英国",
        "hq": "伦敦",
        "founded_year": 1907,
        "industry": "综合油气与可再生低碳能源",
        "revenue_m": "273,731"
    },
    {
        "rank": 23,
        "name_cn": "鸿海精密工业股份有限公司",
        "name_en": "Hon Hai Precision Industry Co., Ltd. (Foxconn)",
        "founder_en": "Terry Gou",
        "founder_cn": "郭台铭",
        "country": "🇹🇼 中国台湾",
        "hq": "新北市",
        "founded_year": 1974,
        "industry": "电子制造服务 (EMS) 与精密制造",
        "revenue_m": "260,084"
    },
    {
        "rank": 24,
        "name_cn": "嘉能可",
        "name_en": "Glencore plc",
        "founder_en": "Marc Rich",
        "founder_cn": "马克·里奇",
        "country": "🇨🇭 瑞士",
        "hq": "巴尔",
        "founded_year": 1974,
        "industry": "大宗商品贸易与综合矿业开采",
        "revenue_m": "247,535"
    },
    {
        "rank": 25,
        "name_cn": "托克集团",
        "name_en": "Trafigura Group",
        "founder_en": "Claude Dauphin, Eric de Turckheim",
        "founder_cn": "克劳德·多芬、埃里克·德·图克海姆",
        "country": "🇸🇬 新加坡",
        "hq": "新加坡",
        "founded_year": 1993,
        "industry": "石油原油、精炼金属与矿产贸易",
        "revenue_m": "240,268"
    },
    {
        "rank": 26,
        "name_cn": "三星电子",
        "name_en": "Samsung Electronics Co., Ltd.",
        "founder_en": "Lee Byung-chull",
        "founder_cn": "李秉喆",
        "country": "🇰🇷 韩国",
        "hq": "京畿道 水原市",
        "founded_year": 1969,
        "industry": "半导体存储芯片与智能终端",
        "revenue_m": "234,675"
    },
    {
        "rank": 27,
        "name_cn": "嘉德诺健康集团",
        "name_en": "Cardinal Health, Inc.",
        "founder_en": "Robert D. Walter",
        "founder_cn": "罗伯特·D·沃尔特",
        "country": "🇺🇸 美国",
        "hq": "俄亥俄州 都柏林",
        "founded_year": 1971,
        "industry": "药品分销与医疗器械用品制造",
        "revenue_m": "222,578"
    },
    {
        "rank": 28,
        "name_cn": "英伟达公司",
        "name_en": "NVIDIA Corporation",
        "founder_en": "Jensen Huang, Chris Malachowsky, Curtis Priem",
        "founder_cn": "黄仁勋、克里斯·马拉科夫斯基、柯蒂斯·普里姆",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 圣克拉拉",
        "founded_year": 1993,
        "industry": "GPU加速计算芯片与AI全栈生态",
        "revenue_m": "215,938"
    },
    {
        "rank": 29,
        "name_cn": "中国工商银行股份有限公司",
        "name_en": "Industrial and Commercial Bank of China (ICBC)",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (中国人民银行分设设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1984,
        "industry": "商业银行与多元化金融服务",
        "revenue_m": "210,590"
    },
    {
        "rank": 30,
        "name_cn": "Meta Platforms公司",
        "name_en": "Meta Platforms, Inc.",
        "founder_en": "Mark Zuckerberg, Eduardo Saverin, Dustin Moskovitz, Chris Hughes",
        "founder_cn": "马克·扎克伯格、爱德华多·萨维林、达斯汀·莫斯科维茨、克里斯·休斯",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 门洛帕克",
        "founded_year": 2004,
        "industry": "社交平台、元宇宙与开源AI",
        "revenue_m": "200,966"
    },
    {
        "rank": 31,
        "name_cn": "Elevance Health公司",
        "name_en": "Elevance Health, Inc.",
        "founder_en": "Associated Mutual Hospital Service (Anthem)",
        "founder_cn": "互助医院互保协会重组 (前身Anthem)",
        "country": "🇺🇸 美国",
        "hq": "印第安纳州 印第安纳波利斯",
        "founded_year": 1944,
        "industry": "健康保险与全生命周期健康服务",
        "revenue_m": "199,125"
    },
    {
        "rank": 32,
        "name_cn": "Centene公司",
        "name_en": "Centene Corporation",
        "founder_en": "Elizabeth Brinn",
        "founder_cn": "伊丽莎白·布林",
        "country": "🇺🇸 美国",
        "hq": "密苏里州 圣路易斯",
        "founded_year": 1984,
        "industry": "政府赞助医疗保险 (Medicaid)",
        "revenue_m": "194,777"
    },
    {
        "rank": 33,
        "name_cn": "英国石油公司",
        "name_en": "BP p.l.c.",
        "founder_en": "William Knox D'Arcy",
        "founder_cn": "威廉·诺克斯·达西",
        "country": "🇬🇧 英国",
        "hq": "伦敦",
        "founded_year": 1909,
        "industry": "石油天然气与低碳能源",
        "revenue_m": "192,549"
    },
    {
        "rank": 34,
        "name_cn": "美国银行",
        "name_en": "Bank of America Corporation",
        "founder_en": "Amadeo Giannini",
        "founder_cn": "阿马迪奥·贾尼尼 (意大利银行前身)",
        "country": "🇺🇸 美国",
        "hq": "北卡罗来纳州 夏洛特",
        "founded_year": 1904,
        "industry": "商业银行、财富管理与资本市场",
        "revenue_m": "191,567"
    },
    {
        "rank": 35,
        "name_cn": "中国农业银行股份有限公司",
        "name_en": "Agricultural Bank of China (ABC)",
        "founder_en": "State Council of China",
        "founder_cn": "中央人民政府 (农业合作银行前身)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1951,
        "industry": "商业银行与乡村振兴普惠金融",
        "revenue_m": "190,708"
    },
    {
        "rank": 36,
        "name_cn": "雪佛龙",
        "name_en": "Chevron Corporation",
        "founder_en": "Demetrius Scofield, Frederick Taylor",
        "founder_cn": "德米特里厄斯·斯科菲尔德、弗雷德里克·泰勒",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 圣拉蒙",
        "founded_year": 1879,
        "industry": "综合石油天然气与清洁能源",
        "revenue_m": "189,031"
    },
    {
        "rank": 37,
        "name_cn": "中国建设银行股份有限公司",
        "name_en": "China Construction Bank (CCB)",
        "founder_en": "State Council of China",
        "founder_cn": "政务院 (中国人民建设银行改制设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1954,
        "industry": "商业银行、基建融资与金融科技",
        "revenue_m": "188,657"
    },
    {
        "rank": 38,
        "name_cn": "福特汽车公司",
        "name_en": "Ford Motor Company",
        "founder_en": "Henry Ford",
        "founder_cn": "亨利·福特",
        "country": "🇺🇸 美国",
        "hq": "密歇根州 迪尔伯恩",
        "founded_year": 1903,
        "industry": "汽车及皮卡/商用车制造",
        "revenue_m": "187,267"
    },
    {
        "rank": 39,
        "name_cn": "通用汽车公司",
        "name_en": "General Motors Company",
        "founder_en": "William C. Durant, Charles Stewart Mott",
        "founder_cn": "威廉·C·杜兰特、查尔斯·斯图尔特·莫特",
        "country": "🇺🇸 美国",
        "hq": "密歇根州 底特律",
        "founded_year": 1908,
        "industry": "汽车制造、奥特能电动化与自动驾驶",
        "revenue_m": "185,019"
    },
    {
        "rank": 40,
        "name_cn": "道达尔能源公司",
        "name_en": "TotalEnergies SE",
        "founder_en": "Ernest Mercier",
        "founder_cn": "欧内斯特·梅西埃 (法国石油公司前身)",
        "country": "🇫🇷 法国",
        "hq": "库尔布瓦",
        "founded_year": 1924,
        "industry": "石油、液化天然气与太阳能/风能",
        "revenue_m": "182,344"
    },
    {
        "rank": 41,
        "name_cn": "京东集团股份有限公司",
        "name_en": "JD.com, Inc.",
        "founder_en": "Richard Liu (Liu Qiangdong)",
        "founder_cn": "刘强东",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1998,
        "industry": "自营电商、智能供应链与物流服务",
        "revenue_m": "182,129"
    },
    {
        "rank": 42,
        "name_cn": "中国人寿保险（集团）公司",
        "name_en": "China Life Insurance (Group) Company",
        "founder_en": "Central People's Government of China",
        "founder_cn": "中央人民政府 (中国人民保险公司分立设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1949,
        "industry": "人寿保险、年金与综合资产管理",
        "revenue_m": "178,215"
    },
    {
        "rank": 43,
        "name_cn": "Stellantis集团",
        "name_en": "Stellantis N.V.",
        "founder_en": "Groupe PSA & FCA Merger",
        "founder_cn": "PSA标致雪铁龙与菲亚特克莱斯勒合并",
        "country": "🇳🇱 荷兰",
        "hq": "阿姆斯特丹",
        "founded_year": 2021,
        "industry": "汽车制造 (标致/雪铁龙/Jeep/菲亚特)",
        "revenue_m": "173,144"
    },
    {
        "rank": 44,
        "name_cn": "中国银行股份有限公司",
        "name_en": "Bank of China Limited",
        "founder_en": "Approved by Dr. Sun Yat-sen",
        "founder_cn": "孙中山批准成立 (大清银行改组)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1912,
        "industry": "跨国商业银行与跨境综合金融",
        "revenue_m": "171,583"
    },
    {
        "rank": 45,
        "name_cn": "花旗集团",
        "name_en": "Citigroup Inc.",
        "founder_en": "Samuel Osgood",
        "founder_cn": "塞缪尔·奥斯古德 (纽约城市银行前身)",
        "country": "🇺🇸 美国",
        "hq": "纽约州 纽约",
        "founded_year": 1812,
        "industry": "全球性投资银行与跨国企业金融",
        "revenue_m": "168,297"
    },
    {
        "rank": 46,
        "name_cn": "家得宝",
        "name_en": "The Home Depot, Inc.",
        "founder_en": "Bernie Marcus, Arthur Blank, Ron Brill, Pat Farrah",
        "founder_cn": "伯尼·马库斯、阿瑟·布兰克、罗恩·布里尔、帕特·法拉",
        "country": "🇺🇸 美国",
        "hq": "佐治亚州 亚特兰大",
        "founded_year": 1978,
        "industry": "家居装修与建材连锁零售",
        "revenue_m": "164,683"
    },
    {
        "rank": 47,
        "name_cn": "房利美",
        "name_en": "Fannie Mae (Federal National Mortgage Association)",
        "founder_en": "Franklin D. Roosevelt / US Congress",
        "founder_cn": "富兰克林·罗斯福 / 美国国会 (新政设立)",
        "country": "🇺🇸 美国",
        "hq": "华盛顿特区",
        "founded_year": 1938,
        "industry": "政府赞助住房抵押贷款支持机构",
        "revenue_m": "159,169"
    },
    {
        "rank": 48,
        "name_cn": "中国平安保险（集团）股份有限公司",
        "name_en": "Ping An Insurance (Group) Company of China, Ltd.",
        "founder_en": "Peter Ma (Ma Mingzhe)",
        "founder_cn": "马明哲",
        "country": "🇨🇳 中国",
        "hq": "深圳",
        "founded_year": 1988,
        "industry": "综合金融、寿险财险与医养生态",
        "revenue_m": "158,650"
    },
    {
        "rank": 49,
        "name_cn": "中国铁路工程集团有限公司",
        "name_en": "China Railway Group Limited (CREC)",
        "founder_en": "Ministry of Railways of China",
        "founder_cn": "铁道部 (铁道部工程总局改制创立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1950,
        "industry": "特大型综合基础设施建设",
        "revenue_m": "152,201"
    },
    {
        "rank": 50,
        "name_cn": "宝马集团",
        "name_en": "BMW Group (Bayerische Motoren Werke AG)",
        "founder_en": "Karl Rapp, Camillo Castiglioni, Franz Josef Popp",
        "founder_cn": "卡尔·拉普、卡米洛·卡斯蒂利奥尼、弗朗茨·约瑟夫·波普",
        "country": "🇩🇪 德国",
        "hq": "慕尼黑",
        "founded_year": 1916,
        "industry": "高端豪华汽车与摩托车制造",
        "revenue_m": "150,524"
    },
    {
        "rank": 51,
        "name_cn": "梅赛德斯-奔驰集团",
        "name_en": "Mercedes-Benz Group AG",
        "founder_en": "Karl Benz, Gottlieb Daimler",
        "founder_cn": "卡尔·本茨、戈特利布·戴姆勒",
        "country": "🇩🇪 德国",
        "hq": "斯图加特",
        "founded_year": 1926,
        "industry": "豪华乘用车及高端商务出行",
        "revenue_m": "149,126"
    },
    {
        "rank": 52,
        "name_cn": "克罗格",
        "name_en": "The Kroger Co.",
        "founder_en": "Bernard Kroger",
        "founder_cn": "伯纳德·克罗格",
        "country": "🇺🇸 美国",
        "hq": "俄亥俄州 辛辛那提",
        "founded_year": 1883,
        "industry": "生鲜超市与食品供应链连锁",
        "revenue_m": "147,642"
    },
    {
        "rank": 53,
        "name_cn": "中国移动通信集团有限公司",
        "name_en": "China Mobile Communications Group Co., Ltd.",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (原电信移动通信局分立设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 2000,
        "industry": "5G移动网络、算力网络与数智服务",
        "revenue_m": "146,550"
    },
    {
        "rank": 54,
        "name_cn": "西班牙国家银行",
        "name_en": "Banco Santander, S.A.",
        "founder_en": "Royal Decree of Queen Isabel II",
        "founder_cn": "西班牙女王伊莎贝拉二世特许设立",
        "country": "🇪🇸 西班牙",
        "hq": "马德里",
        "founded_year": 1857,
        "industry": "商业银行、零售金融与财富管理",
        "revenue_m": "145,070"
    },
    {
        "rank": 55,
        "name_cn": "本田汽车",
        "name_en": "Honda Motor Co., Ltd.",
        "founder_en": "Soichiro Honda, Takeo Fujisawa",
        "founder_cn": "本田宗一郎、藤泽武夫",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1948,
        "industry": "汽车、摩托车与动力装备",
        "revenue_m": "144,625"
    },
    {
        "rank": 56,
        "name_cn": "阿里巴巴集团控股有限公司",
        "name_en": "Alibaba Group Holding Limited",
        "founder_en": "Jack Ma, Joseph Tsai, and 16 co-founders",
        "founder_cn": "马云、蔡崇信及“十八罗汉”",
        "country": "🇨🇳 中国",
        "hq": "浙江省 杭州",
        "founded_year": 1999,
        "industry": "电商平台、阿里云计算与全球商业",
        "revenue_m": "144,170"
    },
    {
        "rank": 57,
        "name_cn": "中国铁道建筑集团有限公司",
        "name_en": "China Railway Construction Corporation (CRCC)",
        "founder_en": "Chinese People's Liberation Army Railway Corps",
        "founder_cn": "中国人民解放军铁道兵",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1948,
        "industry": "特大型工程建筑与高铁基建",
        "revenue_m": "143,507"
    },
    {
        "rank": 58,
        "name_cn": "法国巴黎银行",
        "name_en": "BNP Paribas S.A.",
        "founder_en": "CNEP & Banque de Paris et des Pays-Bas",
        "founder_cn": "巴黎国民银行与巴黎巴银行合并",
        "country": "🇫🇷 法国",
        "hq": "巴黎",
        "founded_year": 1848,
        "industry": "跨国银行、企业金融与全球市场",
        "revenue_m": "141,642"
    },
    {
        "rank": 59,
        "name_cn": "中国中信集团有限公司",
        "name_en": "CITIC Group Corporation",
        "founder_en": "Rong Yiren",
        "founder_cn": "荣毅仁 (邓小平倡导创办)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1979,
        "industry": "综合金融与实业投资跨国集团",
        "revenue_m": "139,276"
    },
    {
        "rank": 60,
        "name_cn": "威瑞森电信",
        "name_en": "Verizon Communications Inc.",
        "founder_en": "Bell Atlantic & GTE Merger",
        "founder_cn": "大西洋贝尔与GTE合并组建",
        "country": "🇺🇸 美国",
        "hq": "纽约州 纽约",
        "founded_year": 1983,
        "industry": "无线蜂窝网络与光纤宽带服务",
        "revenue_m": "138,191"
    },
    {
        "rank": 61,
        "name_cn": "Phillips 66公司",
        "name_en": "Phillips 66",
        "founder_en": "Frank Phillips, Lee Eldas Phillips",
        "founder_cn": "法兰克·菲利普斯、L.E. 菲利普斯",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 休斯敦",
        "founded_year": 1917,
        "industry": "原油炼化、中游管道与特种化学品",
        "revenue_m": "136,560"
    },
    {
        "rank": 62,
        "name_cn": "汇丰银行控股公司",
        "name_en": "HSBC Holdings plc",
        "founder_en": "Thomas Sutherland",
        "founder_cn": "托马斯·萨瑟兰德",
        "country": "🇬🇧 英国",
        "hq": "伦敦",
        "founded_year": 1865,
        "industry": "国际商业银行、贸易融资与财富管理",
        "revenue_m": "135,617"
    },
    {
        "rank": 63,
        "name_cn": "马拉松原油公司",
        "name_en": "Marathon Petroleum Corporation",
        "founder_en": "The Ohio Oil Company Spinoff",
        "founder_cn": "俄亥俄石油公司 (分拆重组)",
        "country": "🇺🇸 美国",
        "hq": "俄亥俄州 芬德利",
        "founded_year": 1887,
        "industry": "炼油一体化与油气零售终端",
        "revenue_m": "135,222"
    },
    {
        "rank": 64,
        "name_cn": "俄罗斯联邦储蓄银行",
        "name_en": "Sberbank of Russia",
        "founder_en": "Decree of Tsar Nicholas I",
        "founder_cn": "沙皇尼古拉一世法令创办",
        "country": "🇷🇺 俄罗斯",
        "hq": "莫斯科",
        "founded_year": 1841,
        "industry": "商业银行、零售信贷与金融科技",
        "revenue_m": "135,076"
    },
    {
        "rank": 65,
        "name_cn": "德国电信",
        "name_en": "Deutsche Telekom AG",
        "founder_en": "Deutsche Bundespost Telecom Spinoff",
        "founder_cn": "德国联邦邮政电信改制",
        "country": "🇩🇪 德国",
        "hq": "波恩",
        "founded_year": 1995,
        "industry": "综合电信运营 (T-Mobile) 与企业IT",
        "revenue_m": "134,313"
    },
    {
        "rank": 66,
        "name_cn": "中国交通建设集团有限公司",
        "name_en": "China Communications Construction Group (CCCC)",
        "founder_en": "CHEC & CRBC Merger",
        "founder_cn": "中国港湾与中国路桥合并重组",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 2005,
        "industry": "港口疏浚、公路特大桥梁基建",
        "revenue_m": "134,089"
    },
    {
        "rank": 67,
        "name_cn": "安联保险集团",
        "name_en": "Allianz SE",
        "founder_en": "Carl von Thieme, Wilhelm von Finck",
        "founder_cn": "卡尔·冯·蒂梅、威廉·冯·芬克",
        "country": "🇩🇪 德国",
        "hq": "慕尼黑",
        "founded_year": 1890,
        "industry": "全球综合保险、再保险与PIMCO资管",
        "revenue_m": "133,984"
    },
    {
        "rank": 68,
        "name_cn": "中国华润有限公司",
        "name_en": "China Resources (Holdings) Co., Ltd.",
        "founder_en": "Qin Bangxian (Bo Gu), Yang Lianfang",
        "founder_cn": "秦邦宪 (博古)、杨廉芳 (联和行前身)",
        "country": "🇨🇳 中国",
        "hq": "深圳 / 香港",
        "founded_year": 1938,
        "industry": "大消费、大健康、城市建设与能源",
        "revenue_m": "133,290"
    },
    {
        "rank": 69,
        "name_cn": "StoneX集团",
        "name_en": "StoneX Group Inc.",
        "founder_en": "Saul Stone",
        "founder_cn": "索尔·斯通",
        "country": "🇺🇸 美国",
        "hq": "纽约州 纽约",
        "founded_year": 1924,
        "industry": "全球金融市场做市与衍生品清算",
        "revenue_m": "132,378"
    },
    {
        "rank": 70,
        "name_cn": "州立农业保险公司",
        "name_en": "State Farm Insurance",
        "founder_en": "George J. Mecherle",
        "founder_cn": "乔治·J·梅切尔",
        "country": "🇺🇸 美国",
        "hq": "伊利诺伊州 布卢明顿",
        "founded_year": 1922,
        "industry": "汽车与财产互助保险服务",
        "revenue_m": "132,312"
    },
    {
        "rank": 71,
        "name_cn": "房地美",
        "name_en": "Freddie Mac (Federal Home Loan Mortgage Corp.)",
        "founder_en": "US Congress (Emergency Home Finance Act)",
        "founder_cn": "美国国会 (紧急住房金融法案特许设立)",
        "country": "🇺🇸 美国",
        "hq": "弗吉尼亚州 麦克莱恩",
        "founded_year": 1970,
        "industry": "住房抵押贷款二级市场支持",
        "revenue_m": "131,688"
    },
    {
        "rank": 72,
        "name_cn": "现代汽车",
        "name_en": "Hyundai Motor Company",
        "founder_en": "Chung Ju-yung",
        "founder_cn": "郑周永",
        "country": "🇰🇷 韩国",
        "hq": "首尔",
        "founded_year": 1967,
        "industry": "汽车制造、电动汽车与机器人研发",
        "revenue_m": "131,021"
    },
    {
        "rank": 73,
        "name_cn": "哈门那公司",
        "name_en": "Humana Inc.",
        "founder_en": "David A. Jones Sr., Wendell Cherry",
        "founder_cn": "大卫·A·琼斯、温德尔·切利",
        "country": "🇺🇸 美国",
        "hq": "肯塔基州 路易斯维尔",
        "founded_year": 1961,
        "industry": "医保优势计划与整合型医疗管理",
        "revenue_m": "129,664"
    },
    {
        "rank": 74,
        "name_cn": "法国电力公司",
        "name_en": "Électricité de France (EDF)",
        "founder_en": "French Government",
        "founder_cn": "法国政府 (电力国有化整合设立)",
        "country": "🇫🇷 法国",
        "hq": "巴黎",
        "founded_year": 1946,
        "industry": "核能发电、清洁公用事业与电网",
        "revenue_m": "127,754"
    },
    {
        "rank": 75,
        "name_cn": "美国电话电报公司",
        "name_en": "AT&T Inc.",
        "founder_en": "Alexander Graham Bell, Gardiner Greene Hubbard",
        "founder_cn": "亚历山大·格拉汉姆·贝尔、加德纳·格林·哈伯德",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 达拉斯",
        "founded_year": 1885,
        "industry": "5G无线通信与企业级光纤宽带",
        "revenue_m": "125,648"
    },
    {
        "rank": 76,
        "name_cn": "三菱商事株式会社",
        "name_en": "Mitsubishi Corporation",
        "founder_en": "Yataro Iwasaki",
        "founder_cn": "岩崎弥太郎",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1954,
        "industry": "综合商社 (能源/金属/基础设施/消费)",
        "revenue_m": "125,512"
    },
    {
        "rank": 77,
        "name_cn": "高盛集团",
        "name_en": "The Goldman Sachs Group, Inc.",
        "founder_en": "Marcus Goldman, Samuel Sachs",
        "founder_cn": "马库斯·高盛、塞缪尔·萨克斯",
        "country": "🇺🇸 美国",
        "hq": "纽约州 纽约",
        "founded_year": 1869,
        "industry": "投资银行、证券承销与机构资产管理",
        "revenue_m": "125,097"
    },
    {
        "rank": 78,
        "name_cn": "恒力集团有限公司",
        "name_en": "Hengli Group Co., Ltd.",
        "founder_en": "Chen Jianhua, Fan Hongwei",
        "founder_cn": "陈建华、范红卫",
        "country": "🇨🇳 中国",
        "hq": "江苏省 苏州",
        "founded_year": 1994,
        "industry": "炼油化工、PTA聚酯与高端化纤纺织",
        "revenue_m": "125,085"
    },
    {
        "rank": 79,
        "name_cn": "美国康卡斯特电信公司",
        "name_en": "Comcast Corporation",
        "founder_en": "Ralph J. Roberts, Daniel Aaron, Julian A. Brodsky",
        "founder_cn": "拉尔夫·J·罗伯茨、丹尼尔·亚伦、朱利安·布罗茨基",
        "country": "🇺🇸 美国",
        "hq": "宾夕法尼亚州 费城",
        "founded_year": 1963,
        "industry": "有线宽带、NBC环球传媒与主题乐园",
        "revenue_m": "123,707"
    },
    {
        "rank": 80,
        "name_cn": "美国富国银行",
        "name_en": "Wells Fargo & Company",
        "founder_en": "Henry Wells, William G. Fargo",
        "founder_cn": "亨利·韦尔斯、威廉·G·法戈",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 旧金山",
        "founded_year": 1852,
        "industry": "零售商业银行与小微企业金融",
        "revenue_m": "123,529"
    },
    {
        "rank": 81,
        "name_cn": "华为投资控股有限公司",
        "name_en": "Huawei Investment & Holding Co., Ltd.",
        "founder_en": "Ren Zhengfei",
        "founder_cn": "任正非",
        "country": "🇨🇳 中国",
        "hq": "广东 深圳",
        "founded_year": 1987,
        "industry": "ICT基础设施、智能手机与鸿蒙/昇腾AI",
        "revenue_m": "122,563"
    },
    {
        "rank": 82,
        "name_cn": "台积公司",
        "name_en": "Taiwan Semiconductor Manufacturing Co., Ltd. (TSMC)",
        "founder_en": "Morris Chang",
        "founder_cn": "张忠谋",
        "country": "🇹🇼 中国台湾",
        "hq": "新竹科学园区",
        "founded_year": 1987,
        "industry": "半导体纯晶圆代工制造",
        "revenue_m": "122,258"
    },
    {
        "rank": 83,
        "name_cn": "中国海洋石油集团有限公司",
        "name_en": "China National Offshore Oil Corporation (CNOOC)",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (对外合作开采海洋石油设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1982,
        "industry": "海洋油气勘探开发与LNG贸易",
        "revenue_m": "120,915"
    },
    {
        "rank": 84,
        "name_cn": "摩根士丹利",
        "name_en": "Morgan Stanley",
        "founder_en": "Henry Sturgis Morgan, Harold Stanley",
        "founder_cn": "亨利·S·摩根、哈罗德·斯坦利",
        "country": "🇺🇸 美国",
        "hq": "纽约州 纽约",
        "founded_year": 1935,
        "industry": "投资银行、机构证券交易与全球财富管理",
        "revenue_m": "119,662"
    },
    {
        "rank": 85,
        "name_cn": "信实工业公司",
        "name_en": "Reliance Industries Limited",
        "founder_en": "Dhirubhai Ambani",
        "founder_cn": "迪鲁巴伊·安巴尼",
        "country": "🇮🇳 印度",
        "hq": "孟买",
        "founded_year": 1958,
        "industry": "石油石化炼解、Jio电信与零售连锁",
        "revenue_m": "119,653"
    },
    {
        "rank": 86,
        "name_cn": "中国南方电网有限责任公司",
        "name_en": "China Southern Power Grid Co., Ltd.",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (电力体制改革分立设立)",
        "country": "🇨🇳 中国",
        "hq": "广东 广州",
        "founded_year": 2002,
        "industry": "南方五省区电网运营与绿色电力供应",
        "revenue_m": "118,797"
    },
    {
        "rank": 87,
        "name_cn": "山东能源集团有限公司",
        "name_en": "Shandong Energy Group Co., Ltd.",
        "founder_en": "Shandong Provincial People's Government",
        "founder_cn": "山东省人民政府 (矿业集团联合重组)",
        "country": "🇨🇳 中国",
        "hq": "山东 济南",
        "founded_year": 2011,
        "industry": "煤炭开采、煤电化工与高端装备",
        "revenue_m": "116,559"
    },
    {
        "rank": 88,
        "name_cn": "瓦莱罗能源公司",
        "name_en": "Valero Energy Corporation",
        "founder_en": "Bill Greehey",
        "founder_cn": "比尔·格里希 (沿海各州天然气分拆)",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 圣安东尼奥",
        "founded_year": 1980,
        "industry": "独立原油精炼与可再生燃料制造",
        "revenue_m": "115,939"
    },
    {
        "rank": 89,
        "name_cn": "俄罗斯天然气工业股份公司",
        "name_en": "Gazprom PJSC",
        "founder_en": "Ministry of Gas Industry of the USSR",
        "founder_cn": "苏联天然气工业部改制设立",
        "country": "🇷🇺 俄罗斯",
        "hq": "圣彼得堡",
        "founded_year": 1989,
        "industry": "天然气勘探、管网运输与能源出口",
        "revenue_m": "114,868"
    },
    {
        "rank": 90,
        "name_cn": "戴尔科技公司",
        "name_en": "Dell Technologies Inc.",
        "founder_en": "Michael Dell",
        "founder_cn": "迈克尔·戴尔",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 朗德罗克",
        "founded_year": 1984,
        "industry": "企业服务器、AI算力集群与PC硬件",
        "revenue_m": "113,538"
    },
    {
        "rank": 91,
        "name_cn": "比亚迪股份有限公司",
        "name_en": "BYD Company Limited",
        "founder_en": "Wang Chuanfu",
        "founder_cn": "王传福",
        "country": "🇨🇳 中国",
        "hq": "广东 深圳",
        "founded_year": 1995,
        "industry": "新能源乘用车、刀片电池与电子代工",
        "revenue_m": "111,853"
    },
    {
        "rank": 92,
        "name_cn": "印度人寿保险公司",
        "name_en": "Life Insurance Corporation of India (LIC)",
        "founder_en": "Parliament of India",
        "founder_cn": "印度议会 (寿险国有化整合法令)",
        "country": "🇮🇳 印度",
        "hq": "孟买",
        "founded_year": 1956,
        "industry": "人寿保险与综合主权资产管理",
        "revenue_m": "110,325"
    },
    {
        "rank": 93,
        "name_cn": "雀巢公司",
        "name_en": "Nestlé S.A.",
        "founder_en": "Henri Nestlé, Charles Page, George Page",
        "founder_cn": "亨利·雀巢、查尔斯·佩奇、乔治·佩奇",
        "country": "🇨🇭 瑞士",
        "hq": "沃韦",
        "founded_year": 1866,
        "industry": "包装食品饮料、咖啡与宠物营养品",
        "revenue_m": "107,737"
    },
    {
        "rank": 94,
        "name_cn": "安盛",
        "name_en": "AXA S.A.",
        "founder_en": "Claude Bébéar",
        "founder_cn": "克劳德·贝贝阿 (互助保险整合)",
        "country": "🇫🇷 法国",
        "hq": "巴黎",
        "founded_year": 1817,
        "industry": "综合保险保障与全球资产管理",
        "revenue_m": "107,710"
    },
    {
        "rank": 95,
        "name_cn": "Equinor公司",
        "name_en": "Equinor ASA (Statoil)",
        "founder_en": "Parliament of Norway (Storting)",
        "founder_cn": "挪威议会法令设立 (原挪威国家石油)",
        "country": "🇳🇴 挪威",
        "hq": "斯塔万格",
        "founded_year": 1972,
        "industry": "北海油气开采与海上风电新能源",
        "revenue_m": "106,462"
    },
    {
        "rank": 96,
        "name_cn": "塔吉特公司",
        "name_en": "Target Corporation",
        "founder_en": "George Draper Dayton",
        "founder_cn": "乔治·德雷珀·戴顿",
        "country": "🇺🇸 美国",
        "hq": "明尼苏达州 明尼阿波利斯",
        "founded_year": 1902,
        "industry": "时尚折扣百货与全渠道零售",
        "revenue_m": "104,780"
    },
    {
        "rank": 97,
        "name_cn": "腾讯控股有限公司",
        "name_en": "Tencent Holdings Limited",
        "founder_en": "Pony Ma, Zhang Zhidong, Xu Chenye, Chen Yidan, Zeng Liqing",
        "founder_cn": "马化腾、张志东、许晨晔、陈一丹、曾李青",
        "country": "🇨🇳 中国",
        "hq": "广东 深圳",
        "founded_year": 1998,
        "industry": "社交平台、数字内容、金融科技与云",
        "revenue_m": "104,591"
    },
    {
        "rank": 98,
        "name_cn": "皇家阿霍德德尔海兹集团",
        "name_en": "Koninklijke Ahold Delhaize N.V.",
        "founder_en": "Albert Heijn, Jules Delhaize, Edouard Delhaize",
        "founder_cn": "阿尔伯特·海恩、于勒·德尔海兹、爱德华·德尔海兹",
        "country": "🇳🇱 荷兰",
        "hq": "赞丹",
        "founded_year": 1867,
        "industry": "连锁食品超市与数字生鲜零售",
        "revenue_m": "104,165"
    },
    {
        "rank": 99,
        "name_cn": "中国五矿集团有限公司",
        "name_en": "China Minmetals Corporation",
        "founder_en": "Ministry of Foreign Trade of China",
        "founder_cn": "中央人民政府贸易部 (中国矿产公司前身)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1950,
        "industry": "金属矿产资源开发与冶金工程",
        "revenue_m": "104,139"
    },
    {
        "rank": 100,
        "name_cn": "中国宝武钢铁集团有限公司",
        "name_en": "China Baowu Steel Group Corp., Ltd.",
        "founder_en": "State Council of China (Baosteel & WISCO Merger)",
        "founder_cn": "国务院 (宝钢与武钢联合重组设立)",
        "country": "🇨🇳 中国",
        "hq": "上海",
        "founded_year": 1890,
        "industry": "钢铁冶金与高端材料生态圈",
        "revenue_m": "102,980"
    }
]
