# -*- coding: utf-8 -*-
"""Data part 4: Companies 301 to 400"""

DATA_PART4 = [
    {
        "rank": 301,
        "name_cn": "联合服务汽车协会",
        "name_en": "United Services Automobile Association (USAA)",
        "founder_en": "William Garrison & 25 US Army Officers",
        "founder_cn": "威廉·加里森等25位美军军官创立",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 圣安东尼奥",
        "founded_year": 1922,
        "industry": "军人及家属综合金融与财产保险",
        "revenue_m": "51,499"
    },
    {
        "rank": 302,
        "name_cn": "新加坡奥兰集团",
        "name_en": "Olam Group Limited",
        "founder_en": "Sunny Verghese (Kewalram Chanrai Group)",
        "founder_cn": "桑尼·韦尔盖塞 (基瓦拉姆集团发起)",
        "country": "🇸🇬 新加坡",
        "hq": "新加坡",
        "founded_year": 1989,
        "industry": "全球农产品大宗加工贸易 (可可/咖啡/坚果)",
        "revenue_m": "51,492"
    },
    {
        "rank": 303,
        "name_cn": "意大利联合圣保罗银行",
        "name_en": "Intesa Sanpaolo S.p.A.",
        "founder_en": "Banca Intesa & Sanpaolo IMI Merger",
        "founder_cn": "意大利商业银行与圣保罗IMI银行合并",
        "country": "🇮🇹 意大利",
        "hq": "都灵 / 米兰",
        "founded_year": 1563,
        "industry": "商业银行、中小企业金融与财富管理",
        "revenue_m": "51,445"
    },
    {
        "rank": 304,
        "name_cn": "拜耳集团",
        "name_en": "Bayer AG",
        "founder_en": "Friedrich Bayer, Johann Friedrich Weskott",
        "founder_cn": "弗里德里希·拜耳、约翰·韦斯科特",
        "country": "🇩🇪 德国",
        "hq": "勒沃库森",
        "founded_year": 1863,
        "industry": "作物科学种子化肥、处方药与健康消费品",
        "revenue_m": "51,405"
    },
    {
        "rank": 305,
        "name_cn": "Iberdrola公司",
        "name_en": "Iberdrola, S.A.",
        "founder_en": "Hidroeléctrica Española & Iberduero Merger",
        "founder_cn": "西班牙水电与伊贝尔杜埃罗合并组建",
        "country": "🇪🇸 西班牙",
        "hq": "毕尔巴鄂",
        "founded_year": 1901,
        "industry": "全球海上陆上风电、光伏与清洁输配电网",
        "revenue_m": "51,373"
    },
    {
        "rank": 306,
        "name_cn": "敬业集团有限公司",
        "name_en": "Jingye Group Co., Ltd.",
        "founder_en": "Li Gengsheng",
        "founder_cn": "李赶坡",
        "country": "🇨🇳 中国",
        "hq": "河北 石家庄",
        "founded_year": 1988,
        "industry": "螺纹钢、中厚板钢铁冶炼与英国钢铁(British Steel)",
        "revenue_m": "51,354"
    },
    {
        "rank": 307,
        "name_cn": "必和必拓集团",
        "name_en": "BHP Group Limited",
        "founder_en": "Charles Rasp (Broken Hill Proprietary)",
        "founder_cn": "查尔斯·拉斯普 (布罗肯希尔控股创立)",
        "country": "🇦🇺 澳大利亚",
        "hq": "墨尔本",
        "founded_year": 1885,
        "industry": "铁矿石、铜矿、冶金煤与钾肥资源开采",
        "revenue_m": "51,262"
    },
    {
        "rank": 308,
        "name_cn": "巴西联邦储蓄银行",
        "name_en": "Caixa Econômica Federal",
        "founder_en": "Decree of Emperor Pedro II of Brazil",
        "founder_cn": "巴西帝国皇帝佩德罗二世法令创立",
        "country": "🇧🇷 巴西",
        "hq": "巴西利亚",
        "founded_year": 1861,
        "industry": "国有储蓄银行、住房公积金与社会普惠金融",
        "revenue_m": "51,096"
    },
    {
        "rank": 309,
        "name_cn": "浙江省交通投资集团有限公司",
        "name_en": "Zhejiang Communications Investment Group Co., Ltd.",
        "founder_en": "Zhejiang Provincial People's Government",
        "founder_cn": "浙江省人民政府 (省属交通国有资产重组设立)",
        "country": "🇨🇳 中国",
        "hq": "浙江 杭州",
        "founded_year": 2001,
        "industry": "高速公路、铁路轨道交通投资建设运营",
        "revenue_m": "50,819"
    },
    {
        "rank": 310,
        "name_cn": "MS&AD保险集团控股有限公司",
        "name_en": "MS&AD Insurance Group Holdings, Inc.",
        "founder_en": "Mitsui Sumitomo & Aioi Nissay Dowa Merger",
        "founder_cn": "三井住友海上与爱和谊日生同和合并",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 2008,
        "industry": "财产意外火灾保险与海外综合险企",
        "revenue_m": "50,780"
    },
    {
        "rank": 311,
        "name_cn": "美团公司",
        "name_en": "Meituan",
        "founder_en": "Wang Xing, Mu Rongjun, Wang Huiwen",
        "founder_cn": "王兴、穆荣均、王慧文",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 2010,
        "industry": "本地生活外卖、即时零售与科技零售生态",
        "revenue_m": "50,761"
    },
    {
        "rank": 312,
        "name_cn": "美国教师退休基金会",
        "name_en": "TIAA (Teachers Insurance and Annuity Association)",
        "founder_en": "Andrew Carnegie (Carnegie Foundation)",
        "founder_cn": "安德鲁·卡内基 (卡内基基金会创立)",
        "country": "🇺🇸 美国",
        "hq": "纽约州 纽约",
        "founded_year": 1918,
        "industry": "高校教职员工养老金年金与资管 (Nuveen)",
        "revenue_m": "50,605"
    },
    {
        "rank": 313,
        "name_cn": "美国利宝互助保险集团",
        "name_en": "Liberty Mutual Insurance Group",
        "founder_en": "Massachusetts Legislature Workers' Comp Act",
        "founder_cn": "马萨诸塞州议会工伤赔偿法案特许组建",
        "country": "🇺🇸 美国",
        "hq": "马萨诸塞州 波士顿",
        "founded_year": 1912,
        "industry": "全球财产意外险、商业责任险与车险",
        "revenue_m": "50,465"
    },
    {
        "rank": 314,
        "name_cn": "HD现代公司",
        "name_en": "HD Hyundai Co., Ltd. (Hyundai Heavy Industries)",
        "founder_en": "Chung Ju-yung",
        "founder_cn": "郑周永",
        "country": "🇰🇷 韩国",
        "hq": "首尔 / 蔚山",
        "founded_year": 1972,
        "industry": "大型LNG集装箱船舶制造、重工与工程机械",
        "revenue_m": "50,128"
    },
    {
        "rank": 315,
        "name_cn": "法国威立雅环境集团",
        "name_en": "Veolia Environnement S.A.",
        "founder_en": "Decree of Napoleon III (Compagnie Générale des Eaux)",
        "founder_cn": "拿破仑三世法令特许创立 (原法国通用水务)",
        "country": "🇫🇷 法国",
        "hq": "欧贝维利耶",
        "founded_year": 1853,
        "industry": "水务处理运营、固废资源循环利用与节能服务",
        "revenue_m": "50,075"
    },
    {
        "rank": 316,
        "name_cn": "电装公司",
        "name_en": "Denso Corporation",
        "founder_en": "Toyota Motor Electrical Equipment Spinoff",
        "founder_cn": "丰田汽车电气配件部独立分拆创立",
        "country": "🇯🇵 日本",
        "hq": "爱知县 刈谷市",
        "founded_year": 1949,
        "industry": "汽车空调热管理、电驱系统与高精度传感器",
        "revenue_m": "50,029"
    },
    {
        "rank": 317,
        "name_cn": "欧莱雅",
        "name_en": "L'Oréal S.A.",
        "founder_en": "Eugène Schueller",
        "founder_cn": "欧仁·舒莱尔",
        "country": "🇫🇷 法国",
        "hq": "克利希",
        "founded_year": 1909,
        "industry": "高档美妆护肤品 (兰蔻/赫莲娜/圣罗兰) 与洗护发",
        "revenue_m": "49,687"
    },
    {
        "rank": 318,
        "name_cn": "日本明治安田生命保险公司",
        "name_en": "Meiji Yasuda Life Insurance Company",
        "founder_en": "Meiji Life & Yasuda Life Merger",
        "founder_cn": "明治生命与安田生命合并组建",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1881,
        "industry": "相互人寿保险保障与老年看护养老服务",
        "revenue_m": "49,378"
    },
    {
        "rank": 319,
        "name_cn": "东风汽车集团有限公司",
        "name_en": "Dongfeng Motor Corporation",
        "founder_en": "Central People's Government of China (Second Automobile Works)",
        "founder_cn": "中央人民政府 (第二汽车制造厂/二汽改制设立)",
        "country": "🇨🇳 中国",
        "hq": "湖北 武汉",
        "founded_year": 1969,
        "industry": "商用车卡车制造、岚图/猛士高端新能源与乘用车",
        "revenue_m": "49,247"
    },
    {
        "rank": 320,
        "name_cn": "美洲电信",
        "name_en": "América Móvil, S.A.B. de C.V.",
        "founder_en": "Carlos Slim",
        "founder_cn": "卡洛斯·斯利姆",
        "country": "🇲🇽 墨西哥",
        "hq": "墨西哥城",
        "founded_year": 2000,
        "industry": "拉美地区电信运营 (Claro/Telcel) 与宽带网络",
        "revenue_m": "49,123"
    },
    {
        "rank": 321,
        "name_cn": "Travelers公司",
        "name_en": "The Travelers Companies, Inc.",
        "founder_en": "James G. Batterson",
        "founder_cn": "詹姆斯·G·巴特森",
        "country": "🇺🇸 美国",
        "hq": "纽约州 纽约",
        "founded_year": 1853,
        "industry": "商业财产险、意外责任险与个人综合保险",
        "revenue_m": "48,828"
    },
    {
        "rank": 322,
        "name_cn": "沃尔沃集团",
        "name_en": "AB Volvo (Volvo Group)",
        "founder_en": "Assar Gabrielsson, Gustav Larson",
        "founder_cn": "阿萨尔·加布里尔森、古斯塔夫·拉尔森",
        "country": "🇸🇪 瑞典",
        "hq": "哥德堡",
        "founded_year": 1927,
        "industry": "重型商用卡车 (Volvo/Mack)、客车与建筑设备",
        "revenue_m": "48,828"
    },
    {
        "rank": 323,
        "name_cn": "贺利氏控股集团",
        "name_en": "Heraeus Holding GmbH",
        "founder_en": "Wilhelm Carl Heraeus",
        "founder_cn": "威廉·卡尔·贺利氏",
        "country": "🇩🇪 德国",
        "hq": "哈瑙",
        "founded_year": 1851,
        "industry": "贵金属精炼加工、石英玻璃与半导体先进材料",
        "revenue_m": "48,719"
    },
    {
        "rank": 324,
        "name_cn": "住友商事",
        "name_en": "Sumitomo Corporation",
        "founder_en": "Masatomo Sumitomo (Sumitomo Clan foundation)",
        "founder_cn": "住友政友 (住友家族基业演变)",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1919,
        "industry": "综合商社 (钢铁管材/交通基建/化学品/媒体)",
        "revenue_m": "48,684"
    },
    {
        "rank": 325,
        "name_cn": "紫金矿业集团股份有限公司",
        "name_en": "Zijin Mining Group Co., Ltd.",
        "founder_en": "Chen Jinghe",
        "founder_cn": "陈景河 (上杭县矿产公司改组)",
        "country": "🇨🇳 中国",
        "hq": "福建 龙岩 / 上杭",
        "founded_year": 1993,
        "industry": "跨国铜、金、锌、锂战略矿产资源开采冶炼",
        "revenue_m": "48,566"
    },
    {
        "rank": 326,
        "name_cn": "浦项制铁控股公司",
        "name_en": "POSCO Holdings Inc.",
        "founder_en": "Park Tae-joon (Pohang Iron & Steel)",
        "founder_cn": "朴泰俊 (韩国政府设立浦项钢铁)",
        "country": "🇰🇷 韩国",
        "hq": "庆尚北道 浦项市 / 首尔",
        "founded_year": 1968,
        "industry": "优质汽车高强钢板、二次锂电正负极材料与氢能",
        "revenue_m": "48,529"
    },
    {
        "rank": 327,
        "name_cn": "法国国营铁路集团",
        "name_en": "SNCF (Société Nationale des Chemins de fer Français)",
        "founder_en": "French Government (Nationalization of 5 Railways)",
        "founder_cn": "法国政府 (五大主要铁路公司国有化合并)",
        "country": "🇫🇷 法国",
        "hq": "圣但尼",
        "founded_year": 1938,
        "industry": "高速铁路客运 (TGV) 与欧洲现代货运物流",
        "revenue_m": "48,490"
    },
    {
        "rank": 328,
        "name_cn": "百时美施贵宝公司",
        "name_en": "Bristol-Myers Squibb Company (BMS)",
        "founder_en": "Edward Robinson Squibb, William McLaren Bristol, John Ripley Myers",
        "founder_cn": "爱德华·R·施贵宝、威廉·M·百时美、约翰·R·迈尔斯",
        "country": "🇺🇸 美国",
        "hq": "新泽西州 普林斯顿",
        "founded_year": 1858,
        "industry": "肿瘤免疫抑制剂 (Opdivo) 与血液心血管创新药",
        "revenue_m": "48,194"
    },
    {
        "rank": 329,
        "name_cn": "可口可乐公司",
        "name_en": "The Coca-Cola Company",
        "founder_en": "John Stith Pemberton, Asa Griggs Candler",
        "founder_cn": "约翰·彭伯顿、阿萨·坎德勒",
        "country": "🇺🇸 美国",
        "hq": "佐治亚州 亚特兰大",
        "founded_year": 1892,
        "industry": "非酒精饮料浓缩液研发与全球品牌运营",
        "revenue_m": "47,941"
    },
    {
        "rank": 330,
        "name_cn": "日本出光兴产株式会社",
        "name_en": "Idemitsu Kosan Co., Ltd.",
        "founder_en": "Sazo Idemitsu",
        "founder_cn": "出光佐三",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1911,
        "industry": "石油炼化、特种润滑油与OLED显示发光材料",
        "revenue_m": "47,289"
    },
    {
        "rank": 331,
        "name_cn": "沃达丰集团",
        "name_en": "Vodafone Group Plc",
        "founder_en": "Gerry Whent, Ernest Harrison (Racal Spinoff)",
        "founder_cn": "格里·温特、欧内斯特·哈里森 (雷卡尔分拆)",
        "country": "🇬🇧 英国",
        "hq": "纽伯里",
        "founded_year": 1984,
        "industry": "跨国移动电信网络、IoT全球连接与企业宽带",
        "revenue_m": "46,906"
    },
    {
        "rank": 332,
        "name_cn": "乔治威斯顿公司",
        "name_en": "George Weston Limited",
        "founder_en": "George Weston",
        "founder_cn": "乔治·威斯顿",
        "country": "🇨🇦 加拿大",
        "hq": "多伦多",
        "founded_year": 1882,
        "industry": "连锁生鲜食品零售 (Loblaw) 与烘焙食品加工",
        "revenue_m": "46,823"
    },
    {
        "rank": 333,
        "name_cn": "诺和诺德公司",
        "name_en": "Novo Nordisk A/S",
        "founder_en": "August Krogh, Marie Krogh, Hans Christian Hagedorn",
        "founder_cn": "奥古斯特·克罗、玛丽·克罗、汉斯·C·哈格多恩",
        "country": "🇩🇰 丹麦",
        "hq": "鲍斯韦",
        "founded_year": 1923,
        "industry": "降糖与减重GLP-1药物 (司美格鲁肽) 及胰岛素",
        "revenue_m": "46,711"
    },
    {
        "rank": 334,
        "name_cn": "加拿大枫信金融控股公司",
        "name_en": "Fairfax Financial Holdings Limited",
        "founder_en": "Prem Watsa",
        "founder_cn": "普雷姆·瓦萨",
        "country": "🇨🇦 加拿大",
        "hq": "多伦多",
        "founded_year": 1985,
        "industry": "财产意外再保险与全球长期价值投资控股",
        "revenue_m": "46,674"
    },
    {
        "rank": 335,
        "name_cn": "Enbridge公司",
        "name_en": "Enbridge Inc.",
        "founder_en": "Imperial Oil (Interprovincial Pipe Line)",
        "founder_cn": "帝国石油发起设立省际管道公司",
        "country": "🇨🇦 加拿大",
        "hq": "卡尔加里",
        "founded_year": 1949,
        "industry": "北美大型原油及天然气长输管道运输",
        "revenue_m": "46,659"
    },
    {
        "rank": 336,
        "name_cn": "耐克公司",
        "name_en": "NIKE, Inc.",
        "founder_en": "Phil Knight, Bill Bowerman (Blue Ribbon Sports)",
        "founder_cn": "菲尔·奈特、比尔·鲍尔曼 (蓝带体育前身)",
        "country": "🇺🇸 美国",
        "hq": "俄勒冈州 比弗顿",
        "founded_year": 1964,
        "industry": "专业运动鞋类、运动服饰与数字运动生态",
        "revenue_m": "46,309"
    },
    {
        "rank": 337,
        "name_cn": "立讯精密工业股份有限公司",
        "name_en": "Luxshare Precision Industry Co., Ltd.",
        "founder_en": "Wang Laichun, Wang Laisheng",
        "founder_cn": "王来春、王来胜",
        "country": "🇨🇳 中国",
        "hq": "广东 东莞",
        "founded_year": 2004,
        "industry": "精密连接器、消费电子整机组装与汽车智能线束",
        "revenue_m": "46,238"
    },
    {
        "rank": 338,
        "name_cn": "康帕斯集团",
        "name_en": "Compass Group PLC",
        "founder_en": "Jack Bateman (Factory Canteens)",
        "founder_cn": "杰克·贝特曼 (工厂食堂服务演变)",
        "country": "🇬🇧 英国",
        "hq": "切特西",
        "founded_year": 1941,
        "industry": "跨国企业、医院、学校合同制团餐管理服务",
        "revenue_m": "46,070"
    },
    {
        "rank": 339,
        "name_cn": "万通互惠理财公司",
        "name_en": "Massachusetts Mutual Life Insurance Company (MassMutual)",
        "founder_en": "George W. Rice",
        "founder_cn": "乔治·W·莱斯",
        "country": "🇺🇸 美国",
        "hq": "马萨诸塞州 斯普林菲尔德",
        "founded_year": 1851,
        "industry": "互助人寿保险、年金与霸菱(Barings)资产管理",
        "revenue_m": "46,054"
    },
    {
        "rank": 340,
        "name_cn": "苏商建设集团有限公司",
        "name_en": "Sushang Construction Group",
        "founder_en": "Yan Jiehe",
        "founder_cn": "严介和",
        "country": "🇨🇳 中国",
        "hq": "江苏 南京",
        "founded_year": 2012,
        "industry": "城市路桥基建、市政工程与水利工程总承包",
        "revenue_m": "45,907"
    },
    {
        "rank": 341,
        "name_cn": "GE航空航天公司",
        "name_en": "GE Aerospace (General Electric Company)",
        "founder_en": "Thomas Edison, Charles A. Coffin",
        "founder_cn": "托马斯·爱迪生、查尔斯·A·科芬",
        "country": "🇺🇸 美国",
        "hq": "俄亥俄州 埃文代尔",
        "founded_year": 1892,
        "industry": "商用客机发动机 (LEAP/GE9X) 与防务动力",
        "revenue_m": "45,855"
    },
    {
        "rank": 342,
        "name_cn": "迪尔公司",
        "name_en": "Deere & Company (John Deere)",
        "founder_en": "John Deere",
        "founder_cn": "约翰·迪尔",
        "country": "🇺🇸 美国",
        "hq": "伊利诺伊州 莫林",
        "founded_year": 1837,
        "industry": "大型农业机械装备、智能精准农机与工程设备",
        "revenue_m": "45,684"
    },
    {
        "rank": 343,
        "name_cn": "Plains GP Holdings公司",
        "name_en": "Plains GP Holdings, L.P.",
        "founder_en": "Plains All American Pipeline Founders",
        "founder_cn": "平原全美原油管道重组设立",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 休斯敦",
        "founded_year": 1998,
        "industry": "原油输送管道中游网络与码头储存中转",
        "revenue_m": "45,579"
    },
    {
        "rank": 344,
        "name_cn": "Orange公司",
        "name_en": "Orange S.A. (France Télécom)",
        "founder_en": "French Ministry of Posts and Telecommunications",
        "founder_cn": "法国邮电部电信部门私有化改制",
        "country": "🇫🇷 法国",
        "hq": "伊西莱穆利诺",
        "founded_year": 1990,
        "industry": "5G移动网络运营、海底光缆互联与企业数字化",
        "revenue_m": "45,563"
    },
    {
        "rank": 345,
        "name_cn": "英格卡集团",
        "name_en": "Ingka Holding B.V. (IKEA Group)",
        "founder_en": "Ingvar Kamprad",
        "founder_cn": "英格瓦·坎普拉德",
        "country": "🇳🇱 荷兰 / 🇸🇪 瑞典",
        "hq": "莱顿",
        "founded_year": 1943,
        "industry": "宜家(IKEA)全球平价家具零售与购物中心运营",
        "revenue_m": "45,531"
    },
    {
        "rank": 346,
        "name_cn": "Inditex公司",
        "name_en": "Inditex S.A.",
        "founder_en": "Amancio Ortega, Rosalía Mera",
        "founder_cn": "阿曼西奥·奥尔特加、罗莎莉娅·梅拉",
        "country": "🇪🇸 西班牙",
        "hq": "阿尔泰霍",
        "founded_year": 1975,
        "industry": "快时尚服饰品牌矩阵 (Zara/Pull&Bear/Massimo Dutti)",
        "revenue_m": "45,448"
    },
    {
        "rank": 347,
        "name_cn": "Molina Healthcare公司",
        "name_en": "Molina Healthcare, Inc.",
        "founder_en": "C. David Molina",
        "founder_cn": "C·大卫·莫利纳",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 长滩",
        "founded_year": 1980,
        "industry": "低收入与弱势群体联邦医疗健康保险 (Medicaid)",
        "revenue_m": "45,426"
    },
    {
        "rank": 348,
        "name_cn": "施耐德电气",
        "name_en": "Schneider Electric SE",
        "founder_en": "Adolphe Schneider, Joseph-Eugène Schneider",
        "founder_cn": "阿道夫·施耐德、约瑟夫-欧仁·施耐德",
        "country": "🇫🇷 法国",
        "hq": "吕埃-马尔迈松",
        "founded_year": 1836,
        "industry": "中低压配电能源管理、绿色微电网与工业自动化",
        "revenue_m": "45,288"
    },
    {
        "rank": 349,
        "name_cn": "上海浦东发展银行股份有限公司",
        "name_en": "Shanghai Pudong Development Bank (SPD Bank)",
        "founder_en": "Shanghai Municipal People's Government",
        "founder_cn": "上海市人民政府 (支持浦东开发开放组建)",
        "country": "🇨🇳 中国",
        "hq": "上海",
        "founded_year": 1992,
        "industry": "全国性股份制商业银行与科创长三角金融",
        "revenue_m": "45,246"
    },
    {
        "rank": 350,
        "name_cn": "森宝利公司",
        "name_en": "J Sainsbury plc",
        "founder_en": "John James Sainsbury, Mary Ann Sainsbury",
        "founder_cn": "约翰·詹姆斯·塞恩斯伯里、玛丽·安·塞恩斯伯里",
        "country": "🇬🇧 英国",
        "hq": "伦敦",
        "founded_year": 1869,
        "industry": "英国生鲜食品超市、便利店与百货零售 (Argos)",
        "revenue_m": "45,230"
    },
    {
        "rank": 351,
        "name_cn": "Netflix公司",
        "name_en": "Netflix, Inc.",
        "founder_en": "Reed Hastings, Marc Randolph",
        "founder_cn": "里德·哈斯廷斯、马克·伦道夫",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 洛斯加托斯",
        "founded_year": 1997,
        "industry": "全球流媒体订阅平台与原创影视内容制作",
        "revenue_m": "45,183"
    },
    {
        "rank": 352,
        "name_cn": "澳洲联邦银行",
        "name_en": "Commonwealth Bank of Australia (CBA)",
        "founder_en": "Parliament of Australia (Commonwealth Bank Act 1911)",
        "founder_cn": "澳大利亚联邦议会法令创立",
        "country": "🇦🇺 澳大利亚",
        "hq": "悉尼",
        "founded_year": 1911,
        "industry": "零售商业银行、住房抵押贷款与机构金融",
        "revenue_m": "45,108"
    },
    {
        "rank": 353,
        "name_cn": "联合信贷集团",
        "name_en": "UniCredit S.p.A.",
        "founder_en": "Credito Italiano & Unicredito Merger",
        "founder_cn": "意大利信贷银行与多家地区银行合并组建",
        "country": "🇮🇹 意大利",
        "hq": "米兰",
        "founded_year": 1870,
        "industry": "泛欧洲商业银行、企业贷款与跨境资本市场",
        "revenue_m": "44,708"
    },
    {
        "rank": 354,
        "name_cn": "伍尔沃斯集团",
        "name_en": "Woolworths Group Limited",
        "founder_en": "Percy Christmas, Stanley Chatterton, and founders",
        "founder_cn": "珀西·克里斯马斯、斯坦利·查特顿等5位联合创办",
        "country": "🇦🇺 澳大利亚",
        "hq": "悉尼",
        "founded_year": 1924,
        "industry": "生鲜超市连锁、食品供应链与折扣百货 (Big W)",
        "revenue_m": "44,693"
    },
    {
        "rank": 355,
        "name_cn": "汉莎集团",
        "name_en": "Deutsche Lufthansa AG",
        "founder_en": "Federal Republic of Germany Reorganization",
        "founder_cn": "联邦德国政府主导重组创立",
        "country": "🇩🇪 德国",
        "hq": "科隆",
        "founded_year": 1953,
        "industry": "跨国干线民用航空客运与航空机务维修 (Lufthansa Technik)",
        "revenue_m": "44,662"
    },
    {
        "rank": 356,
        "name_cn": "赛默飞世尔科技公司",
        "name_en": "Thermo Fisher Scientific Inc.",
        "founder_en": "George N. Hatsopoulos (Thermo Electron) & Chester Fisher",
        "founder_cn": "乔治·哈佐普洛斯、切斯特·费希尔",
        "country": "🇺🇸 美国",
        "hq": "马萨诸塞州 沃尔瑟姆",
        "founded_year": 1956,
        "industry": "生命科学科研仪器、色谱质谱仪与实验室试剂",
        "revenue_m": "44,556"
    },
    {
        "rank": 357,
        "name_cn": "加拿大帝国商业银行",
        "name_en": "Canadian Imperial Bank of Commerce (CIBC)",
        "founder_en": "Canadian Bank of Commerce & Imperial Bank Merger",
        "founder_cn": "加拿大商业银行与帝国银行合并组建",
        "country": "🇨🇦 加拿大",
        "hq": "多伦多",
        "founded_year": 1867,
        "industry": "全业务商业银行、个人信贷与跨境财富管理",
        "revenue_m": "44,358"
    },
    {
        "rank": 358,
        "name_cn": "雅培公司",
        "name_en": "Abbott Laboratories",
        "founder_en": "Wallace Calvin Abbott",
        "founder_cn": "华莱士·C·雅培",
        "country": "🇺🇸 美国",
        "hq": "伊利诺伊州 雅培公园",
        "founded_year": 1888,
        "industry": "连续血糖监测(CGM瞬感)、体外诊断与医学营养品",
        "revenue_m": "44,328"
    },
    {
        "rank": 359,
        "name_cn": "高通",
        "name_en": "Qualcomm Incorporated",
        "founder_en": "Irwin Jacobs, Andrew Viterbi, and 5 engineers",
        "founder_cn": "欧文·雅各布、安德鲁·维特比等7位联合创办",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 圣迭戈",
        "founded_year": 1985,
        "industry": "5G/6G无线通信芯片、骁龙移动处理器与车规芯片",
        "revenue_m": "44,284"
    },
    {
        "rank": 360,
        "name_cn": "瑞士再保险股份有限公司",
        "name_en": "Swiss Re Ltd",
        "founder_en": "Credit Suisse & Helvetia Insurance founders",
        "founder_cn": "瑞士信贷银行与赫尔维蒂亚保险联合发起",
        "country": "🇨🇭 瑞士",
        "hq": "苏黎世",
        "founded_year": 1863,
        "industry": "全球巨灾再保险、寿险再保险与气候风险方案",
        "revenue_m": "44,090"
    },
    {
        "rank": 361,
        "name_cn": "中国通用技术(集团)控股有限责任公司",
        "name_en": "China General Technology (Genertec)",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (中技/中仪/中矿等外贸央企联合设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1998,
        "industry": "高档数控机床母机、医药医疗健康与工程服务",
        "revenue_m": "44,033"
    },
    {
        "rank": 362,
        "name_cn": "澳新银行集团",
        "name_en": "Australia and New Zealand Banking Group (ANZ)",
        "founder_en": "Bank of Australasia Royal Charter",
        "founder_cn": "澳大拉西亚银行英国皇家特许设立演变",
        "country": "🇦🇺 澳大利亚",
        "hq": "墨尔本",
        "founded_year": 1835,
        "industry": "商业银行、按揭贷款与亚太企业贸易金融",
        "revenue_m": "43,836"
    },
    {
        "rank": 363,
        "name_cn": "Fomento Económico Mexicano公司",
        "name_en": "Fomento Económico Mexicano (FEMSA)",
        "founder_en": "Isaac Garza, José Calderón, José A. Muguerza",
        "founder_cn": "艾萨克·加尔萨、何塞·卡尔德隆 等",
        "country": "🇲🇽 墨西哥",
        "hq": "蒙特雷",
        "founded_year": 1890,
        "industry": "跨国连锁便利店 (OXXO) 与可口可乐装瓶分销",
        "revenue_m": "43,778"
    },
    {
        "rank": 364,
        "name_cn": "采埃孚",
        "name_en": "ZF Friedrichshafen AG",
        "founder_en": "Count Ferdinand von Zeppelin",
        "founder_cn": "斐迪南·冯·齐柏林伯爵 (飞艇齿轮厂演变)",
        "country": "🇩🇪 德国",
        "hq": "腓特烈港",
        "founded_year": 1915,
        "industry": "汽车传动变速箱 (8AT)、线控底盘与智能电驱动",
        "revenue_m": "43,774"
    },
    {
        "rank": 365,
        "name_cn": "西北互助人寿保险公司",
        "name_en": "The Northwestern Mutual Life Insurance Company",
        "founder_en": "John Johnston and 36 trustees",
        "founder_cn": "约翰·约翰斯顿与36位受托人设立",
        "country": "🇺🇸 美国",
        "hq": "威斯康星州 密尔沃基",
        "founded_year": 1857,
        "industry": "相互人寿保险、年金与高净值个人财富管理",
        "revenue_m": "43,676"
    },
    {
        "rank": 366,
        "name_cn": "中国华电集团有限公司",
        "name_en": "China Huadian Corporation",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (国家电力体制改革分立设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 2002,
        "industry": "火电清洁高效化、大型水电与陆上海上风光电",
        "revenue_m": "43,412"
    },
    {
        "rank": 367,
        "name_cn": "俄罗斯铁路公司",
        "name_en": "Russian Railways (RZD)",
        "founder_en": "Government of the Russian Federation",
        "founder_cn": "俄罗斯联邦政府 (原俄罗斯铁道部政企分开改制)",
        "country": "🇷🇺 俄罗斯",
        "hq": "莫斯科",
        "founded_year": 2003,
        "industry": "全国干线铁路客运网与亚欧陆桥过境货运",
        "revenue_m": "43,386"
    },
    {
        "rank": 368,
        "name_cn": "西门子能源",
        "name_en": "Siemens Energy AG",
        "founder_en": "Siemens AG Energy Sector Spinoff",
        "founder_cn": "西门子股份公司分拆能源电力业务独立上市",
        "country": "🇩🇪 德国",
        "hq": "慕尼黑",
        "founded_year": 2020,
        "industry": "重型燃气轮机、高压直流输电(HVDC)与风电(歌美飒)",
        "revenue_m": "43,114"
    },
    {
        "rank": 369,
        "name_cn": "Mercadona公司",
        "name_en": "Mercadona S.A.",
        "founder_en": "Francisco Roig Ballester, Trinidad Alfonso Mocholí",
        "founder_cn": "弗朗西斯科·罗伊格·巴列斯特尔 夫妇",
        "country": "🇪🇸 西班牙",
        "hq": "塔韦内斯布兰克斯",
        "founded_year": 1977,
        "industry": "西班牙连锁生鲜超市与高品质自有品牌零售 (Hacendado)",
        "revenue_m": "43,062"
    },
    {
        "rank": 370,
        "name_cn": "葛兰素史克集团",
        "name_en": "GSK plc (GlaxoSmithKline)",
        "founder_en": "Glaxo Wellcome & SmithKline Beecham Merger",
        "founder_cn": "葛兰素威康与史克必成合并组建",
        "country": "🇬🇧 英国",
        "hq": "伦敦",
        "founded_year": 1715,
        "industry": "创新生物疫苗 (欣安立适)、呼吸系统特药与HIV治疗",
        "revenue_m": "43,026"
    },
    {
        "rank": 371,
        "name_cn": "现代摩比斯公司",
        "name_en": "Hyundai Mobis Co., Ltd.",
        "founder_en": "Chung Ju-yung (Hyundai Precision)",
        "founder_cn": "郑周永 (现代精工演变)",
        "country": "🇰🇷 韩国",
        "hq": "首尔",
        "founded_year": 1977,
        "industry": "汽车底盘模块、智能线控转向与纯电驱动系统",
        "revenue_m": "42,994"
    },
    {
        "rank": 372,
        "name_cn": "顺丰控股股份有限公司",
        "name_en": "SF Holding Co., Ltd.",
        "founder_en": "Wang Wei",
        "founder_cn": "王卫",
        "country": "🇨🇳 中国",
        "hq": "广东 深圳",
        "founded_year": 1993,
        "industry": "综合快递物流、全货机机队与鄂州航空货运枢纽",
        "revenue_m": "42,883"
    },
    {
        "rank": 373,
        "name_cn": "美国合众银行",
        "name_en": "U.S. Bancorp",
        "founder_en": "United States National Bank of Portland & First Bank Merger",
        "founder_cn": "波特兰合众国国家银行与第一银行合并",
        "country": "🇺🇸 美国",
        "hq": "明尼苏达州 明尼阿波利斯",
        "founded_year": 1863,
        "industry": "全国大型商业银行、零售信用卡与商户支付服务",
        "revenue_m": "42,861"
    },
    {
        "rank": 374,
        "name_cn": "Dollar General公司",
        "name_en": "Dollar General Corporation",
        "founder_en": "J.L. Turner, Cal Turner",
        "founder_cn": "J.L. 特纳、卡尔·特纳",
        "country": "🇺🇸 美国",
        "hq": "田纳西州 古德利茨维尔",
        "founded_year": 1939,
        "industry": "社区平价小包装折扣杂货与日用品连锁",
        "revenue_m": "42,724"
    },
    {
        "rank": 375,
        "name_cn": "Coop集团",
        "name_en": "Coop Group (Switzerland)",
        "founder_en": "Verband Schweizerischer Konsumvereine (VSK)",
        "founder_cn": "瑞士消费合作社联合会创立",
        "country": "🇨🇭 瑞士",
        "hq": "巴塞尔",
        "founded_year": 1890,
        "industry": "瑞士连锁食品超市、有机生鲜与批发商业",
        "revenue_m": "42,696"
    },
    {
        "rank": 376,
        "name_cn": "西班牙电话公司",
        "name_en": "Telefónica, S.A.",
        "founder_en": "Compañía Telefónica Nacional de España Charter",
        "founder_cn": "西班牙国家电话公司特许设立",
        "country": "🇪🇸 西班牙",
        "hq": "马德里",
        "founded_year": 1924,
        "industry": "跨国综合电信运营 (Movistar/O2) 与光纤网络",
        "revenue_m": "42,540"
    },
    {
        "rank": 377,
        "name_cn": "中国机械工业集团有限公司",
        "name_en": "China National Machinery Industry Corp. (Sinomach)",
        "founder_en": "Ministry of Machine-Building Industry of China",
        "founder_cn": "第一机械工业部改制演变设立",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1997,
        "industry": "现代农业装备、重型装备研发制造与海外工程承包",
        "revenue_m": "42,444"
    },
    {
        "rank": 378,
        "name_cn": "海尔智家股份有限公司",
        "name_en": "Haier Smart Home Co., Ltd.",
        "founder_en": "Zhang Ruimin",
        "founder_cn": "张瑞敏 (青岛电冰箱总厂演变)",
        "country": "🇨🇳 中国",
        "hq": "山东 青岛",
        "founded_year": 1984,
        "industry": "全球高端智慧家电 (卡萨帝/GEA) 与全屋智能",
        "revenue_m": "42,065"
    },
    {
        "rank": 379,
        "name_cn": "麦格纳国际",
        "name_en": "Magna International Inc.",
        "founder_en": "Frank Stronach (Multimatic Investments)",
        "founder_cn": "法兰克·斯特罗纳克",
        "country": "🇨🇦 加拿大",
        "hq": "奥罗拉",
        "founded_year": 1957,
        "industry": "汽车车身底盘系统、动力总成与整车代工制造 (斯太尔)",
        "revenue_m": "42,010"
    },
    {
        "rank": 380,
        "name_cn": "东京电力公司",
        "name_en": "Tokyo Electric Power Company Holdings (TEPCO)",
        "founder_en": "Government of Japan (Postwar Electric Reorganization)",
        "founder_cn": "日本政府 (战后电力重组法令设立)",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1951,
        "industry": "首都圈电力公用事业输配电与可再生发电",
        "revenue_m": "41,991"
    },
    {
        "rank": 381,
        "name_cn": "美国诺斯洛普格拉曼公司",
        "name_en": "Northrop Grumman Corporation",
        "founder_en": "Jack Northrop, Leroy Grumman",
        "founder_cn": "杰克·诺斯洛普、勒罗伊·格鲁曼",
        "country": "🇺🇸 美国",
        "hq": "弗吉尼亚州 福尔斯彻奇",
        "founded_year": 1939,
        "industry": "B-21隐身战略轰炸机、雷达电子战与空间防务系统",
        "revenue_m": "41,954"
    },
    {
        "rank": 382,
        "name_cn": "Magnit公司",
        "name_en": "Magnit PJSC",
        "founder_en": "Sergey Galitsky",
        "founder_cn": "谢尔盖·加利茨基",
        "country": "🇷🇺 俄罗斯",
        "hq": "克拉斯诺达尔",
        "founded_year": 1994,
        "industry": "社区连锁便利超市与综合食品折扣大卖场",
        "revenue_m": "41,851"
    },
    {
        "rank": 383,
        "name_cn": "奇瑞汽车股份有限公司",
        "name_en": "Chery Automobile Co., Ltd.",
        "founder_en": "Yin Tongyue & Wuhu Municipal Government",
        "founder_cn": "尹同跃及芜湖市政府创业团队",
        "country": "🇨🇳 中国",
        "hq": "安徽 芜湖",
        "founded_year": 1997,
        "industry": "乘用车自主整车研发制造与中国汽车海外出口领军",
        "revenue_m": "41,778"
    },
    {
        "rank": 384,
        "name_cn": "铃木汽车",
        "name_en": "Suzuki Motor Corporation",
        "founder_en": "Michio Suzuki",
        "founder_cn": "铃木道雄",
        "country": "🇯🇵 日本",
        "hq": "静冈县 滨松市",
        "founded_year": 1909,
        "industry": "轻型小型汽车、摩托车制造与印度玛鲁蒂铃木",
        "revenue_m": "41,755"
    },
    {
        "rank": 385,
        "name_cn": "百思买",
        "name_en": "Best Buy Co., Inc.",
        "founder_en": "Richard M. Schulze, Gary Smoliak (Sound of Music)",
        "founder_cn": "理查德·M·舒尔茨、加里·斯莫利亚克",
        "country": "🇺🇸 美国",
        "hq": "明尼苏达州 里奇菲尔德",
        "founded_year": 1966,
        "industry": "消费电子、家用电器与 Geek Squad 技术服务连锁",
        "revenue_m": "41,691"
    },
    {
        "rank": 386,
        "name_cn": "赛富时",
        "name_en": "Salesforce, Inc.",
        "founder_en": "Marc Benioff, Parker Harris, Dave Moellenhoff, Frank Dominguez",
        "founder_cn": "马克·贝尼奥夫、帕克·哈里斯 等",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 旧金山",
        "founded_year": 1999,
        "industry": "企业级CRM云平台、Data Cloud与Agentforce自主AI智能体",
        "revenue_m": "41,525"
    },
    {
        "rank": 387,
        "name_cn": "SAP公司",
        "name_en": "SAP SE",
        "founder_en": "Dietmar Hopp, Hasso Plattner, Klaus Tschira, Hans-Werner Hector, Claus Wellenreuther",
        "founder_cn": "迪特马尔·霍普、哈索·普拉特纳等5位前IBM工程师",
        "country": "🇩🇪 德国",
        "hq": "瓦尔多夫",
        "founded_year": 1972,
        "industry": "企业级ERP资源规划软件、S/4HANA与供应链协同",
        "revenue_m": "41,507"
    },
    {
        "rank": 388,
        "name_cn": "KB金融集团",
        "name_en": "KB Financial Group Inc.",
        "founder_en": "Kookmin Bank & Housing and Commercial Bank Merger",
        "founder_cn": "韩国国民银行与住宅银行合并重组",
        "country": "🇰🇷 韩国",
        "hq": "首尔",
        "founded_year": 1963,
        "industry": "综合商业银行、信用卡与个人零售理财",
        "revenue_m": "41,284"
    },
    {
        "rank": 389,
        "name_cn": "广州工业投资控股集团有限公司",
        "name_en": "Guangzhou Industrial Investment Holding Group (Guangzhou Industrial)",
        "founder_en": "Guangzhou Municipal People's Government",
        "founder_cn": "广州市人民政府 (广钢/万宝/万力等企业重组设立)",
        "country": "🇨🇳 中国",
        "hq": "广东 广州",
        "founded_year": 2019,
        "industry": "先进智能装备、工业零部件制造与新材料产业",
        "revenue_m": "41,181"
    },
    {
        "rank": 390,
        "name_cn": "晋能控股集团有限公司",
        "name_en": "Jinneng Holding Group Co., Ltd.",
        "founder_en": "Shanxi Provincial People's Government",
        "founder_cn": "山西省人民政府 (同煤/晋煤/晋能三家大型国企联合重组)",
        "country": "🇨🇳 中国",
        "hq": "山西 大同 / 太原",
        "founded_year": 2020,
        "industry": "动力煤炭采掘、坑口火电发电与智慧绿色能源",
        "revenue_m": "41,131"
    },
    {
        "rank": 391,
        "name_cn": "山东高速集团有限公司",
        "name_en": "Shandong Hi-Speed Group Co., Ltd.",
        "founder_en": "Shandong Provincial People's Government",
        "founder_cn": "山东省人民政府 (省交通厅骨干资产整合设立)",
        "country": "🇨🇳 中国",
        "hq": "山东 济南",
        "founded_year": 2001,
        "industry": "高速公路路网投资运营与基础设施全产业链",
        "revenue_m": "40,985"
    },
    {
        "rank": 392,
        "name_cn": "中国建材集团有限公司",
        "name_en": "China National Building Material Group Co., Ltd. (CNBM)",
        "founder_en": "State Council of China (State Building Materials Bureau)",
        "founder_cn": "国务院 (国家建材局骨干企业重组合并设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1984,
        "industry": "水泥熟料、玻璃纤维、高性能碳纤维与特种玻纤",
        "revenue_m": "40,976"
    },
    {
        "rank": 393,
        "name_cn": "陕西延长石油（集团）有限责任公司",
        "name_en": "Shaanxi Yanchang Petroleum (Group) Co., Ltd.",
        "founder_en": "Qing Dynasty Yanchang Petroleum Bureau (Yanyi Well)",
        "founder_cn": "清政府延长石油官矿局 (中国陆上第一口油井)",
        "country": "🇨🇳 中国",
        "hq": "陕西 西安 / 延安",
        "founded_year": 1905,
        "industry": "低渗油气田勘探、煤油气综合化工与新能源",
        "revenue_m": "40,812"
    },
    {
        "rank": 394,
        "name_cn": "纽约梅隆银行",
        "name_en": "The Bank of New York Mellon Corporation (BNY)",
        "founder_en": "Alexander Hamilton (Bank of New York 1784) & T. Mellon",
        "founder_cn": "亚历山大·汉密尔顿 (纽约银行) 与托马斯·梅隆",
        "country": "🇺🇸 美国",
        "hq": "纽约州 纽约",
        "founded_year": 1784,
        "industry": "全球大型资产托管银行、证券服务与财富管理",
        "revenue_m": "40,762"
    },
    {
        "rank": 395,
        "name_cn": "霍尼韦尔国际公司",
        "name_en": "Honeywell International Inc.",
        "founder_en": "Albert Butz, Mark Honeywell (AlliedSignal Merger)",
        "founder_cn": "阿尔伯特·布茨、马克·霍尼韦尔 (联信合并)",
        "country": "🇺🇸 美国",
        "hq": "北卡罗来纳州 夏洛特",
        "founded_year": 1885,
        "industry": "航空航天机载设备、智能楼宇自控与工业高性能材料",
        "revenue_m": "40,686"
    },
    {
        "rank": 396,
        "name_cn": "菲利普－莫里斯国际公司",
        "name_en": "Philip Morris International Inc. (PMI)",
        "founder_en": "Philip Morris",
        "founder_cn": "菲利普·莫里斯",
        "country": "🇺🇸 美国",
        "hq": "康涅狄格州 斯坦福",
        "founded_year": 1847,
        "industry": "传统烟草与无烟加热不燃烧减害产品 (IQOS/ZYN)",
        "revenue_m": "40,648"
    },
    {
        "rank": 397,
        "name_cn": "渣打银行",
        "name_en": "Standard Chartered PLC",
        "founder_en": "James Wilson (Standard Bank & Chartered Bank Merger)",
        "founder_cn": "詹姆斯·威尔逊 (标准银行与麦加利银行合并)",
        "country": "🇬🇧 英国",
        "hq": "伦敦",
        "founded_year": 1853,
        "industry": "亚洲、非洲与中东跨国商业银行与国际贸易融资",
        "revenue_m": "40,634"
    },
    {
        "rank": 398,
        "name_cn": "Jerónimo Martins公司",
        "name_en": "Jerónimo Martins, SGPS, S.A.",
        "founder_en": "Jerónimo Martins",
        "founder_cn": "热罗尼莫·马丁斯",
        "country": "🇵🇹 葡萄牙",
        "hq": "里斯本",
        "founded_year": 1792,
        "industry": "葡萄牙与波兰 (Biedronka) 折扣食品生鲜超市连锁",
        "revenue_m": "40,595"
    },
    {
        "rank": 399,
        "name_cn": "塔塔汽车乘用车公司",
        "name_en": "Tata Motors Limited",
        "founder_en": "J. R. D. Tata",
        "founder_cn": "J.R.D. 塔塔",
        "country": "🇮🇳 印度",
        "hq": "孟买",
        "founded_year": 1945,
        "industry": "乘用车与豪华全地形越野车 (捷豹路虎 JLR)",
        "revenue_m": "40,562"
    },
    {
        "rank": 400,
        "name_cn": "世邦魏理仕集团",
        "name_en": "CBRE Group, Inc.",
        "founder_en": "Colbert Coldwell (Tucker, Lynch & Coldwell)",
        "founder_cn": "科尔伯特·科德韦尔",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 达拉斯",
        "founded_year": 1906,
        "industry": "全球商业地产代理经纪、物业估值与设施资产管理",
        "revenue_m": "40,550"
    }
]
