# -*- coding: utf-8 -*-
"""Data part 2: Companies 101 to 200"""

DATA_PART2 = [
    {
        "rank": 101,
        "name_cn": "REWE集团",
        "name_en": "REWE Group",
        "founder_en": "Revisionsverband der Westkauf-Genossenschaften",
        "founder_cn": "西部采购合作社联合会",
        "country": "🇩🇪 德国",
        "hq": "科隆",
        "founded_year": 1927,
        "industry": "食品连锁超市与旅游度假",
        "revenue_m": "102,755"
    },
    {
        "rank": 102,
        "name_cn": "博世集团",
        "name_en": "Robert Bosch GmbH",
        "founder_en": "Robert Bosch",
        "founder_cn": "罗伯特·博世",
        "country": "🇩🇪 德国",
        "hq": "斯图加特",
        "founded_year": 1886,
        "industry": "汽车零部件、工业自动化与智能家居",
        "revenue_m": "102,605"
    },
    {
        "rank": 103,
        "name_cn": "法国兴业银行",
        "name_en": "Société Générale S.A.",
        "founder_en": "Decree of Napoleon III & Group of Industrialists",
        "founder_cn": "拿破仑三世法令特许与法国实业家联合",
        "country": "🇫🇷 法国",
        "hq": "巴黎",
        "founded_year": 1864,
        "industry": "商业银行、全球市场与证券投资",
        "revenue_m": "102,423"
    },
    {
        "rank": 104,
        "name_cn": "中国电力建设集团有限公司",
        "name_en": "Power Construction Corporation of China (PowerChina)",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (水利电力建设系统重组设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 2011,
        "industry": "水利水电建设与清洁可再生能源工程",
        "revenue_m": "101,854"
    },
    {
        "rank": 105,
        "name_cn": "乐购",
        "name_en": "Tesco PLC",
        "founder_en": "Jack Cohen",
        "founder_cn": "杰克·科恩",
        "country": "🇬🇧 英国",
        "hq": "韦林花园市",
        "founded_year": 1919,
        "industry": "生鲜超市大卖场与全渠道零售",
        "revenue_m": "98,502"
    },
    {
        "rank": 106,
        "name_cn": "家乐福",
        "name_en": "Carrefour S.A.",
        "founder_en": "Marcel Fournier, Denis Defforey, Jacques Defforey",
        "founder_cn": "马塞尔·富尼耶、德尼·德福雷、雅克·德福雷",
        "country": "🇫🇷 法国",
        "hq": "马西",
        "founded_year": 1959,
        "industry": "大型综合超市连锁与跨国零售",
        "revenue_m": "98,381"
    },
    {
        "rank": 107,
        "name_cn": "日本伊藤忠商事株式会社",
        "name_en": "Itochu Corporation",
        "founder_en": "Chubei Itoh",
        "founder_cn": "伊藤忠兵卫",
        "country": "🇯🇵 日本",
        "hq": "东京 / 大阪",
        "founded_year": 1858,
        "industry": "综合商社 (纺织/机械/金属/能源/消费)",
        "revenue_m": "98,354"
    },
    {
        "rank": 108,
        "name_cn": "国家能源投资集团有限责任公司",
        "name_en": "China Energy Investment Corporation (CHN Energy)",
        "founder_en": "State Council of China (Shenhua & Guodian Merger)",
        "founder_cn": "国务院 (神华集团与国电集团联合重组)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 2017,
        "industry": "煤炭开采、火电与风力光伏发电",
        "revenue_m": "98,344"
    },
    {
        "rank": 109,
        "name_cn": "俄罗斯石油公司",
        "name_en": "Rosneft Oil Company",
        "founder_en": "Government of the Russian Federation",
        "founder_cn": "俄罗斯联邦政府 (原苏联石油工业部改制)",
        "country": "🇷🇺 俄罗斯",
        "hq": "莫斯科",
        "founded_year": 1993,
        "industry": "石油勘探、原油开采与国际出口",
        "revenue_m": "98,223"
    },
    {
        "rank": 110,
        "name_cn": "加拿大皇家银行",
        "name_en": "Royal Bank of Canada (RBC)",
        "founder_en": "John William Ritchie & Halifax Merchants",
        "founder_cn": "约翰·威廉·里奇与哈利法克斯商人集团",
        "country": "🇨🇦 加拿大",
        "hq": "多伦多 / 蒙特利尔",
        "founded_year": 1864,
        "industry": "商业银行、财富管理与全球资本市场",
        "revenue_m": "98,128"
    },
    {
        "rank": 111,
        "name_cn": "日本生命保险公司",
        "name_en": "Nippon Life Insurance Company",
        "founder_en": "Torajiro Sukegawa & Yuhoki Hirose",
        "founder_cn": "助川寅次郎、广濑祐记",
        "country": "🇯🇵 日本",
        "hq": "大阪",
        "founded_year": 1889,
        "industry": "相互人寿保险与资产管理",
        "revenue_m": "98,034"
    },
    {
        "rank": 112,
        "name_cn": "厦门建发集团有限公司",
        "name_en": "Xiamen C&D Group Co., Ltd.",
        "founder_en": "Xiamen Municipal People's Government",
        "founder_cn": "厦门市人民政府 (特区建设发轫设立)",
        "country": "🇨🇳 中国",
        "hq": "福建 厦门",
        "founded_year": 1980,
        "industry": "大宗商品供应链运营与城市综合开发",
        "revenue_m": "97,028"
    },
    {
        "rank": 113,
        "name_cn": "三菱日联金融集团",
        "name_en": "Mitsubishi UFJ Financial Group, Inc. (MUFG)",
        "founder_en": "Mitsubishi Tokyo & UFJ Merger",
        "founder_cn": "三菱东京金融集团与UFJ控股合并",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 2005,
        "industry": "跨国商业银行、信托与资产管理",
        "revenue_m": "97,012"
    },
    {
        "rank": 114,
        "name_cn": "日本电报电话公司",
        "name_en": "Nippon Telegraph and Telephone Corporation (NTT)",
        "founder_en": "Government of Japan (Privatization Act)",
        "founder_cn": "日本政府 (日本电信电话公社民营化)",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1952,
        "industry": "综合电信网络运营与企业级IT方案",
        "revenue_m": "95,608"
    },
    {
        "rank": 115,
        "name_cn": "浙江荣盛控股集团有限公司",
        "name_en": "Zhejiang Rongsheng Holding Group Co., Ltd.",
        "founder_en": "Li Shuirong",
        "founder_cn": "李水荣",
        "country": "🇨🇳 中国",
        "hq": "浙江 杭州",
        "founded_year": 1989,
        "industry": "特大型炼油化工、PTA与芳烃聚酯",
        "revenue_m": "94,831"
    },
    {
        "rank": 116,
        "name_cn": "特斯拉",
        "name_en": "Tesla, Inc.",
        "founder_en": "Martin Eberhard, Marc Tarpenning / Elon Musk",
        "founder_cn": "马丁·艾伯哈德、马克·塔彭宁 / 埃隆·马斯克 (联合创立/早期投资人)",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 奥斯汀",
        "founded_year": 2003,
        "industry": "电动汽车、全自动驾驶(FSD)与储能系统",
        "revenue_m": "94,827"
    },
    {
        "rank": 117,
        "name_cn": "华特迪士尼公司",
        "name_en": "The Walt Disney Company",
        "founder_en": "Walt Disney, Roy O. Disney",
        "founder_cn": "华特·迪士尼、罗伊·O·迪士尼",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 伯班克",
        "founded_year": 1923,
        "industry": "电影动画制作、流媒体(Disney+)与主题公园",
        "revenue_m": "94,425"
    },
    {
        "rank": 118,
        "name_cn": "埃尼石油公司",
        "name_en": "Eni S.p.A.",
        "founder_en": "Enrico Mattei (Italian Government Act)",
        "founder_cn": "恩里科·马泰伊 (意大利政府立法设立)",
        "country": "🇮🇹 意大利",
        "hq": "罗马",
        "founded_year": 1953,
        "industry": "石油天然气勘探开发与生物炼化",
        "revenue_m": "94,326"
    },
    {
        "rank": 119,
        "name_cn": "中国邮政集团有限公司",
        "name_en": "China Post Group Co., Ltd.",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (国家邮政局政企分开改制设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 2007,
        "industry": "邮政普遍服务、快递物流与邮储银行金融",
        "revenue_m": "94,215"
    },
    {
        "rank": 120,
        "name_cn": "强生",
        "name_en": "Johnson & Johnson",
        "founder_en": "Robert Wood Johnson, James Wood Johnson, Edward Mead Johnson",
        "founder_cn": "罗伯特·伍德·约翰逊、詹姆斯·约翰逊、爱德华·约翰逊",
        "country": "🇺🇸 美国",
        "hq": "新泽西州 新布朗斯维克",
        "founded_year": 1886,
        "industry": "创新制药与医疗科技手术器械",
        "revenue_m": "94,193"
    },
    {
        "rank": 121,
        "name_cn": "百事公司",
        "name_en": "PepsiCo, Inc.",
        "founder_en": "Caleb Bradham (Pepsi-Cola) & Herman Lay (Frito-Lay)",
        "founder_cn": "凯莱布·布拉德汉姆、赫尔曼·莱",
        "country": "🇺🇸 美国",
        "hq": "纽约州 珀切斯",
        "founded_year": 1898,
        "industry": "软饮料、燕麦与休闲食品零食",
        "revenue_m": "93,925"
    },
    {
        "rank": 122,
        "name_cn": "敦豪集团",
        "name_en": "DHL Group (Deutsche Post AG)",
        "founder_en": "Adrian Dalsey, Larry Hillblom, Robert Lynn (DHL founders)",
        "founder_cn": "阿德里安·达尔西、拉里·希尔布洛姆、罗伯特·林恩",
        "country": "🇩🇪 德国",
        "hq": "波恩",
        "founded_year": 1969,
        "industry": "国际航空快递、货运代理与供应链管理",
        "revenue_m": "93,453"
    },
    {
        "rank": 123,
        "name_cn": "中国人民保险集团股份有限公司",
        "name_en": "The People's Insurance Company (Group) of China (PICC)",
        "founder_en": "Central People's Government of China",
        "founder_cn": "中央人民政府 (中国人民保险公司)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1949,
        "industry": "财产保险、人身保险与健康险综合运营",
        "revenue_m": "93,111"
    },
    {
        "rank": 124,
        "name_cn": "三井物产株式会社",
        "name_en": "Mitsui & Co., Ltd.",
        "founder_en": "Takashi Masuda",
        "founder_cn": "益田孝 (三井家族基业)",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1876,
        "industry": "综合商社 (金属资源/能源/机械/化学品)",
        "revenue_m": "92,861"
    },
    {
        "rank": 125,
        "name_cn": "上海汽车集团股份有限公司",
        "name_en": "SAIC Motor Corporation Limited",
        "founder_en": "Shanghai Municipal People's Government",
        "founder_cn": "上海市人民政府 (上海汽车制造总厂演变)",
        "country": "🇨🇳 中国",
        "hq": "上海",
        "founded_year": 1955,
        "industry": "汽车整车制造、零部件与智驾出行",
        "revenue_m": "91,301"
    },
    {
        "rank": 126,
        "name_cn": "迪奥公司",
        "name_en": "Christian Dior SE",
        "founder_en": "Christian Dior, Marcel Boussac",
        "founder_cn": "克里斯汀·迪奥、马塞尔·布萨克",
        "country": "🇫🇷 法国",
        "hq": "巴黎",
        "founded_year": 1946,
        "industry": "高级时装、香水美妆与奢侈品控股 (LVMH)",
        "revenue_m": "91,143"
    },
    {
        "rank": 127,
        "name_cn": "意大利国家电力公司",
        "name_en": "Enel S.p.A.",
        "founder_en": "Italian Government (Enel Act)",
        "founder_cn": "意大利政府 (电力国家化法令设立)",
        "country": "🇮🇹 意大利",
        "hq": "罗马",
        "founded_year": 1962,
        "industry": "电力发电输配与全球可再生能源",
        "revenue_m": "90,624"
    },
    {
        "rank": 128,
        "name_cn": "波音",
        "name_en": "The Boeing Company",
        "founder_en": "William Boeing",
        "founder_cn": "威廉·波音",
        "country": "🇺🇸 美国",
        "hq": "弗吉尼亚州 阿灵顿",
        "founded_year": 1916,
        "industry": "民用航空客机与国防军工航天系统",
        "revenue_m": "89,463"
    },
    {
        "rank": 129,
        "name_cn": "中国医药集团有限公司",
        "name_en": "China National Pharmaceutical Group (Sinopharm)",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (中国医药公司等央企重组设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1998,
        "industry": "生物医药研发制造与全国分销零售网络",
        "revenue_m": "89,352"
    },
    {
        "rank": 130,
        "name_cn": "印度石油公司",
        "name_en": "Indian Oil Corporation Limited (IOCL)",
        "founder_en": "Government of India",
        "founder_cn": "印度中央政府",
        "country": "🇮🇳 印度",
        "hq": "新德里",
        "founded_year": 1959,
        "industry": "原油炼化、管道运输与加油终端",
        "revenue_m": "89,249"
    },
    {
        "rank": 131,
        "name_cn": "巴西国家石油公司",
        "name_en": "Petróleo Brasileiro S.A. (Petrobras)",
        "founder_en": "Getúlio Vargas (President of Brazil)",
        "founder_cn": "热图利奥·瓦加斯总统法令设立",
        "country": "🇧🇷 巴西",
        "hq": "里约热内卢",
        "founded_year": 1953,
        "industry": "深海超深水盐下油气开采与炼油",
        "revenue_m": "89,195"
    },
    {
        "rank": 132,
        "name_cn": "意昂集团",
        "name_en": "E.ON SE",
        "founder_en": "VEBA & VIAG Merger",
        "founder_cn": "德国联合电力与联合工业合并",
        "country": "🇩🇪 德国",
        "hq": "埃森",
        "founded_year": 2000,
        "industry": "欧洲能源输配网络与智慧能源解决方案",
        "revenue_m": "88,771"
    },
    {
        "rank": 133,
        "name_cn": "联合包裹速递服务公司",
        "name_en": "United Parcel Service, Inc. (UPS)",
        "founder_en": "James E. Casey, Claude Ryan",
        "founder_cn": "詹姆斯·E·凯西、克劳德·赖安",
        "country": "🇺🇸 美国",
        "hq": "佐治亚州 亚特兰大",
        "founded_year": 1907,
        "industry": "全球快递包裹与一体化供应链物流",
        "revenue_m": "88,661"
    },
    {
        "rank": 134,
        "name_cn": "中国电信集团有限公司",
        "name_en": "China Telecommunications Corporation",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (原中国电信拆分重组设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 2000,
        "industry": "宽带互联网、5G移动通信与天翼云科技",
        "revenue_m": "88,631"
    },
    {
        "rank": 135,
        "name_cn": "雷神技术公司",
        "name_en": "RTX Corporation (Raytheon Technologies)",
        "founder_en": "Laurence K. Marshall, Vannevar Bush, Charles G. Smith",
        "founder_cn": "劳伦斯·马歇尔、万尼瓦尔·布什、查尔斯·史密斯",
        "country": "🇺🇸 美国",
        "hq": "弗吉尼亚州 阿灵顿",
        "founded_year": 1922,
        "industry": "航空航天发动机 (普惠)、柯林斯机载与防务电子",
        "revenue_m": "88,603"
    },
    {
        "rank": 136,
        "name_cn": "Rajesh Exports公司",
        "name_en": "Rajesh Exports Limited",
        "founder_en": "Rajesh Mehta, Prashant Mehta",
        "founder_cn": "拉杰什·梅塔、普拉尚特·梅塔",
        "country": "🇮🇳 印度",
        "hq": "班加罗尔",
        "founded_year": 1989,
        "industry": "黄金精炼、珠宝设计制造与贵金属出口",
        "revenue_m": "88,164"
    },
    {
        "rank": 137,
        "name_cn": "联邦快递",
        "name_en": "FedEx Corporation",
        "founder_en": "Frederick W. Smith",
        "founder_cn": "弗雷德里克·W·史密斯",
        "country": "🇺🇸 美国",
        "hq": "田纳西州 孟菲斯",
        "founded_year": 1971,
        "industry": "隔夜航空货运快递与陆运物流",
        "revenue_m": "87,926"
    },
    {
        "rank": 138,
        "name_cn": "浙江吉利控股集团有限公司",
        "name_en": "Zhejiang Geely Holding Group Co., Ltd.",
        "founder_en": "Li Shufu",
        "founder_cn": "李书福",
        "country": "🇨🇳 中国",
        "hq": "浙江 杭州",
        "founded_year": 1986,
        "industry": "乘用车制造、极氪智能电车与低轨卫星互联",
        "revenue_m": "87,866"
    },
    {
        "rank": 139,
        "name_cn": "前进保险公司",
        "name_en": "The Progressive Corporation",
        "founder_en": "Joseph Green, Jack Green",
        "founder_cn": "约瑟夫·格林、杰克·格林",
        "country": "🇺🇸 美国",
        "hq": "俄亥俄州 梅菲尔德村",
        "founded_year": 1937,
        "industry": "汽车车险、商业车辆保险与直销经纪",
        "revenue_m": "87,671"
    },
    {
        "rank": 140,
        "name_cn": "多伦多道明银行",
        "name_en": "The Toronto-Dominion Bank (TD Bank Group)",
        "founder_en": "Bank of Toronto & The Dominion Bank Merger",
        "founder_cn": "多伦多银行与自治领银行合并",
        "country": "🇨🇦 加拿大",
        "hq": "多伦多",
        "founded_year": 1955,
        "industry": "零售商业银行、财富管理与跨境金融",
        "revenue_m": "87,350"
    },
    {
        "rank": 141,
        "name_cn": "索尼",
        "name_en": "Sony Group Corporation",
        "founder_en": "Masaru Ibuka, Akio Morita",
        "founder_cn": "井深大、盛田昭夫",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1946,
        "industry": "游戏(PlayStation)、影视音乐与图像CMOS传感器",
        "revenue_m": "87,304"
    },
    {
        "rank": 142,
        "name_cn": "SK集团",
        "name_en": "SK Group",
        "founder_en": "Chey Jong-gun",
        "founder_cn": "崔钟建",
        "country": "🇰🇷 韩国",
        "hq": "首尔",
        "founded_year": 1953,
        "industry": "半导体(HBM存储)、能源化工与电信运营",
        "revenue_m": "87,238"
    },
    {
        "rank": 143,
        "name_cn": "西门子",
        "name_en": "Siemens AG",
        "founder_en": "Werner von Siemens, Johann Georg Halske",
        "founder_cn": "维尔纳·冯·西门子、约翰·格奥尔格·哈尔斯克",
        "country": "🇩🇪 德国",
        "hq": "慕尼黑 / 柏林",
        "founded_year": 1847,
        "industry": "工业自动化、智能楼宇基建与数字工业软件",
        "revenue_m": "87,066"
    },
    {
        "rank": 144,
        "name_cn": "西班牙对外银行",
        "name_en": "Banco Bilbao Vizcaya Argentaria, S.A. (BBVA)",
        "founder_en": "Banco de Bilbao, Banco de Vizcaya & Argentaria",
        "founder_cn": "毕尔巴鄂银行、比斯开银行与阿根廷联合银行合并",
        "country": "🇪🇸 西班牙",
        "hq": "毕尔巴鄂 / 马德里",
        "founded_year": 1857,
        "industry": "跨国商业银行、零售金融与拉美金融服务",
        "revenue_m": "87,005"
    },
    {
        "rank": 145,
        "name_cn": "美国劳氏公司",
        "name_en": "Lowe's Companies, Inc.",
        "founder_en": "Lucius Smith Lowe",
        "founder_cn": "卢修斯·史密斯·劳",
        "country": "🇺🇸 美国",
        "hq": "北卡罗来纳州 穆尔斯维尔",
        "founded_year": 1921,
        "industry": "家居装修与家装五金连锁大卖场",
        "revenue_m": "86,286"
    },
    {
        "rank": 146,
        "name_cn": "巴西JBS公司",
        "name_en": "JBS S.A.",
        "founder_en": "José Batista Sobrinho",
        "founder_cn": "若泽·巴蒂斯塔·索布里尼奥",
        "country": "🇧🇷 巴西",
        "hq": "圣保罗",
        "founded_year": 1953,
        "industry": "全球大型肉类蛋白加工 (牛肉/禽肉/猪肉)",
        "revenue_m": "86,184"
    },
    {
        "rank": 147,
        "name_cn": "Energy Transfer公司",
        "name_en": "Energy Transfer LP",
        "founder_en": "Kelcy Warren, Ray Davis",
        "founder_cn": "凯尔西·沃伦、雷·戴维斯",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 达拉斯",
        "founded_year": 1996,
        "industry": "天然气与原油中游长输管网及仓储",
        "revenue_m": "85,536"
    },
    {
        "rank": 148,
        "name_cn": "英国劳埃德银行集团",
        "name_en": "Lloyds Banking Group plc",
        "founder_en": "John Taylor, Sampson Lloyd",
        "founder_cn": "约翰·泰勒、桑普森·劳埃德",
        "country": "🇬🇧 英国",
        "hq": "伦敦",
        "founded_year": 1765,
        "industry": "零售商业银行、商业借贷与住房抵押贷款",
        "revenue_m": "85,430"
    },
    {
        "rank": 149,
        "name_cn": "万喜集团",
        "name_en": "VINCI S.A.",
        "founder_en": "Alexandre Giros, Louis Loucheur",
        "founder_cn": "亚历山大·吉罗、路易·卢舍尔",
        "country": "🇫🇷 法国",
        "hq": "楠泰尔",
        "founded_year": 1899,
        "industry": "特许经营收费公路/机场与综合建筑工程",
        "revenue_m": "85,387"
    },
    {
        "rank": 150,
        "name_cn": "法国农业信贷银行",
        "name_en": "Crédit Agricole S.A.",
        "founder_en": "French Agricultural Credit Law Act",
        "founder_cn": "法国农业信贷法案设立",
        "country": "🇫🇷 法国",
        "hq": "蒙鲁日",
        "founded_year": 1894,
        "industry": "合作制商业银行、农贷与东方汇理资管 (Amundi)",
        "revenue_m": "84,368"
    },
    {
        "rank": 151,
        "name_cn": "宝洁公司",
        "name_en": "The Procter & Gamble Company (P&G)",
        "founder_en": "William Procter, James Gamble",
        "founder_cn": "威廉·普罗克特、詹姆斯·甘布尔",
        "country": "🇺🇸 美国",
        "hq": "俄亥俄州 辛辛那提",
        "founded_year": 1837,
        "industry": "日化日用快消品、个人洗护与织物护理",
        "revenue_m": "84,284"
    },
    {
        "rank": 152,
        "name_cn": "艾伯森公司",
        "name_en": "Albertsons Companies, Inc.",
        "founder_en": "Joe Albertson",
        "founder_cn": "乔·艾伯森",
        "country": "🇺🇸 美国",
        "hq": "爱达荷州 博伊西",
        "founded_year": 1939,
        "industry": "食品杂货与生鲜连锁超市",
        "revenue_m": "83,173"
    },
    {
        "rank": 153,
        "name_cn": "联想集团有限公司",
        "name_en": "Lenovo Group Limited",
        "founder_en": "Liu Chuanzhi & CAS Computing Institute",
        "founder_cn": "柳传志等中科院计算所科研人员",
        "country": "🇨🇳 中国",
        "hq": "北京 / 香港",
        "founded_year": 1984,
        "industry": "个人电脑、智能手机、AI服务器与基础设施方案",
        "revenue_m": "83,075"
    },
    {
        "rank": 154,
        "name_cn": "物产中大集团股份有限公司",
        "name_en": "Wuchan Zhongda Group Co., Ltd.",
        "founder_en": "Zhejiang Provincial People's Government",
        "founder_cn": "浙江省人民政府 (省物资局改制设立)",
        "country": "🇨🇳 中国",
        "hq": "浙江 杭州",
        "founded_year": 1954,
        "industry": "大宗商品供应链集成服务与高端实业",
        "revenue_m": "82,984"
    },
    {
        "rank": 155,
        "name_cn": "空中客车公司",
        "name_en": "Airbus SE",
        "founder_en": "Franco-German-British Intergovernmental Accord",
        "founder_cn": "法德英多国政府联合协定组建",
        "country": "🇫🇷 法国",
        "hq": "图卢兹",
        "founded_year": 1970,
        "industry": "民用航空客机 (A320/A350)、直升机与防务航天",
        "revenue_m": "82,812"
    },
    {
        "rank": 156,
        "name_cn": "山东魏桥创业集团有限公司",
        "name_en": "Shandong Weiqiao Pioneering Group Co., Ltd.",
        "founder_en": "Zhang Shiping",
        "founder_cn": "张士平",
        "country": "🇨🇳 中国",
        "hq": "山东 滨州",
        "founded_year": 1981,
        "industry": "电解铝深加工与高品质纺织服装",
        "revenue_m": "82,303"
    },
    {
        "rank": 157,
        "name_cn": "中粮集团有限公司",
        "name_en": "COFCO Corporation",
        "founder_en": "Ministry of Foreign Trade of China",
        "founder_cn": "中央人民政府贸易部 (华北油脂公司演变)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1949,
        "industry": "全产业链粮油食品加工与全球大宗农产品贸易",
        "revenue_m": "81,955"
    },
    {
        "rank": 158,
        "name_cn": "盛虹控股集团有限公司",
        "name_en": "Shenghong Holding Group Co., Ltd.",
        "founder_en": "Miao Hangen",
        "founder_cn": "缪汉根",
        "country": "🇨🇳 中国",
        "hq": "江苏 苏州",
        "founded_year": 1992,
        "industry": "炼化一体化、EVA光伏新能源材料与化纤聚酯",
        "revenue_m": "81,811"
    },
    {
        "rank": 159,
        "name_cn": "西斯科公司",
        "name_en": "Sysco Corporation",
        "founder_en": "John Baugh, Herbert Irving, Harry Rosenthal",
        "founder_cn": "约翰·鲍、赫伯特·欧文、哈里·罗森塔尔",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 休斯敦",
        "founded_year": 1969,
        "industry": "餐饮食材供应链与生鲜餐饮分销",
        "revenue_m": "81,370"
    },
    {
        "rank": 160,
        "name_cn": "Engie集团",
        "name_en": "Engie S.A. (GDF Suez)",
        "founder_en": "Suez & Gaz de France Merger",
        "founder_cn": "苏伊士集团与法国燃气合并",
        "country": "🇫🇷 法国",
        "hq": "库尔布瓦",
        "founded_year": 1858,
        "industry": "天然气公用事业、可再生电力与低碳能源",
        "revenue_m": "81,147"
    },
    {
        "rank": 161,
        "name_cn": "泰国国家石油有限公司",
        "name_en": "PTT Public Company Limited",
        "founder_en": "Government of Thailand (Petroleum Authority of Thailand)",
        "founder_cn": "泰国政府法令设立 (原泰国石油管理局)",
        "country": "🇹🇭 泰国",
        "hq": "曼谷",
        "founded_year": 1978,
        "industry": "石油天然气勘探、炼化与油气零售",
        "revenue_m": "81,039"
    },
    {
        "rank": 162,
        "name_cn": "印度国家银行",
        "name_en": "State Bank of India (SBI)",
        "founder_en": "Parliament of India (Bank of Calcutta 1806)",
        "founder_cn": "印度议会法案改制设立 (前身加尔各答银行)",
        "country": "🇮🇳 印度",
        "hq": "孟买",
        "founded_year": 1806,
        "industry": "大型国有商业银行、微型普惠金融与投资",
        "revenue_m": "80,655"
    },
    {
        "rank": 163,
        "name_cn": "美国邮政",
        "name_en": "United States Postal Service (USPS)",
        "founder_en": "Benjamin Franklin / Second Continental Congress",
        "founder_cn": "本杰明·富兰克林 / 第二届大陆会议设立",
        "country": "🇺🇸 美国",
        "hq": "华盛顿特区",
        "founded_year": 1775,
        "industry": "公共普遍邮政通信与包裹派送服务",
        "revenue_m": "80,581"
    },
    {
        "rank": 164,
        "name_cn": "江西铜业集团有限公司",
        "name_en": "Jiangxi Copper Corporation",
        "founder_en": "State Planning Commission of China",
        "founder_cn": "国家计划委员会与中国有色金属总公司设立",
        "country": "🇨🇳 中国",
        "hq": "江西 南昌 / 贵溪",
        "founded_year": 1979,
        "industry": "铜矿采选、高纯阴极铜冶炼与精深加工",
        "revenue_m": "80,488"
    },
    {
        "rank": 165,
        "name_cn": "美国运通公司",
        "name_en": "American Express Company",
        "founder_en": "Henry Wells, William G. Fargo, John Butterfield",
        "founder_cn": "亨利·韦尔斯、威廉·G·法戈、约翰·巴特菲尔德",
        "country": "🇺🇸 美国",
        "hq": "纽约州 纽约",
        "founded_year": 1850,
        "industry": "信用卡支付清算网络、商旅服务与高端金融",
        "revenue_m": "80,463"
    },
    {
        "rank": 166,
        "name_cn": "起亚公司",
        "name_en": "Kia Corporation",
        "founder_en": "Kim Chul-ho",
        "founder_cn": "金喆浩",
        "country": "🇰🇷 韩国",
        "hq": "首尔",
        "founded_year": 1944,
        "industry": "乘用车制造、纯电动汽车(EV)与出行方案",
        "revenue_m": "80,292"
    },
    {
        "rank": 167,
        "name_cn": "ADM公司",
        "name_en": "Archer-Daniels-Midland Company (ADM)",
        "founder_en": "George A. Archer, William S. Daniels",
        "founder_cn": "乔治·A·阿彻、威廉·S·丹尼尔斯",
        "country": "🇺🇸 美国",
        "hq": "伊利诺伊州 芝加哥",
        "founded_year": 1902,
        "industry": "粮油深加工、饲料配料与特种食品营养",
        "revenue_m": "80,269"
    },
    {
        "rank": 168,
        "name_cn": "日产汽车",
        "name_en": "Nissan Motor Co., Ltd.",
        "founder_en": "Yoshisuke Aikawa",
        "founder_cn": "鲇川义介",
        "country": "🇯🇵 日本",
        "hq": "神奈川县 横滨市",
        "founded_year": 1933,
        "industry": "汽车整车制造、e-POWER电驱与自动驾驶",
        "revenue_m": "79,675"
    },
    {
        "rank": 169,
        "name_cn": "墨西哥石油公司",
        "name_en": "Petróleos Mexicanos (Pemex)",
        "founder_en": "Lázaro Cárdenas (President of Mexico)",
        "founder_cn": "拉萨罗·卡德纳斯总统国有化法令设立",
        "country": "🇲🇽 墨西哥",
        "hq": "墨西哥城",
        "founded_year": 1938,
        "industry": "墨西哥油气勘探开采、炼油与分销",
        "revenue_m": "79,570"
    },
    {
        "rank": 170,
        "name_cn": "太平洋建设集团有限公司",
        "name_en": "Pacific Construction Group Co., Ltd.",
        "founder_en": "Yan Jiehe",
        "founder_cn": "严介和",
        "country": "🇨🇳 中国",
        "hq": "新疆 乌鲁木齐 / 江苏 南京",
        "founded_year": 1995,
        "industry": "城市道路、桥梁隧道与园区BT/PPP基础设施",
        "revenue_m": "79,293"
    },
    {
        "rank": 171,
        "name_cn": "法国BPCE银行集团",
        "name_en": "Groupe BPCE",
        "founder_en": "Banque Populaire & Caisse d'Epargne Merger",
        "founder_cn": "大众银行与储蓄银行合并组建",
        "country": "🇫🇷 法国",
        "hq": "巴黎",
        "founded_year": 2009,
        "industry": "合作制商业银行、零售金融与投资银行(Natixis)",
        "revenue_m": "78,937"
    },
    {
        "rank": 172,
        "name_cn": "瑞银集团",
        "name_en": "UBS Group AG",
        "founder_en": "Union Bank of Switzerland & SBC Merger",
        "founder_cn": "瑞士联合银行与瑞士银行公司合并组建",
        "country": "🇨🇭 瑞士",
        "hq": "苏黎世",
        "founded_year": 1862,
        "industry": "全球顶尖超高净值财富管理与投资银行",
        "revenue_m": "78,786"
    },
    {
        "rank": 173,
        "name_cn": "美国大都会集团",
        "name_en": "MetLife, Inc.",
        "founder_en": "Simeon Draper, James R. Dow (National Union Life)",
        "founder_cn": "西蒙·德雷珀、詹姆斯·R·道",
        "country": "🇺🇸 美国",
        "hq": "纽约州 纽约",
        "founded_year": 1868,
        "industry": "人寿保险、年金、雇员福利与资产管理",
        "revenue_m": "77,084"
    },
    {
        "rank": 174,
        "name_cn": "伊塔乌联合银行控股公司",
        "name_en": "Itaú Unibanco Holding S.A.",
        "founder_en": "Eudoro Villela, Alfredo Egydio de Souza Aranha",
        "founder_cn": "尤多罗·维莱拉、阿尔弗雷多·阿兰尼亚",
        "country": "🇧🇷 巴西",
        "hq": "圣保罗",
        "founded_year": 1924,
        "industry": "商业银行、信用卡发行业务与拉美金融",
        "revenue_m": "76,791"
    },
    {
        "rank": 175,
        "name_cn": "丰田通商公司",
        "name_en": "Toyota Tsusho Corporation",
        "founder_en": "Toyoda Automatic Loom Works Trading Division",
        "founder_cn": "丰田自动织机商事部门分立设立",
        "country": "🇯🇵 日本",
        "hq": "爱知县 名古屋",
        "founded_year": 1948,
        "industry": "丰田集团综合商社、汽车供应链与非洲商贸",
        "revenue_m": "76,716"
    },
    {
        "rank": 176,
        "name_cn": "瑞士罗氏公司",
        "name_en": "F. Hoffmann-La Roche AG",
        "founder_en": "Fritz Hoffmann-La Roche",
        "founder_cn": "弗里茨·霍夫曼-罗氏",
        "country": "🇨🇭 瑞士",
        "hq": "巴塞尔",
        "founded_year": 1896,
        "industry": "肿瘤靶向生物制药与体外诊断(IVD)",
        "revenue_m": "76,274"
    },
    {
        "rank": 177,
        "name_cn": "日本邮政控股公司",
        "name_en": "Japan Post Holdings Co., Ltd.",
        "founder_en": "Government of Japan (Postal Privatization)",
        "founder_cn": "日本政府 (日本邮政公社民营化拆分设立)",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 2006,
        "industry": "综合邮递物流、邮储银行与简保人寿保险",
        "revenue_m": "75,911"
    },
    {
        "rank": 178,
        "name_cn": "HCA 医疗保健公司",
        "name_en": "HCA Healthcare, Inc.",
        "founder_en": "Thomas F. Frist Sr., Thomas F. Frist Jr., Jack C. Massey",
        "founder_cn": "老托马斯·弗里斯特、小托马斯·弗里斯特、杰克·马西",
        "country": "🇺🇸 美国",
        "hq": "田纳西州 纳什维尔",
        "founded_year": 1968,
        "industry": "私立连锁综合医院网络与急救日间手术中心",
        "revenue_m": "75,600"
    },
    {
        "rank": 179,
        "name_cn": "EP集团",
        "name_en": "Energetický a průmyslový holding (EPH)",
        "founder_en": "Daniel Křetínský, Patrik Tkáč",
        "founder_cn": "丹尼尔·克雷廷斯基、帕特里克·特卡奇",
        "country": "🇨🇿 捷克",
        "hq": "布拉格",
        "founded_year": 2009,
        "industry": "欧洲综合电力能源基础设施与天然气输配",
        "revenue_m": "75,387"
    },
    {
        "rank": 180,
        "name_cn": "博枫公司",
        "name_en": "Brookfield Corporation",
        "founder_en": "William Mackenzie, Frederick Stark Nicholls",
        "founder_cn": "威廉·麦肯齐、弗雷德里克·斯塔克·尼科尔斯",
        "country": "🇨🇦 加拿大",
        "hq": "多伦多",
        "founded_year": 1899,
        "industry": "全球另类资产管理 (不动产/基建/清洁能源)",
        "revenue_m": "75,100"
    },
    {
        "rank": 181,
        "name_cn": "洛克希德－马丁",
        "name_en": "Lockheed Martin Corporation",
        "founder_en": "Allan Lockheed, Malcolm Lockheed, Glenn L. Martin",
        "founder_cn": "阿兰·洛克希德、马尔科姆·洛克希德、格伦·马丁",
        "country": "🇺🇸 美国",
        "hq": "马里兰州 贝塞斯达",
        "founded_year": 1995,
        "industry": "军用隐身战机 (F-35)、反导系统与国防军工",
        "revenue_m": "75,048"
    },
    {
        "rank": 182,
        "name_cn": "第一生命保险集团",
        "name_en": "The Dai-ichi Life Insurance Company, Limited",
        "founder_en": "Tsuneta Yano",
        "founder_cn": "矢野恒太",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1902,
        "industry": "相互人寿保险、年金与全球机构资产管理",
        "revenue_m": "75,033"
    },
    {
        "rank": 183,
        "name_cn": "中国第一汽车集团有限公司",
        "name_en": "FAW Group Co., Ltd.",
        "founder_en": "Central People's Government of China (First Automotive Works)",
        "founder_cn": "中央人民政府 (毛泽东奠基/第一汽车制造厂)",
        "country": "🇨🇳 中国",
        "hq": "吉林 长春",
        "founded_year": 1953,
        "industry": "红旗高端乘用车、解放重卡与合资车企制造",
        "revenue_m": "74,398"
    },
    {
        "rank": 184,
        "name_cn": "美国纽约人寿保险公司",
        "name_en": "New York Life Insurance Company",
        "founder_en": "Nautilus Insurance Company Charter",
        "founder_cn": "诺第留斯保险公司改制特许",
        "country": "🇺🇸 美国",
        "hq": "纽约州 纽约",
        "founded_year": 1845,
        "industry": "互助人寿保险与高净值家庭财富传承规划",
        "revenue_m": "73,146"
    },
    {
        "rank": 185,
        "name_cn": "Alimentation Couche-Tard公司",
        "name_en": "Alimentation Couche-Tard Inc.",
        "founder_en": "Alain Bouchard, Jacques D'Amours, Richard Fortin, Réal Plourde",
        "founder_cn": "阿兰·布沙尔、雅克·达穆尔、理查德·福尔汀、雷阿尔·普卢德",
        "country": "🇨🇦 加拿大",
        "hq": "拉瓦尔",
        "founded_year": 1980,
        "industry": "跨国连锁便利店 (Circle K) 与成品油零售",
        "revenue_m": "72,857"
    },
    {
        "rank": 186,
        "name_cn": "巴克莱",
        "name_en": "Barclays PLC",
        "founder_en": "John Freame, Thomas Gould, James Barclay",
        "founder_cn": "约翰·弗里姆、托马斯·古尔德、詹姆斯·巴克莱",
        "country": "🇬🇧 英国",
        "hq": "伦敦",
        "founded_year": 1690,
        "industry": "跨国商业银行、投行承销与消费信用卡金融",
        "revenue_m": "71,930"
    },
    {
        "rank": 187,
        "name_cn": "荷兰国际集团",
        "name_en": "ING Groep N.V.",
        "founder_en": "NMB Postbank Group & Nationale-Nederlanden Merger",
        "founder_cn": "NMB邮政银行与荷兰国民人寿合并",
        "country": "🇳🇱 荷兰",
        "hq": "阿姆斯特丹",
        "founded_year": 1991,
        "industry": "数字化零售银行与跨国企业批发金融",
        "revenue_m": "71,899"
    },
    {
        "rank": 188,
        "name_cn": "交通银行股份有限公司",
        "name_en": "Bank of Communications Co., Ltd.",
        "founder_en": "Ministry of Posts and Communications of Qing Dynasty",
        "founder_cn": "清政府邮传部 (设立赎回路权与发钞)",
        "country": "🇨🇳 中国",
        "hq": "上海",
        "founded_year": 1908,
        "industry": "大型综合商业银行与全牌照跨境金融服务",
        "revenue_m": "71,791"
    },
    {
        "rank": 189,
        "name_cn": "德意志银行",
        "name_en": "Deutsche Bank AG",
        "founder_en": "Ludwig Bamberger, Adelbert Delbrück",
        "founder_cn": "路德维希·班贝格、阿德尔伯特·德尔布吕克",
        "country": "🇩🇪 德国",
        "hq": "法兰克福",
        "founded_year": 1870,
        "industry": "投资银行、全球外汇交易与企业贷款服务",
        "revenue_m": "71,623"
    },
    {
        "rank": 190,
        "name_cn": "日本三井住友金融集团",
        "name_en": "Sumitomo Mitsui Financial Group, Inc. (SMFG)",
        "founder_en": "Sumitomo Bank & Sakura Bank Merger",
        "founder_cn": "住友银行与樱花银行合并组建",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 2002,
        "industry": "综合商业银行、证券经纪与海外项目融资",
        "revenue_m": "71,600"
    },
    {
        "rank": 191,
        "name_cn": "巴斯夫公司",
        "name_en": "BASF SE",
        "founder_en": "Friedrich Engelhorn",
        "founder_cn": "弗里德里希·恩格尔霍恩",
        "country": "🇩🇪 德国",
        "hq": "路德维希港",
        "founded_year": 1865,
        "industry": "特种化学品、高分子工程塑料与农化作物保护",
        "revenue_m": "71,513"
    },
    {
        "rank": 192,
        "name_cn": "日本永旺集团",
        "name_en": "AEON Co., Ltd.",
        "founder_en": "Takuya Okada (JUSCO Merger)",
        "founder_cn": "冈田卓也 (冈田屋等多家百货合并)",
        "country": "🇯🇵 日本",
        "hq": "千叶县 千叶市",
        "founded_year": 1926,
        "industry": "购物中心综合超市(GMS)与零售金融",
        "revenue_m": "71,479"
    },
    {
        "rank": 193,
        "name_cn": "波兰国营石油公司",
        "name_en": "Orlen S.A. (PKN Orlen)",
        "founder_en": "Petrochemia Płock & Centrala Produktów Naftowych",
        "founder_cn": "普沃茨克石化与波兰国家石油产品中心合并",
        "country": "🇵🇱 波兰",
        "hq": "普沃茨克",
        "founded_year": 1999,
        "industry": "石油炼化、天然气公用事业与加油站网络",
        "revenue_m": "71,277"
    },
    {
        "rank": 194,
        "name_cn": "印尼国家石油公司",
        "name_en": "Pertamina (Persero)",
        "founder_en": "Government of Indonesia (Permina & Pertamin Merger)",
        "founder_cn": "印度尼西亚政府 (两家国营石油合并设立)",
        "country": "🇮🇩 印度尼西亚",
        "hq": "雅加达",
        "founded_year": 1957,
        "industry": "印尼油气勘探开发、炼化与地热新能源",
        "revenue_m": "70,894"
    },
    {
        "rank": 195,
        "name_cn": "丰益国际",
        "name_en": "Wilmar International Limited",
        "founder_en": "Kuok Khoon Hong, Martua Sitorus",
        "founder_cn": "郭孔丰、吴笙福",
        "country": "🇸🇬 新加坡",
        "hq": "新加坡",
        "founded_year": 1991,
        "industry": "大宗农产品加工 (金龙鱼母公司) 与特种油脂",
        "revenue_m": "70,416"
    },
    {
        "rank": 196,
        "name_cn": "邦吉公司",
        "name_en": "Bunge Global SA",
        "founder_en": "Johann Peter Gottlieb Bunge",
        "founder_cn": "约翰·彼得·戈特利布·邦吉",
        "country": "🇺🇸 美国",
        "hq": "密苏里州 切斯特菲尔德",
        "founded_year": 1818,
        "industry": "国际大宗粮油贸易与油籽压榨深加工 (ABCD四大粮商)",
        "revenue_m": "70,329"
    },
    {
        "rank": 197,
        "name_cn": "日立",
        "name_en": "Hitachi, Ltd.",
        "founder_en": "Namihei Odaira",
        "founder_cn": "小平浪平",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1910,
        "industry": "社会基础设施系统、Lumada数字化与机电",
        "revenue_m": "70,246"
    },
    {
        "rank": 198,
        "name_cn": "纬创集团",
        "name_en": "Wistron Corporation",
        "founder_en": "Simon Lin",
        "founder_cn": "林宪铭 (由宏碁集团制造服务分拆设立)",
        "country": "🇹🇼 中国台湾",
        "hq": "台北市",
        "founded_year": 2001,
        "industry": "电子制造服务 (EMS) 与AI服务器算力代工",
        "revenue_m": "70,180"
    },
    {
        "rank": 199,
        "name_cn": "俄罗斯外贸银行",
        "name_en": "VTB Bank PJSC",
        "founder_en": "State Bank of the RSFSR / Government of Russia",
        "founder_cn": "俄罗斯联邦国家银行设立 (原对外贸易银行)",
        "country": "🇷🇺 俄罗斯",
        "hq": "圣彼得堡",
        "founded_year": 1990,
        "industry": "国有商业银行、大型企业金融与投行服务",
        "revenue_m": "69,867"
    },
    {
        "rank": 200,
        "name_cn": "慕尼黑再保险集团",
        "name_en": "Munich Re (Münchener Rückversicherungs-Gesellschaft)",
        "founder_en": "Carl von Thieme, Wilhelm von Finck",
        "founder_cn": "卡尔·冯·蒂梅、威廉·冯·芬克",
        "country": "🇩🇪 德国",
        "hq": "慕尼黑",
        "founded_year": 1880,
        "industry": "全球巨灾再保险与ERGO初级综合保险",
        "revenue_m": "69,816"
    }
]
