# -*- coding: utf-8 -*-
"""Data part 5: Companies 401 to 500"""

DATA_PART5 = [
    {
        "rank": 401,
        "name_cn": "日本KDDI电信公司",
        "name_en": "KDDI Corporation",
        "founder_en": "Kazuo Inamori (DDI, KDD & IDO Merger)",
        "founder_cn": "稻盛和夫 (第二电电/KDD/IDO合并创立)",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1984,
        "industry": "移动通信 (au)、光纤宽带与数字生活平台",
        "revenue_m": "40,289"
    },
    {
        "rank": 402,
        "name_cn": "德国中央合作银行",
        "name_en": "DZ BANK AG (Deutsche Zentral-Genossenschaftsbank)",
        "founder_en": "Prussian Central Cooperative Bank Act",
        "founder_cn": "普鲁士中央合作银行法案特许设立",
        "country": "🇩🇪 德国",
        "hq": "法兰克福",
        "founded_year": 1883,
        "industry": "德国合作金融体系中央结算与商业银行",
        "revenue_m": "40,148"
    },
    {
        "rank": 403,
        "name_cn": "Visa公司",
        "name_en": "Visa Inc.",
        "founder_en": "Dee Hock (BankAmericard Program Spinoff)",
        "founder_cn": "迪·霍克 (美洲银行信用卡计划独立演变)",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 旧金山",
        "founded_year": 1958,
        "industry": "全球数字支付结算清算网络 (VisaNet)",
        "revenue_m": "40,000"
    },
    {
        "rank": 404,
        "name_cn": "陶氏公司",
        "name_en": "Dow Inc.",
        "founder_en": "Herbert Henry Dow",
        "founder_cn": "赫伯特·亨利·陶",
        "country": "🇺🇸 美国",
        "hq": "密歇根州 米德兰",
        "founded_year": 1897,
        "industry": "基础化学品、功能聚合物与特种有机硅涂层",
        "revenue_m": "39,968"
    },
    {
        "rank": 405,
        "name_cn": "国民威斯敏斯特银行集团",
        "name_en": "NatWest Group plc",
        "founder_en": "National Provincial Bank & Westminster Bank Merger",
        "founder_cn": "国民地方银行与威斯敏斯特银行合并",
        "country": "🇬🇧 英国",
        "hq": "爱丁堡 / 伦敦",
        "founded_year": 1968,
        "industry": "英国大型商业银行、个人按揭信贷与中小企业金融",
        "revenue_m": "39,833"
    },
    {
        "rank": 406,
        "name_cn": "广东省广新控股集团有限公司",
        "name_en": "Guangdong Guangxin Holdings Group Co., Ltd.",
        "founder_en": "Guangdong Provincial People's Government",
        "founder_cn": "广东省人民政府 (省属外贸企业转型整合设立)",
        "country": "🇨🇳 中国",
        "hq": "广东 广州",
        "founded_year": 2000,
        "industry": "高性能金属新材料、生物医药与新兴实业制造",
        "revenue_m": "39,788"
    },
    {
        "rank": 407,
        "name_cn": "St. James's Place公司",
        "name_en": "St. James's Place plc",
        "founder_en": "Mike Wilson, Sir Mark Weinberg, Lord Rothschild",
        "founder_cn": "迈克·威尔逊、马克·温伯格爵士、罗斯柴尔德勋爵",
        "country": "🇬🇧 英国",
        "hq": "赛伦塞斯特",
        "founded_year": 1991,
        "industry": "高净值私人财富管理与个性化退休规划",
        "revenue_m": "39,727"
    },
    {
        "rank": 408,
        "name_cn": "住友生命保险公司",
        "name_en": "Sumitomo Life Insurance Company",
        "founder_en": "Kyutaro Yoshida (Hinode Life Insurance)",
        "founder_cn": "吉田久太郎等创立 (日之出人寿演变)",
        "country": "🇯🇵 日本",
        "hq": "大阪",
        "founded_year": 1907,
        "industry": "相互人寿保险与综合康养活力保障 (Vitality)",
        "revenue_m": "39,640"
    },
    {
        "rank": 409,
        "name_cn": "友邦保险控股有限公司",
        "name_en": "AIA Group Limited",
        "founder_en": "Cornelius Vander Starr",
        "founder_cn": "科尼利厄斯·范德·斯塔尔 (美亚保险始创)",
        "country": "🇭🇰 中国香港",
        "hq": "香港",
        "founded_year": 1919,
        "industry": "亚太泛地区独立人寿保险与高端个人医疗保障",
        "revenue_m": "39,639"
    },
    {
        "rank": 410,
        "name_cn": "中国中车集团有限公司",
        "name_en": "CRRC Corporation Limited",
        "founder_en": "State Council of China (CSR & CNR Merger)",
        "founder_cn": "国务院 (中国南车与中国北车重组组建)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1881,
        "industry": "复兴号高速动车组、城轨地铁列车与电力机车制造",
        "revenue_m": "39,502"
    },
    {
        "rank": 411,
        "name_cn": "上海医药集团股份有限公司",
        "name_en": "Shanghai Pharmaceuticals Holding Co., Ltd.",
        "founder_en": "Shanghai Municipal People's Government",
        "founder_cn": "上海市国资委 (整合上海医药骨干资产设立)",
        "country": "🇨🇳 中国",
        "hq": "上海",
        "founded_year": 1994,
        "industry": "创新原研制药、现代中药与全渠道药品商业分销",
        "revenue_m": "39,454"
    },
    {
        "rank": 412,
        "name_cn": "US Foods Holding公司",
        "name_en": "US Foods Holding Corp.",
        "founder_en": "Monarch Foods & US Foodservice Mergers",
        "founder_cn": "君主食品与全美食品服务联合演变",
        "country": "🇺🇸 美国",
        "hq": "伊利诺伊州 罗斯蒙特",
        "founded_year": 1853,
        "industry": "餐饮全品类食材冷链配送与商用厨房综合服务",
        "revenue_m": "39,424"
    },
    {
        "rank": 413,
        "name_cn": "北京汽车集团有限公司",
        "name_en": "Beijing Automotive Group Co., Ltd. (BAIC Group)",
        "founder_en": "Beijing Municipal People's Government (Beijing Auto Works)",
        "founder_cn": "北京市人民政府 (北京汽车制造厂演变设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1958,
        "industry": "北汽越野车、极狐智能纯电整车与合资车企制造",
        "revenue_m": "39,393"
    },
    {
        "rank": 414,
        "name_cn": "新华人寿保险股份有限公司",
        "name_en": "New China Life Insurance Company Ltd. (NCI)",
        "founder_en": "Approved by People's Bank of China",
        "founder_cn": "中国人民银行批准设立 (股份制专业寿险公司)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1996,
        "industry": "人寿保险、长期年金保险与全龄康养社区投资",
        "revenue_m": "39,380"
    },
    {
        "rank": 415,
        "name_cn": "杭州钢铁集团有限公司",
        "name_en": "Hangzhou Iron and Steel Group Co., Ltd. (Hangang)",
        "founder_en": "Zhejiang Provincial People's Government",
        "founder_cn": "浙江省委省政府 (杭州半山钢铁厂创建设立)",
        "country": "🇨🇳 中国",
        "hq": "浙江 杭州",
        "founded_year": 1957,
        "industry": "特种优钢制造、节能环保治理与大数据数字经济",
        "revenue_m": "39,236"
    },
    {
        "rank": 416,
        "name_cn": "三菱电机股份有限公司",
        "name_en": "Mitsubishi Electric Corporation",
        "founder_en": "Mitsubishi Shipbuilding Electrical Machinery Spinoff",
        "founder_cn": "三菱造船电机制作所分立设立",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1921,
        "industry": "工业自动化PLC、变频器、高速电梯与功率半导体",
        "revenue_m": "39,113"
    },
    {
        "rank": 417,
        "name_cn": "巴登-符腾堡州能源公司",
        "name_en": "EnBW (Energie Baden-Württemberg AG)",
        "founder_en": "Badenwerk & EVS Merger",
        "founder_cn": "巴登州立电力与符腾堡综合电力合并组建",
        "country": "🇩🇪 德国",
        "hq": "卡尔斯鲁厄",
        "founded_year": 1997,
        "industry": "公用事业电网运营、海上风电与充电基础设施",
        "revenue_m": "38,789"
    },
    {
        "rank": 418,
        "name_cn": "法国邮政",
        "name_en": "La Poste",
        "founder_en": "Royal Edict of King Louis XI of France",
        "founder_cn": "法国国王路易十一敕令皇家邮政设立",
        "country": "🇫🇷 法国",
        "hq": "伊西莱穆利诺",
        "founded_year": 1477,
        "industry": "普遍公共邮政服务、法国邮政银行与国际快递",
        "revenue_m": "38,786"
    },
    {
        "rank": 419,
        "name_cn": "杭州市实业投资集团有限公司",
        "name_en": "Hangzhou Industrial Investment Group (Hangshi Group)",
        "founder_en": "Hangzhou Municipal People's Government",
        "founder_cn": "杭州市人民政府 (市属工业资产重组改制设立)",
        "country": "🇨🇳 中国",
        "hq": "浙江 杭州",
        "founded_year": 2001,
        "industry": "高端装备制造投资、园区开发运营与大宗供应链",
        "revenue_m": "38,760"
    },
    {
        "rank": 420,
        "name_cn": "澳大利亚国民银行",
        "name_en": "National Australia Bank Limited (NAB)",
        "founder_en": "Alexander Gibb, Andrew Cruickshank (National Bank of Australasia)",
        "founder_cn": "亚历山大·吉布、安德鲁·克鲁克香克",
        "country": "🇦🇺 澳大利亚",
        "hq": "墨尔本",
        "founded_year": 1858,
        "industry": "澳大利亚大型商业银行与农业小微企业信贷",
        "revenue_m": "38,754"
    },
    {
        "rank": 421,
        "name_cn": "深圳市投资控股有限公司",
        "name_en": "Shenzhen Investment Holdings Co., Ltd. (SIHC)",
        "founder_en": "State-owned Assets Supervision Commission of Shenzhen",
        "founder_cn": "深圳市国资委 (国有资本投资运营综合平台)",
        "country": "🇨🇳 中国",
        "hq": "广东 深圳",
        "founded_year": 2004,
        "industry": "高新科技园区投资运营、战略新兴产业与综合金融",
        "revenue_m": "38,664"
    },
    {
        "rank": 422,
        "name_cn": "亿滋国际",
        "name_en": "Mondelēz International, Inc.",
        "founder_en": "James L. Kraft (Kraft Foods Spinoff)",
        "founder_cn": "詹姆斯·L·卡夫 (卡夫食品零食业务独立分拆)",
        "country": "🇺🇸 美国",
        "hq": "伊利诺伊州 芝加哥",
        "founded_year": 1923,
        "industry": "饼干 (奥利奥/焙朗)、巧克力 (妙卡/吉百利) 与糖果零食",
        "revenue_m": "38,537"
    },
    {
        "rank": 423,
        "name_cn": "曼福集团",
        "name_en": "MAPFRE S.A.",
        "founder_en": "Mutualidad de la Agrupación de Propietarios de Fincas Rústicas",
        "founder_cn": "西班牙农业庄园主土地互助保险公社",
        "country": "🇪🇸 西班牙",
        "hq": "马哈达翁达",
        "founded_year": 1933,
        "industry": "跨国财产保险、个人车险与全球再保险服务",
        "revenue_m": "38,432"
    },
    {
        "rank": 424,
        "name_cn": "巴西淡水河谷公司",
        "name_en": "Vale S.A. (Companhia Vale do Rio Doce)",
        "founder_en": "President Getúlio Vargas (Federal Decree)",
        "founder_cn": "热图利奥·瓦加斯总统法令设立",
        "country": "🇧🇷 巴西",
        "hq": "里约热内卢",
        "founded_year": 1942,
        "industry": "全球高品位铁矿石球团、镍矿、铜矿开采与物流铁路",
        "revenue_m": "38,403"
    },
    {
        "rank": 425,
        "name_cn": "CDP集团",
        "name_en": "Cassa Depositi e Prestiti (CDP Group)",
        "founder_en": "Royal Decree of King Carlo Alberto of Sardinia",
        "founder_cn": "撒丁王国国王卡洛·阿尔贝托皇家法令设立",
        "country": "🇮🇹 意大利",
        "hq": "罗马",
        "founded_year": 1850,
        "industry": "意大利国家主权促进银行与重大基础设施投资",
        "revenue_m": "38,170"
    },
    {
        "rank": 426,
        "name_cn": "Lithia Motors公司",
        "name_en": "Lithia Motors, Inc.",
        "founder_en": "Walt DeBoer",
        "founder_cn": "沃尔特·德波尔",
        "country": "🇺🇸 美国",
        "hq": "俄勒冈州 梅德福",
        "founded_year": 1946,
        "industry": "北美跨国汽车授权经销网络与Driveway线上汽车平台",
        "revenue_m": "38,134"
    },
    {
        "rank": 427,
        "name_cn": "GE Vernova公司",
        "name_en": "GE Vernova Inc.",
        "founder_en": "General Electric Power & Renewables Spinoff",
        "founder_cn": "通用电气电力与新能源业务独立分拆上市",
        "country": "🇺🇸 美国",
        "hq": "马萨诸塞州 剑桥",
        "founded_year": 2024,
        "industry": "大型重型燃气轮机、海上风电与电网电气化转型",
        "revenue_m": "38,068"
    },
    {
        "rank": 428,
        "name_cn": "山东黄金集团有限公司",
        "name_en": "Shandong Gold Group Co., Ltd.",
        "founder_en": "Shandong Provincial People's Government",
        "founder_cn": "山东省人民政府 (省属重点黄金矿山企业组建)",
        "country": "🇨🇳 中国",
        "hq": "山东 济南",
        "founded_year": 1996,
        "industry": "深部金矿绿色开采、高纯黄金冶炼与国际黄金贸易",
        "revenue_m": "37,936"
    },
    {
        "rank": 429,
        "name_cn": "卡塔尔国民银行",
        "name_en": "Qatar National Bank (QNB Group)",
        "founder_en": "Emir of Qatar Emiri Decree No. 7",
        "founder_cn": "卡塔尔埃米尔第7号法令特许设立",
        "country": "🇶🇦 卡塔尔",
        "hq": "多哈",
        "founded_year": 1964,
        "industry": "中东及北非跨国商业银行、大型主权项目金融",
        "revenue_m": "37,831"
    },
    {
        "rank": 430,
        "name_cn": "广州市建筑集团有限公司",
        "name_en": "Guangzhou Municipal Construction Group Co., Ltd.",
        "founder_en": "Guangzhou Municipal People's Government",
        "founder_cn": "广州市人民政府 (广州市建筑工程局改制设立)",
        "country": "🇨🇳 中国",
        "hq": "广东 广州",
        "founded_year": 1950,
        "industry": "大型工程总承包、地标超高层建筑与城市更新改造",
        "revenue_m": "37,816"
    },
    {
        "rank": 431,
        "name_cn": "文晔科技公司",
        "name_en": "WT Microelectronics Co., Ltd.",
        "founder_en": "Eric Cheng (Cheng Wen-tsung)",
        "founder_cn": "郑文宗 (收购富昌电子 Future Electronics)",
        "country": "🇹🇼 中国台湾",
        "hq": "新北市",
        "founded_year": 1993,
        "industry": "半导体电子元器件全球分销与技术方案增值服务",
        "revenue_m": "37,808"
    },
    {
        "rank": 432,
        "name_cn": "英国标准人寿保险公司",
        "name_en": "Phoenix Group Holdings plc (Standard Life)",
        "founder_en": "James Chalmers (Life Association of Scotland)",
        "founder_cn": "詹姆斯·查尔默斯 (标准人寿历史品牌)",
        "country": "🇬🇧 英国",
        "hq": "伦敦 / 爱丁堡",
        "founded_year": 1825,
        "industry": "长期人寿保险、年金与养老金资产投资管理",
        "revenue_m": "37,779"
    },
    {
        "rank": 433,
        "name_cn": "海亮集团有限公司",
        "name_en": "Hailiang Group Co., Ltd.",
        "founder_en": "Feng Hailiang",
        "founder_cn": "冯海良",
        "country": "🇨🇳 中国",
        "hq": "浙江 绍兴 / 杭州",
        "founded_year": 1989,
        "industry": "高精度铜管铜箔精密智能制造、基础教育与现代农业",
        "revenue_m": "37,473"
    },
    {
        "rank": 434,
        "name_cn": "国际航空集团",
        "name_en": "International Consolidated Airlines Group S.A. (IAG)",
        "founder_en": "British Airways & Iberia Merger",
        "founder_cn": "英国航空与西班牙国家航空合并组建",
        "country": "🇪🇸 西班牙 / 🇬🇧 英国",
        "hq": "马德里 / 伦敦",
        "founded_year": 2011,
        "industry": "跨国干线民航控股 (英航/伊比利亚/爱尔兰航空)",
        "revenue_m": "37,461"
    },
    {
        "rank": 435,
        "name_cn": "CRH公司",
        "name_en": "CRH plc",
        "founder_en": "Cement Limited & Roadstone Limited Merger",
        "founder_cn": "爱尔兰水泥公司与路石公司合并",
        "country": "🇮🇪 爱尔兰",
        "hq": "都柏林",
        "founded_year": 1970,
        "industry": "水泥骨料、特种沥青材料与装配式建筑构件",
        "revenue_m": "37,447"
    },
    {
        "rank": 436,
        "name_cn": "铜陵有色金属集团控股有限公司",
        "name_en": "Tongling Nonferrous Metals Group Holding Co., Ltd.",
        "founder_en": "Government Administration Council of China",
        "founder_cn": "中央人民政府政务院设立 (新中国最早铜工业基地)",
        "country": "🇨🇳 中国",
        "hq": "安徽 铜陵",
        "founded_year": 1949,
        "industry": "铜矿采选、高纯阴极铜冶炼与超薄锂电池铜箔",
        "revenue_m": "37,391"
    },
    {
        "rank": 437,
        "name_cn": "DSV公司",
        "name_en": "DSV A/S (De Sammensluttede Vognmænd)",
        "founder_en": "Leif Tullberg and 9 independent truckers",
        "founder_cn": "莱夫·图尔伯格等9位独立卡车承运人联合创立",
        "country": "🇩🇰 丹麦",
        "hq": "海泽胡瑟讷",
        "founded_year": 1976,
        "industry": "全球空海陆货运代理、无船承运人与合同物流仓储",
        "revenue_m": "37,381"
    },
    {
        "rank": 438,
        "name_cn": "美光科技公司",
        "name_en": "Micron Technology, Inc.",
        "founder_en": "Ward Parkinson, Joe Parkinson, Dennis Wilson, Doug Egly",
        "founder_cn": "沃德·帕金森、乔·帕金森、丹尼斯·威尔逊、道格·埃格利",
        "country": "🇺🇸 美国",
        "hq": "爱达荷州 博伊西",
        "founded_year": 1978,
        "industry": "DRAM动态随机存储、HBM3E内存与NAND固态存储芯片",
        "revenue_m": "37,378"
    },
    {
        "rank": 439,
        "name_cn": "德国联邦铁路公司",
        "name_en": "Deutsche Bahn AG (DB)",
        "founder_en": "Deutsche Bundesbahn & Deutsche Reichsbahn Merger",
        "founder_cn": "两德统一后联邦铁路与国营铁路合并改制设立",
        "country": "🇩🇪 德国",
        "hq": "柏林",
        "founded_year": 1994,
        "industry": "全国城际高速铁路客运 (ICE) 与跨国货运物流 (DB Cargo)",
        "revenue_m": "37,359"
    },
    {
        "rank": 440,
        "name_cn": "西太平洋银行",
        "name_en": "Westpac Banking Corporation",
        "founder_en": "Governor Lachlan Macquarie (Bank of New South Wales 1817)",
        "founder_cn": "拉克兰·麦考利总督特许 (新南威尔士银行前身)",
        "country": "🇦🇺 澳大利亚",
        "hq": "悉尼",
        "founded_year": 1817,
        "industry": "商业银行、个人住房抵押贷款与机构金融",
        "revenue_m": "37,338"
    },
    {
        "rank": 441,
        "name_cn": "BAE系统公司",
        "name_en": "BAE Systems plc",
        "founder_en": "British Aerospace & Marconi Electronic Systems Merger",
        "founder_cn": "英国宇航公司与马可尼电子系统合并组建",
        "country": "🇬🇧 英国",
        "hq": "法恩伯勒",
        "founded_year": 1999,
        "industry": "台风战斗机、机敏级核潜艇、装甲车辆与航天防务",
        "revenue_m": "37,322"
    },
    {
        "rank": 442,
        "name_cn": "华纳兄弟探索公司",
        "name_en": "Warner Bros. Discovery, Inc.",
        "founder_en": "Harry, Albert, Sam, and Jack Warner & John Malone",
        "founder_cn": "华纳四兄弟创立 / 探索频道合并重组",
        "country": "🇺🇸 美国",
        "hq": "纽约州 纽约",
        "founded_year": 1923,
        "industry": "电影制片厂、HBO电视剧、DC超级英雄与Max流媒体",
        "revenue_m": "37,296"
    },
    {
        "rank": 443,
        "name_cn": "日本三菱重工业股份有限公司",
        "name_en": "Mitsubishi Heavy Industries, Ltd. (MHI)",
        "founder_en": "Yataro Iwasaki (Nagasaki Shipyard)",
        "founder_cn": "岩崎弥太郎 (长崎造船所演变)",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1884,
        "industry": "燃气轮机、H3运载火箭、核能发电设备与国防军工舰船",
        "revenue_m": "37,275"
    },
    {
        "rank": 444,
        "name_cn": "法国航空－荷兰皇家航空集团",
        "name_en": "Air France-KLM",
        "founder_en": "Air France & KLM Royal Dutch Airlines Merger",
        "founder_cn": "法国航空与荷兰皇家航空合并组建",
        "country": "🇫🇷 法国 / 🇳🇱 荷兰",
        "hq": "巴黎",
        "founded_year": 2004,
        "industry": "泛欧洲大型民用航空客运枢纽与国际货运航线",
        "revenue_m": "37,229"
    },
    {
        "rank": 445,
        "name_cn": "蜀道投资集团有限责任公司",
        "name_en": "Shudao Investment Group Co., Ltd.",
        "founder_en": "Sichuan Provincial People's Government",
        "founder_cn": "四川省人民政府 (四川铁投与四川交投联合重组)",
        "country": "🇨🇳 中国",
        "hq": "四川 成都",
        "founded_year": 2021,
        "industry": "高原山区复杂高速公路、高铁铁路投资建设与综合交通",
        "revenue_m": "37,213"
    },
    {
        "rank": 446,
        "name_cn": "星巴克公司",
        "name_en": "Starbucks Corporation",
        "founder_en": "Jerry Baldwin, Zev Siegl, Gordon Bowker / Howard Schultz",
        "founder_cn": "杰里·鲍德温、泽夫·西格尔、戈登·鲍克 / 霍华德·舒尔茨",
        "country": "🇺🇸 美国",
        "hq": "华盛顿州 西雅图",
        "founded_year": 1971,
        "industry": "精品现磨咖啡连锁、咖啡豆烘焙与茶瓦纳茶饮",
        "revenue_m": "37,184"
    },
    {
        "rank": 447,
        "name_cn": "中国民生银行股份有限公司",
        "name_en": "China Minsheng Banking Corp., Ltd.",
        "founder_en": "Jing Shuping & All-China Federation of Industry and Commerce",
        "founder_cn": "经叔平倡导发起 (全国工商联会员企业联合设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1996,
        "industry": "全国性民营股份制商业银行与小微民营企业普惠金融",
        "revenue_m": "37,039"
    },
    {
        "rank": 448,
        "name_cn": "Migros集团",
        "name_en": "Migros-Genossenschafts-Bund (MGB)",
        "founder_en": "Gottlieb Duttweiler",
        "founder_cn": "戈特利布·杜特韦勒",
        "country": "🇨🇭 瑞士",
        "hq": "苏黎世",
        "founded_year": 1925,
        "industry": "瑞士合作社连锁食品超市、百货商场与平价商业",
        "revenue_m": "37,015"
    },
    {
        "rank": 449,
        "name_cn": "大和房建",
        "name_en": "Daiwa House Industry Co., Ltd.",
        "founder_en": "Nobuo Ishibashi",
        "founder_cn": "石桥信夫",
        "country": "🇯🇵 日本",
        "hq": "大阪",
        "founded_year": 1955,
        "industry": "装配式预制钢结构住宅、现代物流仓储与商业地产",
        "revenue_m": "37,004"
    },
    {
        "rank": 450,
        "name_cn": "江苏沙钢集团有限公司",
        "name_en": "Jiangsu Shagang Group Co., Ltd.",
        "founder_en": "Shen Wenrong",
        "founder_cn": "沈文荣",
        "country": "🇨🇳 中国",
        "hq": "江苏 张家港",
        "founded_year": 1975,
        "industry": "民营超大型特钢宽厚板、优线特棒与工业特钢",
        "revenue_m": "36,983"
    },
    {
        "rank": 451,
        "name_cn": "中国电子信息产业集团有限公司",
        "name_en": "China Electronics Corporation (CEC)",
        "founder_en": "Ministry of Electronics Industry of China",
        "founder_cn": "电子工业部所属骨干企事业单位组建设立",
        "country": "🇨🇳 中国",
        "hq": "广东 深圳",
        "founded_year": 1989,
        "industry": "国家网信自主核心体系 (飞腾CPU/银河麒麟OS/数据要素)",
        "revenue_m": "36,981"
    },
    {
        "rank": 452,
        "name_cn": "World Kinect公司",
        "name_en": "World Kinect Corporation (World Fuel Services)",
        "founder_en": "Paul Stebbins, Michael Kasbar",
        "founder_cn": "保罗·斯特宾斯、迈克尔·卡斯巴",
        "country": "🇺🇸 美国",
        "hq": "佛罗里达州 迈阿密",
        "founded_year": 1984,
        "industry": "全球航空燃料、远洋船用重油加注与综合能源服务",
        "revenue_m": "36,917"
    },
    {
        "rank": 453,
        "name_cn": "阿斯麦公司",
        "name_en": "ASML Holding N.V.",
        "founder_en": "Philips & ASM International Joint Venture",
        "founder_cn": "飞利浦与先进半导体材料(ASMI)合资创立",
        "country": "🇳🇱 荷兰",
        "hq": "费尔德霍芬",
        "founded_year": 1984,
        "industry": "半导体先进光刻机 (EUV高数值孔径/DUV浸润式)",
        "revenue_m": "36,846"
    },
    {
        "rank": 454,
        "name_cn": "安进",
        "name_en": "Amgen Inc. (Applied Molecular Genetics)",
        "founder_en": "William Bowes, George B. Rathmann, and scientists",
        "founder_cn": "威廉·鲍斯、乔治·拉思曼等科学家团队创立",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 千橡市",
        "founded_year": 1980,
        "industry": "生物重组制药、靶向促红素、骨质疏松与肿瘤生物药",
        "revenue_m": "36,751"
    },
    {
        "rank": 455,
        "name_cn": "蒂森克虏伯",
        "name_en": "thyssenkrupp AG",
        "founder_en": "August Thyssen, Alfred Krupp (Thyssen & Krupp Merger)",
        "founder_cn": "奥古斯特·蒂森、阿尔弗雷德·克虏伯 (两大家族合并)",
        "country": "🇩🇪 德国",
        "hq": "埃森",
        "founded_year": 1999,
        "industry": "高品质特种汽车钢板、工业传动零部件与氢能电解槽",
        "revenue_m": "36,229"
    },
    {
        "rank": 456,
        "name_cn": "中国大唐集团有限公司",
        "name_en": "China Datang Corporation",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (国家电力体制改革分立设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 2002,
        "industry": "高效清洁火电、大型水电流域开发与风光新能源",
        "revenue_m": "36,173"
    },
    {
        "rank": 457,
        "name_cn": "长江和记实业有限公司",
        "name_en": "CK Hutchison Holdings Limited",
        "founder_en": "Li Ka-shing",
        "founder_cn": "李嘉诚 (长江实业与和记黄埔合并重组)",
        "country": "🇭🇰 中国香港",
        "hq": "香港",
        "founded_year": 1828,
        "industry": "全球港口码头、屈臣氏保健零售、跨国电信与能源基建",
        "revenue_m": "35,923"
    },
    {
        "rank": 458,
        "name_cn": "奥地利石油天然气集团",
        "name_en": "OMV AG",
        "founder_en": "Austrian Government (Österreichische Mineralölverwaltung)",
        "founder_cn": "奥地利政府法令设立 (奥地利矿物油管理局)",
        "country": "🇦🇹 奥地利",
        "hq": "维也纳",
        "founded_year": 1956,
        "industry": "中欧石油天然气勘探炼化与北欧化工 (Borealis) 循环塑料",
        "revenue_m": "35,914"
    },
    {
        "rank": 459,
        "name_cn": "和硕",
        "name_en": "Pegatron Corporation",
        "founder_en": "T.H. Tung (ASUSTeK OEM Spinoff)",
        "founder_cn": "童子贤 (华硕电脑代工制造部门分立设立)",
        "country": "🇹🇼 中国台湾",
        "hq": "台北市",
        "founded_year": 2008,
        "industry": "智能手机、平板电脑与车载电子制造服务 (EMS)",
        "revenue_m": "35,857"
    },
    {
        "rank": 460,
        "name_cn": "斯伦贝谢公司",
        "name_en": "SLB (Schlumberger Limited)",
        "founder_en": "Conrad Schlumberger, Marcel Schlumberger",
        "founder_cn": "康拉德·斯伦贝谢、马塞尔·斯伦贝谢",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 休斯敦",
        "founded_year": 1926,
        "industry": "油气田测井、深海钻井与地下碳捕集数字化能源技术",
        "revenue_m": "35,708"
    },
    {
        "rank": 461,
        "name_cn": "赛峰集团",
        "name_en": "Safran S.A.",
        "founder_en": "SNECMA & SAGEM Merger",
        "founder_cn": "法国国家航空空间研究公司与萨基姆合并组建",
        "country": "🇫🇷 法国",
        "hq": "巴黎",
        "founded_year": 1896,
        "industry": "民用航空发动机 (LEAP合资研发)、起落架与航空电子",
        "revenue_m": "35,705"
    },
    {
        "rank": 462,
        "name_cn": "损保控股有限公司",
        "name_en": "Sompo Holdings, Inc.",
        "founder_en": "Tokyo Fire Insurance (Yasuda Fire & Sompo Japan)",
        "founder_cn": "东京火灾保险创立演变 (损保日本兴亚合并)",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1888,
        "industry": "财产意外险、海外商业险与日本大型老年看护服务",
        "revenue_m": "35,651"
    },
    {
        "rank": 463,
        "name_cn": "湖南钢铁集团有限公司",
        "name_en": "Hunan Steel Group Co., Ltd.",
        "founder_en": "Hunan Provincial People's Government (Valin Steel)",
        "founder_cn": "湖南省人民政府 (原华菱钢铁集团改制设立)",
        "country": "🇨🇳 中国",
        "hq": "湖南 长沙 / 湘潭",
        "founded_year": 1997,
        "industry": "高端宽厚板造船用钢、无缝钢管与汽车高端结构特钢",
        "revenue_m": "35,623"
    },
    {
        "rank": 464,
        "name_cn": "通威集团有限公司",
        "name_en": "Tongwei Group Co., Ltd.",
        "founder_en": "Liu Hanyuan",
        "founder_cn": "刘汉元",
        "country": "🇨🇳 中国",
        "hq": "四川 成都",
        "founded_year": 1982,
        "industry": "高纯晶硅、高效太阳能电池片与绿色渔光一体农牧",
        "revenue_m": "35,602"
    },
    {
        "rank": 465,
        "name_cn": "Cenovus Energy公司",
        "name_en": "Cenovus Energy Inc.",
        "founder_en": "Encana Corporation Oil Sands Spinoff",
        "founder_cn": "恩卡纳公司油砂业务分拆独立设立",
        "country": "🇨🇦 加拿大",
        "hq": "卡尔加里",
        "founded_year": 2009,
        "industry": "加拿大原油油砂蒸汽重力开采 (SAGD) 与炼油",
        "revenue_m": "35,567"
    },
    {
        "rank": 466,
        "name_cn": "瑞士ABB集团",
        "name_en": "ABB Ltd (ASEA Brown Boveri)",
        "founder_en": "Ludvig Fredholm (ASEA) & Charles Brown, Walter Boveri",
        "founder_cn": "路德维希·弗雷德霍姆、查尔斯·布朗、瓦尔特·博韦里",
        "country": "🇨🇭 瑞士",
        "hq": "苏黎世",
        "founded_year": 1883,
        "industry": "工业机器人本体、电机驱动器与高低压电气成套",
        "revenue_m": "35,551"
    },
    {
        "rank": 467,
        "name_cn": "广州医药集团有限公司",
        "name_en": "Guangzhou Pharmaceutical Holdings Limited (GPHL)",
        "founder_en": "Guangzhou Municipal People's Government",
        "founder_cn": "广州市人民政府 (市属中药与西药骨干资产整合)",
        "country": "🇨🇳 中国",
        "hq": "广东 广州",
        "founded_year": 1996,
        "industry": "经典现代中药 (王老吉/陈李济)、生物医药与医药商业",
        "revenue_m": "35,509"
    },
    {
        "rank": 468,
        "name_cn": "CHS公司",
        "name_en": "CHS Inc.",
        "founder_en": "Cenex & Harvest States Cooperatives Merger",
        "founder_cn": "塞内克斯石油与丰收州谷物合作社联合组建",
        "country": "🇺🇸 美国",
        "hq": "明尼苏达州 因弗格罗夫海茨",
        "founded_year": 1931,
        "industry": "全美农业合作社、谷物粮油加工与农业炼油能源",
        "revenue_m": "35,463"
    },
    {
        "rank": 469,
        "name_cn": "Perusahaan Listrik Negara公司",
        "name_en": "PT Perusahaan Listrik Negara (PLN)",
        "founder_en": "President Sukarno Decree No. 19",
        "founder_cn": "苏加诺总统第19号法令特许设立",
        "country": "🇮🇩 印度尼西亚",
        "hq": "雅加达",
        "founded_year": 1965,
        "industry": "印度尼西亚群岛电力发电、高压输电与配电网络",
        "revenue_m": "35,408"
    },
    {
        "rank": 470,
        "name_cn": "CFE公司",
        "name_en": "Comisión Federal de Electricidad (CFE)",
        "founder_en": "President Lázaro Cárdenas Decree",
        "founder_cn": "拉萨罗·卡德纳斯总统法令设立",
        "country": "🇲🇽 墨西哥",
        "hq": "墨西哥城",
        "founded_year": 1937,
        "industry": "墨西哥国家电力公用事业、水力地热发电与全国电网",
        "revenue_m": "35,371"
    },
    {
        "rank": 471,
        "name_cn": "印度工业信贷投资银行",
        "name_en": "ICICI Bank Limited",
        "founder_en": "World Bank & Government of India Joint Initiative",
        "founder_cn": "世界银行与印度政府联合倡议发起设立",
        "country": "🇮🇳 印度",
        "hq": "孟买",
        "founded_year": 1994,
        "industry": "私营商业银行、数字个人信贷与中小型企业融资",
        "revenue_m": "35,325"
    },
    {
        "rank": 472,
        "name_cn": "森科能源公司",
        "name_en": "Suncor Energy Inc.",
        "founder_en": "Sun Company of Canada (J. Howard Pew)",
        "founder_cn": "加拿大太阳石油公司设立",
        "country": "🇨🇦 加拿大",
        "hq": "卡尔加里",
        "founded_year": 1953,
        "industry": "加拿大商业油砂合成原油开采与Petro-Canada加油网络",
        "revenue_m": "35,291"
    },
    {
        "rank": 473,
        "name_cn": "德国巴登-符腾堡州银行",
        "name_en": "Landesbank Baden-Württemberg (LBBW)",
        "founder_en": "SüdwestLB, Landesgirokasse & L-Bank Merger",
        "founder_cn": "西南州立银行与州立转账储蓄银行合并",
        "country": "🇩🇪 德国",
        "hq": "斯图加特",
        "founded_year": 1999,
        "industry": "公立州立银行、储蓄银行中央清算与德国中型隐形冠军企业金融",
        "revenue_m": "35,114"
    },
    {
        "rank": 474,
        "name_cn": "阿联酋航空集团",
        "name_en": "The Emirates Group (Emirates Airline)",
        "founder_en": "Sheikh Ahmed bin Saeed Al Maktoum",
        "founder_cn": "艾哈迈德·本·赛义德·阿勒马克图姆 (迪拜王室创立)",
        "country": "🇦🇪 阿联酋",
        "hq": "迪拜",
        "founded_year": 1985,
        "industry": "全宽体机队国际干线航空客运 (A380/B777) 与空港服务",
        "revenue_m": "35,054"
    },
    {
        "rank": 475,
        "name_cn": "德龙钢铁产业集团有限公司",
        "name_en": "Delong Steel Industry Group Co., Ltd.",
        "founder_en": "Ding Liguo",
        "founder_cn": "丁立国",
        "country": "🇨🇳 中国",
        "hq": "河北 邢台 / 天津",
        "founded_year": 1992,
        "industry": "绿色生态钢铁冶炼、新天钢混改与印尼德信海外钢厂",
        "revenue_m": "34,926"
    },
    {
        "rank": 476,
        "name_cn": "加拿大鲍尔集团",
        "name_en": "Power Corporation of Canada",
        "founder_en": "Arthur J. Nesbitt, Peter A. T. Thomson",
        "founder_cn": "亚瑟·J·内斯比特、彼得·A·汤姆森",
        "country": "🇨🇦 加拿大",
        "hq": "蒙特利尔",
        "founded_year": 1925,
        "industry": "跨国综合金融控股、大人寿保险 (Great-West) 与资管 (IGM)",
        "revenue_m": "34,900"
    },
    {
        "rank": 477,
        "name_cn": "荷兰合作银行集团",
        "name_en": "Rabobank (Coöperatieve Rabobank U.A.)",
        "founder_en": "Coöperatieve Centrale Raiffeisen-Bank & Boerenleenbank Merger",
        "founder_cn": "荷兰莱夫艾森合作银行与农民借贷银行合并组建",
        "country": "🇳🇱 荷兰",
        "hq": "乌得勒支",
        "founded_year": 1898,
        "industry": "全球农业与食品供应链专业金融、合作制商业银行",
        "revenue_m": "34,873"
    },
    {
        "rank": 478,
        "name_cn": "超威半导体公司",
        "name_en": "Advanced Micro Devices, Inc. (AMD)",
        "founder_en": "Jerry Sanders and 7 former Fairchild engineers",
        "founder_cn": "杰里·桑德斯等8位仙童半导体工程师创立",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 圣克拉拉",
        "founded_year": 1969,
        "industry": "Zen架构微处理器 (锐龙/霄龙) 与Instinct数据中心AI芯片",
        "revenue_m": "34,639"
    },
    {
        "rank": 479,
        "name_cn": "Coupang公司",
        "name_en": "Coupang, Inc.",
        "founder_en": "Bom Kim",
        "founder_cn": "金范锡",
        "country": "🇰🇷 韩国",
        "hq": "首尔",
        "founded_year": 2010,
        "industry": "火箭配送自营电商平台、酷澎生鲜与智能履约物流",
        "revenue_m": "34,534"
    },
    {
        "rank": 480,
        "name_cn": "新希望控股集团有限公司",
        "name_en": "New Hope Group Co., Ltd.",
        "founder_en": "Liu Yonghao, Liu Yongyan, Chen Yuxin, Liu Yongxing",
        "founder_cn": "刘永好、刘永言、陈育新、刘永行 (四兄弟创立)",
        "country": "🇨🇳 中国",
        "hq": "四川 成都",
        "founded_year": 1982,
        "industry": "现代化农牧饲料、冷鲜生猪禽肉与民生金融投资",
        "revenue_m": "34,462"
    },
    {
        "rank": 481,
        "name_cn": "慧与公司",
        "name_en": "Hewlett Packard Enterprise (HPE)",
        "founder_en": "Hewlett-Packard Company Enterprise Spinoff",
        "founder_cn": "惠普公司企业级基础设施业务分拆设立",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 斯普林",
        "founded_year": 2015,
        "industry": "企业服务器、混合云边缘智算与克雷(Cray)超算集群",
        "revenue_m": "34,296"
    },
    {
        "rank": 482,
        "name_cn": "D.R. Horton公司",
        "name_en": "D.R. Horton, Inc.",
        "founder_en": "Donald R. Horton",
        "founder_cn": "唐纳德·R·霍顿",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 阿灵顿",
        "founded_year": 1978,
        "industry": "独栋平价刚需住宅建造商与社区规划开发",
        "revenue_m": "34,250"
    },
    {
        "rank": 483,
        "name_cn": "怡和集团",
        "name_en": "Jardine Matheson Holdings Limited",
        "founder_en": "William Jardine, James Matheson",
        "founder_cn": "威廉·渣甸、詹姆士·马地臣",
        "country": "🇭🇰 中国香港",
        "hq": "香港",
        "founded_year": 1832,
        "industry": "多元化洋行控股 (香港置地/文华东方酒店/怡和汽车/牛奶国际)",
        "revenue_m": "34,217"
    },
    {
        "rank": 484,
        "name_cn": "北京建龙重工集团有限公司",
        "name_en": "Beijing Jianlong Heavy Industry Group Co., Ltd.",
        "founder_en": "Zhang Zhixiang",
        "founder_cn": "张志祥",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1999,
        "industry": "特钢新材料、重型造船工程与海外铁铜矿山开发",
        "revenue_m": "34,202"
    },
    {
        "rank": 485,
        "name_cn": "莱纳公司",
        "name_en": "Lennar Corporation",
        "founder_en": "Gene Fisher, Arnold Rosen",
        "founder_cn": "吉恩·费希尔、阿诺德·罗森",
        "country": "🇺🇸 美国",
        "hq": "佛罗里达州 迈阿密",
        "founded_year": 1954,
        "industry": "独栋及多户住宅建造、智能家居社区与抵押金融",
        "revenue_m": "34,187"
    },
    {
        "rank": 486,
        "name_cn": "俄罗斯天然气工业银行‌",
        "name_en": "Gazprombank (Joint Stock Company)",
        "founder_en": "Gazprom PJSC",
        "founder_cn": "俄罗斯天然气工业股份公司发起设立",
        "country": "🇷🇺 俄罗斯",
        "hq": "莫斯科",
        "founded_year": 1990,
        "industry": "国家能源工业项目清算融资与大型跨国企业金融",
        "revenue_m": "34,162"
    },
    {
        "rank": 487,
        "name_cn": "美国PNC金融服务集团",
        "name_en": "The PNC Financial Services Group, Inc.",
        "founder_en": "Pittsburgh National & Provident National Merger",
        "founder_cn": "匹兹堡国家银行与天佑国家银行合并组建",
        "country": "🇺🇸 美国",
        "hq": "宾夕法尼亚州 匹兹堡",
        "founded_year": 1852,
        "industry": "区域性全能商业银行、企业贷款与财富传承管理",
        "revenue_m": "33,996"
    },
    {
        "rank": 488,
        "name_cn": "林德集团",
        "name_en": "Linde plc",
        "founder_en": "Carl von Linde (Praxair Merger)",
        "founder_cn": "卡尔·冯·林德 (林德与普莱克斯合并)",
        "country": "🇮🇪 爱尔兰 / 🇬🇧 英国",
        "hq": "都柏林 / 吉尔福德",
        "founded_year": 1879,
        "industry": "高纯工业气体 (氧氮氩氦)、低温空分工程与绿氢制备",
        "revenue_m": "33,986"
    },
    {
        "rank": 489,
        "name_cn": "爱信",
        "name_en": "Aisin Corporation",
        "founder_en": "Kiichiro Toyoda (Aichi Kogyo & Shinkawa Kogyo Merger)",
        "founder_cn": "丰田喜一郎发起 (爱知工业与新川工业合并)",
        "country": "🇯🇵 日本",
        "hq": "爱知县 刈谷市",
        "founded_year": 1949,
        "industry": "汽车自动变速箱 (AT)、e-Axle电动驱动轴与制动底盘",
        "revenue_m": "33,958"
    },
    {
        "rank": 490,
        "name_cn": "住友电工",
        "name_en": "Sumitomo Electric Industries, Ltd.",
        "founder_en": "Sumitomo Copper Rolling Works Spinoff",
        "founder_cn": "住友伸铜所电线制造部门独立分立",
        "country": "🇯🇵 日本",
        "hq": "大阪",
        "founded_year": 1897,
        "industry": "汽车高低压线束、通信光纤光缆与化合物半导体材料",
        "revenue_m": "33,907"
    },
    {
        "rank": 491,
        "name_cn": "鞍钢集团有限公司",
        "name_en": "Ansteel Group Corporation Limited",
        "founder_en": "Central People's Government of China (Anshan & Benxi Merger)",
        "founder_cn": "中央人民政府 (鞍钢、本钢、攀钢联合重组)",
        "country": "🇨🇳 中国",
        "hq": "辽宁 鞍山",
        "founded_year": 1948,
        "industry": "汽车特种用钢、重型铁轨材料与战略钒钛资源开发",
        "revenue_m": "33,894"
    },
    {
        "rank": 492,
        "name_cn": "Vibra Energia公司",
        "name_en": "Vibra Energia S.A. (Petrobras Distribuidora)",
        "founder_en": "Petrobras Downstream Distribution Spinoff",
        "founder_cn": "巴西国家石油公司下游零售分销私有化分立",
        "country": "🇧🇷 巴西",
        "hq": "里约热内卢",
        "founded_year": 1971,
        "industry": "巴西大型成品油批发零售、特种润滑油与加油站网络 (BR)",
        "revenue_m": "33,856"
    },
    {
        "rank": 493,
        "name_cn": "英美烟草集团",
        "name_en": "British American Tobacco p.l.c. (BAT)",
        "founder_en": "Imperial Tobacco & American Tobacco Joint Venture",
        "founder_cn": "帝国烟草与美国烟草合资设立",
        "country": "🇬🇧 英国",
        "hq": "伦敦",
        "founded_year": 1902,
        "industry": "传统烟草卷烟与雾化电子烟/无烟口含减害产品 (Vuse/Glo)",
        "revenue_m": "33,731"
    },
    {
        "rank": 494,
        "name_cn": "康明斯公司",
        "name_en": "Cummins Inc.",
        "founder_en": "Clessie Cummins, William Glanton Irwin",
        "founder_cn": "克莱西·康明斯、威廉·G·欧文",
        "country": "🇺🇸 美国",
        "hq": "印第安纳州 哥伦布",
        "founded_year": 1919,
        "industry": "商用重型柴油天然气发动机、发电机组与氢燃料电池",
        "revenue_m": "33,670"
    },
    {
        "rank": 495,
        "name_cn": "Oneok公司",
        "name_en": "ONEOK, Inc.",
        "founder_en": "Dennis T. Flynn, Charles B. Ames (Oklahoma Natural Gas)",
        "founder_cn": "丹尼斯·T·弗林、查尔斯·B·艾姆斯 (俄克拉荷马天然气)",
        "country": "🇺🇸 美国",
        "hq": "俄克拉荷马州 塔尔萨",
        "founded_year": 1906,
        "industry": "天然气液体(NGL)长输管道输配、分馏加工与仓储中游",
        "revenue_m": "33,629"
    },
    {
        "rank": 496,
        "name_cn": "美敦力公司",
        "name_en": "Medtronic plc",
        "founder_en": "Earl Bakken, Palmer Hermundslie",
        "founder_cn": "厄尔·巴肯、帕尔默·赫蒙德斯利",
        "country": "🇮🇪 爱尔兰 / 🇺🇸 美国",
        "hq": "都柏林 / 明尼阿波利斯",
        "founded_year": 1949,
        "industry": "心脏起搏器、神经调控刺激器与微创外科手术机器人",
        "revenue_m": "33,537"
    },
    {
        "rank": 497,
        "name_cn": "广西投资集团有限公司",
        "name_en": "Guangxi Investment Group Co., Ltd.",
        "founder_en": "Guangxi Zhuang Autonomous Region People's Government",
        "founder_cn": "广西壮族自治区人民政府 (自治区建设投资开发公司设立)",
        "country": "🇨🇳 中国",
        "hq": "广西 南宁",
        "founded_year": 1988,
        "industry": "生态铝全产业链、清洁能源发电与现代金融服务",
        "revenue_m": "33,399"
    },
    {
        "rank": 498,
        "name_cn": "大金集团",
        "name_en": "Daikin Industries, Ltd.",
        "founder_en": "Akira Yamada (Osaka Metal Industries)",
        "founder_cn": "山田晃 (大阪金属工业所创立)",
        "country": "🇯🇵 日本",
        "hq": "大阪",
        "founded_year": 1924,
        "industry": "变频多联商用家用中央空调与氟化工高新材料",
        "revenue_m": "33,276"
    },
    {
        "rank": 499,
        "name_cn": "LG化学公司",
        "name_en": "LG Chem, Ltd.",
        "founder_en": "Koo In-hwoi (Lucky Chemical Industrial)",
        "founder_cn": "具仁会 (乐喜化学工业社演变)",
        "country": "🇰🇷 韩国",
        "hq": "首尔",
        "founded_year": 1947,
        "industry": "石化基础材料、ABS工程塑料与高端电池材料",
        "revenue_m": "33,190"
    },
    {
        "rank": 500,
        "name_cn": "贝宝公司",
        "name_en": "PayPal Holdings, Inc.",
        "founder_en": "Peter Thiel, Max Levchin, Elon Musk, Luke Nosek, Ken Howery",
        "founder_cn": "彼得·蒂尔、马克斯·列夫琴、埃隆·马斯克、卢克·诺塞克、肯·豪厄里",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 圣何塞",
        "founded_year": 1998,
        "industry": "全球数字在线支付、跨境电子钱包与金融结算科技",
        "revenue_m": "33,172"
    }
]
