# -*- coding: utf-8 -*-
"""Data part 3: Companies 201 to 300"""

DATA_PART3 = [
    {
        "rank": 201,
        "name_cn": "浙江恒逸集团有限公司",
        "name_en": "Zhejiang Hengyi Group Co., Ltd.",
        "founder_en": "Qiu Jianlin",
        "founder_cn": "邱建林",
        "country": "🇨🇳 中国",
        "hq": "浙江 杭州",
        "founded_year": 1994,
        "industry": "文莱炼化一体化与化纤聚酯制造",
        "revenue_m": "69,781"
    },
    {
        "rank": 202,
        "name_cn": "苏黎世保险集团",
        "name_en": "Zurich Insurance Group Ltd",
        "founder_en": "Schweiz Marine Insurance Co. founders",
        "founder_cn": "瑞士水运保险公司创办人联合设立",
        "country": "🇨🇭 瑞士",
        "hq": "苏黎世",
        "founded_year": 1872,
        "industry": "全球财产保险、人寿保险与商业风险保障",
        "revenue_m": "69,780"
    },
    {
        "rank": 203,
        "name_cn": "KOC集团",
        "name_en": "Koç Holding A.Ş.",
        "founder_en": "Vehbi Koç",
        "founder_cn": "韦赫比·考奇",
        "country": "🇹🇷 土耳其",
        "hq": "伊斯坦布尔",
        "founded_year": 1926,
        "industry": "汽车制造、家用电器 (Beko)、能源与金融",
        "revenue_m": "69,742"
    },
    {
        "rank": 204,
        "name_cn": "埃森哲",
        "name_en": "Accenture plc",
        "founder_en": "Arthur Andersen Consulting Division Spinoff",
        "founder_cn": "安达信咨询业务独立分拆组建",
        "country": "🇮🇪 爱尔兰",
        "hq": "都柏林",
        "founded_year": 1989,
        "industry": "管理咨询、数字化转型、企业AI与云服务",
        "revenue_m": "69,673"
    },
    {
        "rank": 205,
        "name_cn": "Seven & I 控股公司",
        "name_en": "Seven & i Holdings Co., Ltd.",
        "founder_en": "Masatoshi Ito (Ito-Yokado & 7-Eleven)",
        "founder_cn": "伊藤雅俊 (伊藤洋华堂与7-Eleven整合)",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1920,
        "industry": "全球连锁便利店 (7-Eleven) 与综合商超",
        "revenue_m": "69,577"
    },
    {
        "rank": 206,
        "name_cn": "第一资本金融公司",
        "name_en": "Capital One Financial Corporation",
        "founder_en": "Richard Fairbank, Nigel Morris",
        "founder_cn": "理查德·费尔班克、奈杰尔·莫里斯",
        "country": "🇺🇸 美国",
        "hq": "弗吉尼亚州 麦克莱恩",
        "founded_year": 1994,
        "industry": "消费信贷、信用卡发行与数字商业银行",
        "revenue_m": "69,252"
    },
    {
        "rank": 207,
        "name_cn": "中国铝业集团有限公司",
        "name_en": "Aluminum Corporation of China (Chinalco)",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (国有骨干有色金属企业组建)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 2001,
        "industry": "铝土矿开采、氧化铝冶炼与轻量化铝材",
        "revenue_m": "68,909"
    },
    {
        "rank": 208,
        "name_cn": "印度石油天然气公司",
        "name_en": "Oil and Natural Gas Corporation (ONGC)",
        "founder_en": "Government of India",
        "founder_cn": "印度中央政府",
        "country": "🇮🇳 印度",
        "hq": "新德里",
        "founded_year": 1956,
        "industry": "上游油气资源勘探开发与深海石油工程",
        "revenue_m": "68,887"
    },
    {
        "rank": 209,
        "name_cn": "Uniper公司",
        "name_en": "Uniper SE",
        "founder_en": "E.ON Conventional Energy Spinoff",
        "founder_cn": "意昂集团传统化石能源业务分拆设立",
        "country": "🇩🇪 德国",
        "hq": "杜塞尔多夫",
        "founded_year": 2016,
        "industry": "天然气进口输配、公用事业发电与储能",
        "revenue_m": "68,752"
    },
    {
        "rank": 210,
        "name_cn": "SK海力士公司",
        "name_en": "SK Hynix Inc.",
        "founder_en": "Hyundai Electronics / Acquired by SK Group",
        "founder_cn": "现代电子半导体部门演变 / SK集团收购",
        "country": "🇰🇷 韩国",
        "hq": "京畿道 利川市",
        "founded_year": 1983,
        "industry": "高带宽内存(HBM)、DRAM与NAND闪存芯片",
        "revenue_m": "68,338"
    },
    {
        "rank": 211,
        "name_cn": "广达电脑公司",
        "name_en": "Quanta Computer Inc.",
        "founder_en": "Barry Lam, C.C. Leung",
        "founder_cn": "林百里、梁次震",
        "country": "🇹🇼 中国台湾",
        "hq": "桃园市",
        "founded_year": 1988,
        "industry": "笔记本电脑制造与云计算AI服务器代工",
        "revenue_m": "68,164"
    },
    {
        "rank": 212,
        "name_cn": "中国保利集团有限公司",
        "name_en": "China Poly Group Corporation",
        "founder_en": "PLA General Staff Dept & CITIC",
        "founder_cn": "总参装备部与中信公司联合创立",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1992,
        "industry": "国际贸易、房地产开发、文化艺术与民爆",
        "revenue_m": "68,121"
    },
    {
        "rank": 213,
        "name_cn": "金川集团股份有限公司",
        "name_en": "Jinchuan Group Co., Ltd.",
        "founder_en": "State Planning Commission of China",
        "founder_cn": "国家计委设立 (甘肃金昌白家嘴镍矿基地)",
        "country": "🇨🇳 中国",
        "hq": "甘肃 金昌",
        "founded_year": 1959,
        "industry": "镍、钴、铜及铂族贵金属采选冶炼",
        "revenue_m": "68,116"
    },
    {
        "rank": 214,
        "name_cn": "韩国电力公司",
        "name_en": "Korea Electric Power Corporation (KEPCO)",
        "founder_en": "Government of South Korea (Hanseong Electric 1898)",
        "founder_cn": "大韩民国政府法令整合设立 (前身汉城电气)",
        "country": "🇰🇷 韩国",
        "hq": "全罗南道 罗州市",
        "founded_year": 1898,
        "industry": "国有电力发电输配与核电出口建设",
        "revenue_m": "67,931"
    },
    {
        "rank": 215,
        "name_cn": "好事达",
        "name_en": "The Allstate Corporation",
        "founder_en": "Robert E. Wood (Sears, Roebuck & Co.)",
        "founder_cn": "罗伯特·E·伍德 (西尔斯百货发起设立)",
        "country": "🇺🇸 美国",
        "hq": "伊利诺伊州 诺斯布鲁克",
        "founded_year": 1931,
        "industry": "个人车险、房屋财产险与人寿保险",
        "revenue_m": "67,685"
    },
    {
        "rank": 216,
        "name_cn": "卡特彼勒",
        "name_en": "Caterpillar Inc.",
        "founder_en": "Benjamin Holt, C. L. Best",
        "founder_cn": "本杰明·霍尔特、C.L. 贝斯特",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 欧文",
        "founded_year": 1925,
        "industry": "建筑工程机械、矿山重型卡车与柴油发动机",
        "revenue_m": "67,589"
    },
    {
        "rank": 217,
        "name_cn": "国际商业机器公司",
        "name_en": "International Business Machines Corp. (IBM)",
        "founder_en": "Charles Ranlett Flint, Thomas J. Watson",
        "founder_cn": "查尔斯·兰莱特·弗林特、托马斯·J·沃森",
        "country": "🇺🇸 美国",
        "hq": "纽约州 阿蒙克",
        "founded_year": 1911,
        "industry": "企业混合云 (Red Hat)、企业AI (watsonx) 与IT咨询",
        "revenue_m": "67,535"
    },
    {
        "rank": 218,
        "name_cn": "意大利忠利保险公司",
        "name_en": "Assicurazioni Generali S.p.A.",
        "founder_en": "Giuseppe Lazzaro Morpurgo",
        "founder_cn": "朱塞佩·莫尔普戈",
        "country": "🇮🇹 意大利",
        "hq": "的里雅斯特",
        "founded_year": 1831,
        "industry": "欧洲综合人寿保险、财险与全球资产管理",
        "revenue_m": "67,321"
    },
    {
        "rank": 219,
        "name_cn": "日本制铁公司",
        "name_en": "Nippon Steel Corporation",
        "founder_en": "Yawata Iron & Steel and Fuji Iron & Steel Merger",
        "founder_cn": "八幡制铁与富士制铁合并重组",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1970,
        "industry": "高品质特种钢板、车用超高强钢与无缝管材",
        "revenue_m": "66,772"
    },
    {
        "rank": 220,
        "name_cn": "巴西银行",
        "name_en": "Banco do Brasil S.A.",
        "founder_en": "King John VI of Portugal",
        "founder_cn": "葡萄牙国王若昂六世皇家法令设立",
        "country": "🇧🇷 巴西",
        "hq": "巴西利亚",
        "founded_year": 1808,
        "industry": "国有商业银行、农业贷款与拉美综合金融",
        "revenue_m": "66,770"
    },
    {
        "rank": 221,
        "name_cn": "招商银行股份有限公司",
        "name_en": "China Merchants Bank (CMB)",
        "founder_en": "Yuan Geng (China Merchants Group)",
        "founder_cn": "袁庚 (招商局蛇口工业区创办)",
        "country": "🇨🇳 中国",
        "hq": "广东 深圳",
        "founded_year": 1987,
        "industry": "零售商业银行、信用卡与高净值私人银行",
        "revenue_m": "66,303"
    },
    {
        "rank": 222,
        "name_cn": "联合利华",
        "name_en": "Unilever PLC",
        "founder_en": "William Lever, James Darcy Lever, Anton Jurgens",
        "founder_cn": "威廉·利华、詹姆斯·利华、安东·尤尔根斯",
        "country": "🇬🇧 英国",
        "hq": "伦敦",
        "founded_year": 1929,
        "industry": "个人护理洗发沐浴、家庭清洁与包装调味食品",
        "revenue_m": "65,638"
    },
    {
        "rank": 223,
        "name_cn": "雷诺",
        "name_en": "Renault S.A.",
        "founder_en": "Louis Renault, Marcel Renault, Fernand Renault",
        "founder_cn": "路易·雷诺、马塞尔·雷诺、费尔南·雷诺",
        "country": "🇫🇷 法国",
        "hq": "布洛涅-比扬古",
        "founded_year": 1899,
        "industry": "乘用车制造、纯电动车型(Ampere)与轻型商用车",
        "revenue_m": "65,331"
    },
    {
        "rank": 224,
        "name_cn": "美国礼来公司",
        "name_en": "Eli Lilly and Company",
        "founder_en": "Eli Lilly",
        "founder_cn": "伊莱·礼来",
        "country": "🇺🇸 美国",
        "hq": "印第安纳州 印第安纳波利斯",
        "founded_year": 1876,
        "industry": "减重降糖GLP-1生物药、阿尔茨海默病与肿瘤药",
        "revenue_m": "65,179"
    },
    {
        "rank": 225,
        "name_cn": "默沙东",
        "name_en": "Merck & Co., Inc. (MSD)",
        "founder_en": "George Merck",
        "founder_cn": "乔治·默克",
        "country": "🇺🇸 美国",
        "hq": "新泽西州 罗威",
        "founded_year": 1891,
        "industry": "抗肿瘤PD-1免疫药物(Keytruda)与HPV疫苗",
        "revenue_m": "65,011"
    },
    {
        "rank": 226,
        "name_cn": "美国全国保险公司",
        "name_en": "Nationwide Mutual Insurance Company",
        "founder_en": "Ohio Farm Bureau Federation (Farm Bureau Mutual)",
        "founder_cn": "俄亥俄州农业互助联合会创办",
        "country": "🇺🇸 美国",
        "hq": "俄亥俄州 哥伦布",
        "founded_year": 1926,
        "industry": "车险财产险、农业综合保险与退休年金",
        "revenue_m": "64,930"
    },
    {
        "rank": 227,
        "name_cn": "厦门象屿集团有限公司",
        "name_en": "Xiamen Xiangyu Group Corporation",
        "founder_en": "Xiamen Municipal People's Government",
        "founder_cn": "厦门市人民政府 (象屿保税区设立组建)",
        "country": "🇨🇳 中国",
        "hq": "福建 厦门",
        "founded_year": 1995,
        "industry": "大宗商品供应链综合服务、物流仓储与造船",
        "revenue_m": "64,537"
    },
    {
        "rank": 228,
        "name_cn": "引能仕控股株式会社",
        "name_en": "ENEOS Holdings, Inc.",
        "founder_en": "Nippon Oil & Japan Energy Merger",
        "founder_cn": "日本石油与日本能源合并组建",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1888,
        "industry": "石油精炼加工、有色金属冶炼与氢能源开发",
        "revenue_m": "64,342"
    },
    {
        "rank": 229,
        "name_cn": "法国布伊格集团",
        "name_en": "Bouygues S.A.",
        "founder_en": "Francis Bouygues",
        "founder_cn": "弗朗西斯·布伊格",
        "country": "🇫🇷 法国",
        "hq": "巴黎",
        "founded_year": 1952,
        "industry": "建筑与土木工程、房地产、TF1电视传媒与电信",
        "revenue_m": "64,192"
    },
    {
        "rank": 230,
        "name_cn": "博通公司",
        "name_en": "Broadcom Inc.",
        "founder_en": "Henry Samueli, Henry Nicholas / Hock Tan (Avago merger)",
        "founder_cn": "亨利·萨缪利、亨利·尼古拉斯 / 陈福阳 (并购重组)",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 帕洛阿尔托",
        "founded_year": 1961,
        "industry": "网络交换ASIC芯片、无线射频与VMware云软件",
        "revenue_m": "63,887"
    },
    {
        "rank": 231,
        "name_cn": "美的集团股份有限公司",
        "name_en": "Midea Group Co., Ltd.",
        "founder_en": "He Xiangjian",
        "founder_cn": "何享健",
        "country": "🇨🇳 中国",
        "hq": "广东 佛山",
        "founded_year": 1968,
        "industry": "智能白电、工业机器人 (库卡) 与暖通楼宇科技",
        "revenue_m": "63,790"
    },
    {
        "rank": 232,
        "name_cn": "小米集团",
        "name_en": "Xiaomi Corporation",
        "founder_en": "Lei Jun, Lin Bin, Wanqiang Li, and co-founders",
        "founder_cn": "雷军、林斌、黎万强等联合创始人",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 2010,
        "industry": "智能手机、AIoT智能硬件生态与智能纯电汽车",
        "revenue_m": "63,621"
    },
    {
        "rank": 233,
        "name_cn": "德国艾德卡公司",
        "name_en": "Edeka Group (Edeka Zentrale)",
        "founder_en": "Einkaufsgenossenschaft der Kolonialwarenhändler",
        "founder_cn": "柏林殖民地商品零售采购合作社",
        "country": "🇩🇪 德国",
        "hq": "汉堡",
        "founded_year": 1898,
        "industry": "生鲜超级市场与食品供应链合作社",
        "revenue_m": "63,534"
    },
    {
        "rank": 234,
        "name_cn": "中国能源建设集团有限公司",
        "name_en": "China Energy Engineering Group (Energy China)",
        "founder_en": "State Council of China (Gezhouba & Power Planning)",
        "founder_cn": "国务院 (葛洲坝集团及电力设计院重组设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 2011,
        "industry": "火电水电核电勘测设计施工与特高压电网",
        "revenue_m": "63,442"
    },
    {
        "rank": 235,
        "name_cn": "达美航空",
        "name_en": "Delta Air Lines, Inc.",
        "founder_en": "C. E. Woolman (Huff Daland Dusters)",
        "founder_cn": "科利特·E·乌尔曼 (哈夫达兰德农喷航空演变)",
        "country": "🇺🇸 美国",
        "hq": "佐治亚州 亚特兰大",
        "founded_year": 1925,
        "industry": "全球大型枢纽民航客运与国际航线网络",
        "revenue_m": "63,364"
    },
    {
        "rank": 236,
        "name_cn": "大众超级市场公司",
        "name_en": "Publix Super Markets, Inc.",
        "founder_en": "George W. Jenkins",
        "founder_cn": "乔治·W·詹金斯",
        "country": "🇺🇸 美国",
        "hq": "佛罗里达州 莱克兰",
        "founded_year": 1930,
        "industry": "全员工持股制连锁生鲜食品超市",
        "revenue_m": "63,209"
    },
    {
        "rank": 237,
        "name_cn": "中国远洋海运集团有限公司",
        "name_en": "China COSCO Shipping Corporation Limited",
        "founder_en": "State Council of China (COSCO & China Shipping Merger)",
        "founder_cn": "国务院 (中远集团与中海集团联合重组设立)",
        "country": "🇨🇳 中国",
        "hq": "上海",
        "founded_year": 2016,
        "industry": "集装箱干线班轮、散货运输与全球港口码头",
        "revenue_m": "63,202"
    },
    {
        "rank": 238,
        "name_cn": "LG电子",
        "name_en": "LG Electronics Inc.",
        "founder_en": "Koo In-hwoi (GoldStar)",
        "founder_cn": "具仁会 (金星社前身)",
        "country": "🇰🇷 韩国",
        "hq": "首尔",
        "founded_year": 1958,
        "industry": "智能家电、OLED电视显示与车载座舱电子",
        "revenue_m": "62,748"
    },
    {
        "rank": 239,
        "name_cn": "卢克石油公司",
        "name_en": "Lukoil PJSC",
        "founder_en": "Vagit Alekperov (Langepas, Uray & Kogalym)",
        "founder_cn": "瓦吉特·阿列克佩罗夫 (西伯利亚三油田整合)",
        "country": "🇷🇺 俄罗斯",
        "hq": "莫斯科",
        "founded_year": 1991,
        "industry": "民营石油天然气勘探开采、炼油与加油站",
        "revenue_m": "62,644"
    },
    {
        "rank": 240,
        "name_cn": "辉瑞制药有限公司",
        "name_en": "Pfizer Inc.",
        "founder_en": "Charles Pfizer, Charles F. Erhart",
        "founder_cn": "查尔斯·辉瑞、查尔斯·埃尔哈特",
        "country": "🇺🇸 美国",
        "hq": "纽约州 纽约",
        "founded_year": 1849,
        "industry": "创新生物制药、mRNA疫苗与抗肿瘤新药研发",
        "revenue_m": "62,579"
    },
    {
        "rank": 241,
        "name_cn": "TD Synnex公司",
        "name_en": "TD SYNNEX Corporation",
        "founder_en": "Robert T. Huang (Synnex) & Tech Data Merger",
        "founder_cn": "黄德慈 (新聚思) 与泰科数据合并设立",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 弗里蒙特",
        "founded_year": 1980,
        "industry": "IT产品与企业云计算软硬件分销",
        "revenue_m": "62,508"
    },
    {
        "rank": 242,
        "name_cn": "马来西亚国家石油公司",
        "name_en": "Petroliam Nasional Berhad (Petronas)",
        "founder_en": "Tun Abdul Razak (Government of Malaysia Act)",
        "founder_cn": "马来西亚总理拉扎克法令特许设立",
        "country": "🇲🇾 马来西亚",
        "hq": "吉隆坡 (双子塔)",
        "founded_year": 1974,
        "industry": "上游油气开采、LNG液化天然气与炼油化工",
        "revenue_m": "62,173"
    },
    {
        "rank": 243,
        "name_cn": "康菲石油公司",
        "name_en": "ConocoPhillips",
        "founder_en": "Isaac E. Blake (Conoco) & Frank Phillips (Phillips)",
        "founder_cn": "艾萨克·布莱克与法兰克·菲利普斯合并",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 休斯敦",
        "founded_year": 1875,
        "industry": "独立上游石油天然气勘探开发 (E&P)",
        "revenue_m": "61,548"
    },
    {
        "rank": 244,
        "name_cn": "Galaxy Digital公司",
        "name_en": "Galaxy Digital Holdings Ltd.",
        "founder_en": "Michael Novogratz",
        "founder_cn": "迈克尔·诺沃格拉茨",
        "country": "🇺🇸 美国",
        "hq": "纽约州 纽约",
        "founded_year": 2018,
        "industry": "数字资产金融、加密货币机构经纪与Web3投资",
        "revenue_m": "61,356"
    },
    {
        "rank": 245,
        "name_cn": "安赛乐米塔尔",
        "name_en": "ArcelorMittal S.A.",
        "founder_en": "Lakshmi Mittal (Mittal Steel & Arcelor Merger)",
        "founder_cn": "拉克希米·米塔尔 (米塔尔钢铁收购阿赛洛)",
        "country": "🇱🇺 卢森堡",
        "hq": "卢森堡市",
        "founded_year": 2006,
        "industry": "跨国钢铁制造、汽车高强特钢与铁矿石采矿",
        "revenue_m": "61,352"
    },
    {
        "rank": 246,
        "name_cn": "艾伯维",
        "name_en": "AbbVie Inc.",
        "founder_en": "Abbott Laboratories BioPharma Spinoff",
        "founder_cn": "雅培制药生物制药部门分拆独立设立",
        "country": "🇺🇸 美国",
        "hq": "伊利诺伊州 北芝加哥",
        "founded_year": 2013,
        "industry": "自身免疫病制药(修美乐/Skyrizi)与血液肿瘤药",
        "revenue_m": "61,160"
    },
    {
        "rank": 247,
        "name_cn": "保德信金融集团",
        "name_en": "Prudential Financial, Inc.",
        "founder_en": "John F. Dryden (Widows & Orphans Friendly Society)",
        "founder_cn": "约翰·F·德莱顿 (寡妇与孤儿友爱会前身)",
        "country": "🇺🇸 美国",
        "hq": "新泽西州 纽瓦克",
        "founded_year": 1875,
        "industry": "人寿保险、年金与PGIM全球机构资产管理",
        "revenue_m": "60,774"
    },
    {
        "rank": 248,
        "name_cn": "中国太平洋保险(集团)股份有限公司",
        "name_en": "China Pacific Insurance (Group) Co., Ltd. (CPIC)",
        "founder_en": "Bank of Communications Promotion",
        "founder_cn": "交通银行发起组建 (全国性综合股份制险企)",
        "country": "🇨🇳 中国",
        "hq": "上海",
        "founded_year": 1991,
        "industry": "人寿保险、财产保险与大健康养老管理",
        "revenue_m": "60,542"
    },
    {
        "rank": 249,
        "name_cn": "陕西煤业化工集团有限责任公司",
        "name_en": "Shaanxi Coal and Chemical Industry Group",
        "founder_en": "Shaanxi Provincial People's Government",
        "founder_cn": "陕西省人民政府 (省属煤炭企事业单位组建)",
        "country": "🇨🇳 中国",
        "hq": "陕西 西安",
        "founded_year": 2004,
        "industry": "优质动力煤开采、煤炭清洁转化与现代煤化工",
        "revenue_m": "60,538"
    },
    {
        "rank": 250,
        "name_cn": "巴西布拉德斯科银行",
        "name_en": "Banco Bradesco S.A.",
        "founder_en": "Amador Aguiar",
        "founder_cn": "阿马多尔·阿吉亚尔",
        "country": "🇧🇷 巴西",
        "hq": "奥萨斯库",
        "founded_year": 1943,
        "industry": "大型民营商业银行、零售网点与汽车金融",
        "revenue_m": "60,522"
    },
    {
        "rank": 251,
        "name_cn": "TJX公司",
        "name_en": "The TJX Companies, Inc.",
        "founder_en": "Bernard Cammarata",
        "founder_cn": "伯纳德·卡马拉塔",
        "country": "🇺🇸 美国",
        "hq": "马萨诸塞州 弗雷明汉",
        "founded_year": 1976,
        "industry": "名牌服饰与家居折扣连锁百货 (T.J. Maxx/Marshalls)",
        "revenue_m": "60,372"
    },
    {
        "rank": 252,
        "name_cn": "厦门国贸控股集团有限公司",
        "name_en": "ITG Holding Group Co., Ltd.",
        "founder_en": "Xiamen Municipal People's Government",
        "founder_cn": "厦门市人民政府 (特区对外贸易机构演变)",
        "country": "🇨🇳 中国",
        "hq": "福建 厦门",
        "founded_year": 1980,
        "industry": "大宗商品供应链运营、高端制造与金融服务",
        "revenue_m": "60,296"
    },
    {
        "rank": 253,
        "name_cn": "日本瑞穗金融集团",
        "name_en": "Mizuho Financial Group, Inc.",
        "founder_en": "DKB, Fuji Bank & IBJ Merger",
        "founder_cn": "第一劝业银行、富士银行与日本兴业银行合并",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 2000,
        "industry": "跨国商业银行、大型企业辛迪加贷款与投行",
        "revenue_m": "60,284"
    },
    {
        "rank": 254,
        "name_cn": "青山控股集团有限公司",
        "name_en": "Tsingshan Holding Group Co., Ltd.",
        "founder_en": "Xiang Guangda, Sun Jianfen",
        "founder_cn": "项光达、孙建芬",
        "country": "🇨🇳 中国",
        "hq": "浙江 温州",
        "founded_year": 1988,
        "industry": "全球不锈钢冶炼、印尼镍产业链与动力锂电",
        "revenue_m": "60,131"
    },
    {
        "rank": 255,
        "name_cn": "拼多多控股公司",
        "name_en": "PDD Holdings Inc.",
        "founder_en": "Colin Huang (Huang Zheng)",
        "founder_cn": "黄峥",
        "country": "🇨🇳 中国",
        "hq": "上海",
        "founded_year": 2015,
        "industry": "社交电商平台 (拼多多) 与全球跨境电商 (Temu)",
        "revenue_m": "60,081"
    },
    {
        "rank": 256,
        "name_cn": "Performance Food Group公司",
        "name_en": "Performance Food Group Company (PFG)",
        "founder_en": "James Capel (Pocahontas Foods)",
        "founder_cn": "詹姆斯·卡佩尔 (波卡洪塔斯食品前身)",
        "country": "🇺🇸 美国",
        "hq": "弗吉尼亚州 里士满",
        "founded_year": 1885,
        "industry": "餐饮食材冷链配送与连锁餐馆供应链",
        "revenue_m": "59,899"
    },
    {
        "rank": 257,
        "name_cn": "安达保险公司",
        "name_en": "Chubb Limited",
        "founder_en": "Thomas Caldecot Chubb, Percy Chubb (ACE Limited Merger)",
        "founder_cn": "托马斯·C·安达、珀西·安达 (ACE合并)",
        "country": "🇨🇭 瑞士",
        "hq": "苏黎世",
        "founded_year": 1882,
        "industry": "商业财产及责任险、超高净值私人财产险",
        "revenue_m": "59,402"
    },
    {
        "rank": 258,
        "name_cn": "百威英博",
        "name_en": "Anheuser-Busch InBev SA/NV (AB InBev)",
        "founder_en": "Den Hoorn Brewery & Anheuser-Busch/AmBev Merger",
        "founder_cn": "比利时时代啤酒与安海斯-布希/美洲饮料合并",
        "country": "🇧🇪 比利时",
        "hq": "鲁汶",
        "founded_year": 1366,
        "industry": "全球大型啤酒酿造 (百威/时代/科罗娜/福佳)",
        "revenue_m": "59,320"
    },
    {
        "rank": 259,
        "name_cn": "联合航空控股公司",
        "name_en": "United Airlines Holdings, Inc.",
        "founder_en": "Walter Varney, William Boeing (Boeing Transport)",
        "founder_cn": "沃尔特·瓦尼、威廉·波音 (波音航空运输演变)",
        "country": "🇺🇸 美国",
        "hq": "伊利诺伊州 芝加哥",
        "founded_year": 1926,
        "industry": "全球枢纽大型干线航空公司 (星空联盟发起成员)",
        "revenue_m": "59,070"
    },
    {
        "rank": 260,
        "name_cn": "宁德时代新能源科技股份有限公司",
        "name_en": "Contemporary Amperex Technology Co., Limited (CATL)",
        "founder_en": "Robin Zeng (Zeng Yuqun)",
        "founder_cn": "曾毓群",
        "country": "🇨🇳 中国",
        "hq": "福建 宁德",
        "founded_year": 2011,
        "industry": "动力电池 (麒麟/神行超充电池) 与储能系统",
        "revenue_m": "58,948"
    },
    {
        "rank": 261,
        "name_cn": "东京海上日动火灾保险公司",
        "name_en": "Tokio Marine Holdings, Inc.",
        "founder_en": "Eiichi Shibusawa (Tokio Marine Insurance)",
        "founder_cn": "涩泽荣一 (东京海上保险前身)",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1879,
        "industry": "财产海上火灾保险与跨国综合保险控股",
        "revenue_m": "58,869"
    },
    {
        "rank": 262,
        "name_cn": "阿斯利康",
        "name_en": "AstraZeneca PLC",
        "founder_en": "Astra AB & Zeneca Group Merger",
        "founder_cn": "瑞典阿斯特拉与英国捷利康合并",
        "country": "🇬🇧 英国",
        "hq": "剑桥",
        "founded_year": 1999,
        "industry": "抗肿瘤靶向药 (泰瑞沙/安可达) 与罕见病药物",
        "revenue_m": "58,739"
    },
    {
        "rank": 263,
        "name_cn": "力拓集团",
        "name_en": "Rio Tinto Group",
        "founder_en": "Hugh Matheson (Matheson & Co.)",
        "founder_cn": "休·马西森 (西班牙力拓矿山联合投资)",
        "country": "🇬🇧 英国 / 🇦🇺 澳大利亚",
        "hq": "伦敦 / 墨尔本",
        "founded_year": 1873,
        "industry": "皮尔巴拉高品质铁矿石、铝土矿与铜矿开采",
        "revenue_m": "57,638"
    },
    {
        "rank": 264,
        "name_cn": "法国国民互助信贷银行集团",
        "name_en": "Crédit Mutuel Group",
        "founder_en": "Raiffeisen Mutual Credit Movement in Alsace",
        "founder_cn": "阿尔萨斯莱夫艾森农村互助信贷运动设立",
        "country": "🇫🇷 法国",
        "hq": "斯特拉斯堡",
        "founded_year": 1882,
        "industry": "合作制互助商业银行与数字化保险服务",
        "revenue_m": "57,518"
    },
    {
        "rank": 265,
        "name_cn": "甲骨文公司",
        "name_en": "Oracle Corporation",
        "founder_en": "Larry Ellison, Bob Miner, Ed Oates",
        "founder_cn": "拉里·埃里森、鲍勃·迈纳、埃德·奥茨",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 奥斯汀",
        "founded_year": 1977,
        "industry": "企业级关系型数据库、ERP云应用与OCI智算中心",
        "revenue_m": "57,399"
    },
    {
        "rank": 266,
        "name_cn": "河钢集团有限公司",
        "name_en": "HBIS Group Co., Ltd.",
        "founder_en": "Hebei Provincial People's Government (Tangsteel & Hansteel Merger)",
        "founder_cn": "河北省人民政府 (唐钢与邯钢联合重组组建)",
        "country": "🇨🇳 中国",
        "hq": "河北 石家庄",
        "founded_year": 2008,
        "industry": "高端汽车家电用钢、氢冶金绿色低碳炼钢",
        "revenue_m": "57,304"
    },
    {
        "rank": 267,
        "name_cn": "诺华公司",
        "name_en": "Novartis AG",
        "founder_en": "Ciba-Geigy & Sandoz Laboratories Merger",
        "founder_cn": "汽巴-嘉基与山德士药厂合并组建",
        "country": "🇨🇭 瑞士",
        "hq": "巴塞尔",
        "founded_year": 1996,
        "industry": "创新生物制药、放射配体疗法(RLT)与CAR-T细胞疗法",
        "revenue_m": "56,674"
    },
    {
        "rank": 268,
        "name_cn": "思科公司",
        "name_en": "Cisco Systems, Inc.",
        "founder_en": "Leonard Bosack, Sandy Lerner",
        "founder_cn": "伦纳德·波萨克、桑蒂·勒纳",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 圣何塞",
        "founded_year": 1984,
        "industry": "企业级路由交换机、网络安全与数据中心互联",
        "revenue_m": "56,654"
    },
    {
        "rank": 269,
        "name_cn": "Talanx公司",
        "name_en": "Talanx AG",
        "founder_en": "Haftpflichtverband der Deutschen Industrie (HDI)",
        "founder_cn": "德国工业责任保险互助联合会创办",
        "country": "🇩🇪 德国",
        "hq": "汉诺威",
        "founded_year": 1903,
        "industry": "大型工业险、零售金融与汉诺威再保险 (Hannover Re)",
        "revenue_m": "56,646"
    },
    {
        "rank": 270,
        "name_cn": "西班牙ACS集团",
        "name_en": "Actividades de Construcción y Servicios, S.A. (ACS)",
        "founder_en": "Florentino Pérez",
        "founder_cn": "弗洛伦蒂诺·佩雷斯",
        "country": "🇪🇸 西班牙",
        "hq": "马德里",
        "founded_year": 1997,
        "industry": "全球大型工程总承包、收费公路特许与能源基建",
        "revenue_m": "56,224"
    },
    {
        "rank": 271,
        "name_cn": "国家电力投资集团有限公司",
        "name_en": "State Power Investment Corporation (SPIC)",
        "founder_en": "State Council of China (CPI & SNPTC Merger)",
        "founder_cn": "国务院 (中电投集团与国家核电联合重组)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 2015,
        "industry": "光伏与风电清洁能源、国和一号三代核电",
        "revenue_m": "56,221"
    },
    {
        "rank": 272,
        "name_cn": "HDFC银行",
        "name_en": "HDFC Bank Limited",
        "founder_en": "Hasmukhbhai Parekh (Housing Development Finance Corp.)",
        "founder_cn": "哈斯穆克·帕雷克 (印度住房开发金融分立)",
        "country": "🇮🇳 印度",
        "hq": "孟买",
        "founded_year": 1994,
        "industry": "私营商业银行、零售住房信贷与数字化金融",
        "revenue_m": "56,075"
    },
    {
        "rank": 273,
        "name_cn": "蒙特利尔银行",
        "name_en": "Bank of Montreal (BMO)",
        "founder_en": "John Richardson and group of 8 merchants",
        "founder_cn": "约翰·理查森等8位蒙特利尔商人联合设立",
        "country": "🇨🇦 加拿大",
        "hq": "多伦多 / 蒙特利尔",
        "founded_year": 1817,
        "industry": "跨国商业银行、财富管理与北美跨境资本市场",
        "revenue_m": "55,925"
    },
    {
        "rank": 274,
        "name_cn": "戴姆勒卡车控股股份公司",
        "name_en": "Daimler Truck Holding AG",
        "founder_en": "Daimler AG Commercial Vehicle Spinoff",
        "founder_cn": "戴姆勒集团商用车业务独立分拆上市",
        "country": "🇩🇪 德国",
        "hq": "莱茵菲尔登-埃希特丁根",
        "founded_year": 2021,
        "industry": "重型商用卡车 (梅赛德斯-奔驰/福莱纳) 与客车制造",
        "revenue_m": "55,704"
    },
    {
        "rank": 275,
        "name_cn": "X5集团",
        "name_en": "X5 Group (X5 Retail Group)",
        "founder_en": "Pyaterochka & Perekrestok Merger (Alfa Group)",
        "founder_cn": "五月花与十字路口超市合并 (阿尔法集团控股)",
        "country": "🇷🇺 俄罗斯",
        "hq": "莫斯科",
        "founded_year": 2006,
        "industry": "社区折扣便利店与大型食品零售超市",
        "revenue_m": "55,361"
    },
    {
        "rank": 276,
        "name_cn": "惠普公司",
        "name_en": "HP Inc.",
        "founder_en": "Bill Hewlett, David Packard",
        "founder_cn": "比尔·休利特、戴维·帕卡德",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 帕洛阿尔托",
        "founded_year": 1939,
        "industry": "个人电脑、笔记本、激光喷墨打印与3D打印方案",
        "revenue_m": "55,295"
    },
    {
        "rank": 277,
        "name_cn": "丸红株式会社",
        "name_en": "Marubeni Corporation",
        "founder_en": "Chubei Itoh (Itochu spun off)",
        "founder_cn": "伊藤忠兵卫 (伊藤忠分流设立)",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1858,
        "industry": "综合商社 (国际粮食贸易/农业投入品/海外电力)",
        "revenue_m": "54,846"
    },
    {
        "rank": 278,
        "name_cn": "特许通讯公司",
        "name_en": "Charter Communications, Inc.",
        "founder_en": "Jerald Kent, Barry Babcock, Howard Wood",
        "founder_cn": "杰拉尔德·肯特、巴里·巴布科克、霍华德·伍德",
        "country": "🇺🇸 美国",
        "hq": "康涅狄格州 斯坦福",
        "founded_year": 1993,
        "industry": "有线宽带、数字电视与移动网络 (Spectrum)",
        "revenue_m": "54,774"
    },
    {
        "rank": 279,
        "name_cn": "赛诺菲",
        "name_en": "Sanofi S.A.",
        "founder_en": "Elf Aquitaine Spinoff & Synthélabo Merger",
        "founder_cn": "埃尔夫阿奎坦制药部门与圣德拉堡合并",
        "country": "🇫🇷 法国",
        "hq": "巴黎",
        "founded_year": 1973,
        "industry": "创新免疫靶向制药 (达必妥) 与儿科流感疫苗",
        "revenue_m": "54,650"
    },
    {
        "rank": 280,
        "name_cn": "美国航空集团",
        "name_en": "American Airlines Group Inc.",
        "founder_en": "C. R. Smith (Aviation Corporation Merger)",
        "founder_cn": "C.R. 史密斯 (多家小航司整合联合组建)",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 沃斯堡",
        "founded_year": 1930,
        "industry": "跨国干线民航客运与寰宇一家(Oneworld)航网",
        "revenue_m": "54,633"
    },
    {
        "rank": 281,
        "name_cn": "中国联合网络通信股份有限公司",
        "name_en": "China United Network Communications Group (China Unicom)",
        "founder_en": "State Council of China (Unicom & Netcom Merger)",
        "founder_cn": "国务院 (中国联通与中国网通联合重组)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1994,
        "industry": "5G移动网络、千兆宽带、联通云与大数据算力",
        "revenue_m": "54,569"
    },
    {
        "rank": 282,
        "name_cn": "雷普索尔公司",
        "name_en": "Repsol S.A.",
        "founder_en": "Instituto Nacional de Hidrocarburos (INH)",
        "founder_cn": "西班牙国家碳氢化合物研究所改制设立",
        "country": "🇪🇸 西班牙",
        "hq": "马德里",
        "founded_year": 1987,
        "industry": "油气一体化勘探炼化与可再生低碳能源",
        "revenue_m": "54,534"
    },
    {
        "rank": 283,
        "name_cn": "泰森食品",
        "name_en": "Tyson Foods, Inc.",
        "founder_en": "John W. Tyson",
        "founder_cn": "约翰·W·泰森",
        "country": "🇺🇸 美国",
        "hq": "阿肯色州 斯普林代尔",
        "founded_year": 1935,
        "industry": "禽肉、牛肉与猪肉冷鲜深加工及预制食品",
        "revenue_m": "54,441"
    },
    {
        "rank": 284,
        "name_cn": "马士基集团",
        "name_en": "A.P. Møller – Mærsk A/S",
        "founder_en": "Arnold Peter Møller, Peter Mærsk Møller",
        "founder_cn": "阿诺德·彼得·默勒、彼得·马士基·默勒",
        "country": "🇩🇰 丹麦",
        "hq": "哥本哈根",
        "founded_year": 1904,
        "industry": "全球集装箱干线班轮运输与端到端智能供应链",
        "revenue_m": "53,988"
    },
    {
        "rank": 285,
        "name_cn": "中国华能集团有限公司",
        "name_en": "China Huaneng Group Co., Ltd.",
        "founder_en": "State Council of China",
        "founder_cn": "国务院 (华能开发公司深化改革设立)",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1985,
        "industry": "清洁化火电、大型水电与风电光伏新能源开发",
        "revenue_m": "53,840"
    },
    {
        "rank": 286,
        "name_cn": "松下控股公司",
        "name_en": "Panasonic Holdings Corporation",
        "founder_en": "Konosuke Matsushita",
        "founder_cn": "松下幸之助",
        "country": "🇯🇵 日本",
        "hq": "大阪府 门真市",
        "founded_year": 1918,
        "industry": "车载动力圆柱电池、智能家电与汽车电子",
        "revenue_m": "53,405"
    },
    {
        "rank": 287,
        "name_cn": "路易达孚集团",
        "name_en": "Louis Dreyfus Company (LDC)",
        "founder_en": "Léopold Louis-Dreyfus",
        "founder_cn": "利奥波德·路易-德雷福斯",
        "country": "🇳🇱 荷兰",
        "hq": "鹿特丹",
        "founded_year": 1851,
        "industry": "大宗谷物、油籽、棉花与果汁全球加工贸易 (ABCD四大粮商)",
        "revenue_m": "53,197"
    },
    {
        "rank": 288,
        "name_cn": "兴业银行股份有限公司",
        "name_en": "Industrial Bank Co., Ltd.",
        "founder_en": "Fujian Provincial People's Government",
        "founder_cn": "福建省人民政府 (经中国人民银行批准设立)",
        "country": "🇨🇳 中国",
        "hq": "福建 福州",
        "founded_year": 1988,
        "industry": "全国性股份制商业银行与赤道银行绿色金融",
        "revenue_m": "53,050"
    },
    {
        "rank": 289,
        "name_cn": "英特尔公司",
        "name_en": "Intel Corporation",
        "founder_en": "Robert Noyce, Gordon Moore",
        "founder_cn": "罗伯特·诺伊斯、戈登·摩尔",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 圣克拉拉",
        "founded_year": 1968,
        "industry": "x86微处理器CPU、服务器芯片与IFS晶圆代工",
        "revenue_m": "52,853"
    },
    {
        "rank": 290,
        "name_cn": "加拿大丰业银行",
        "name_en": "Bank of Nova Scotia (Scotiabank)",
        "founder_en": "William Lawson and Halifax Merchants",
        "founder_cn": "威廉·劳森及哈利法克斯商人集团",
        "country": "🇨🇦 加拿大",
        "hq": "多伦多 / 哈利法克斯",
        "founded_year": 1832,
        "industry": "跨国商业银行、零售金融与美洲太平洋联盟业务",
        "revenue_m": "52,710"
    },
    {
        "rank": 291,
        "name_cn": "韩华集团",
        "name_en": "Hanwha Group",
        "founder_en": "Kim Chong-hee (Korea Explosives)",
        "founder_cn": "金钟喜 (韩国火药公司前身)",
        "country": "🇰🇷 韩国",
        "hq": "首尔",
        "founded_year": 1952,
        "industry": "防务军工航空航天、光伏新能源 (Qcells) 与金融",
        "revenue_m": "52,608"
    },
    {
        "rank": 292,
        "name_cn": "Enterprise Products Partners公司",
        "name_en": "Enterprise Products Partners L.P.",
        "founder_en": "Dan Duncan",
        "founder_cn": "丹·邓肯",
        "country": "🇺🇸 美国",
        "hq": "德克萨斯州 休斯敦",
        "founded_year": 1968,
        "industry": "天然气液体(NGL)中游管网、分馏加工与码头出口",
        "revenue_m": "52,596"
    },
    {
        "rank": 293,
        "name_cn": "英迈公司",
        "name_en": "Ingram Micro Inc.",
        "founder_en": "Geza Czige, Fred Heinzmann (Micro D)",
        "founder_cn": "格扎·齐格、弗雷德·海因兹曼",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 欧文",
        "founded_year": 1979,
        "industry": "全球IT硬件与云技术服务供应链分销",
        "revenue_m": "52,556"
    },
    {
        "rank": 294,
        "name_cn": "通用动力",
        "name_en": "General Dynamics Corporation",
        "founder_en": "John Philip Holland (Electric Boat Company)",
        "founder_cn": "约翰·P·霍兰 (电船公司创立演变)",
        "country": "🇺🇸 美国",
        "hq": "弗吉尼亚州 莱斯顿",
        "founded_year": 1899,
        "industry": "核动力攻击/战略潜艇、湾流公务机与陆战装甲系统",
        "revenue_m": "52,550"
    },
    {
        "rank": 295,
        "name_cn": "圣戈班集团",
        "name_en": "Compagnie de Saint-Gobain S.A.",
        "founder_en": "King Louis XIV & Jean-Baptiste Colbert",
        "founder_cn": "路易十四与让-巴蒂斯特·柯尔贝尔 (皇家镜面玻璃工场)",
        "country": "🇫🇷 法国",
        "hq": "库尔布瓦",
        "founded_year": 1665,
        "industry": "高性能建筑节能材料、平板特种玻璃与轻型建筑系统",
        "revenue_m": "52,429"
    },
    {
        "rank": 296,
        "name_cn": "Uber Technologies公司",
        "name_en": "Uber Technologies, Inc.",
        "founder_en": "Travis Kalanick, Garrett Camp",
        "founder_cn": "特拉维斯·卡兰尼克、加勒特·坎普",
        "country": "🇺🇸 美国",
        "hq": "加利福尼亚州 旧金山",
        "founded_year": 2009,
        "industry": "全球网约叫车出行与即时餐饮配送平台 (Uber Eats)",
        "revenue_m": "52,017"
    },
    {
        "rank": 297,
        "name_cn": "泰康保险集团股份有限公司",
        "name_en": "Taikang Insurance Group, Inc.",
        "founder_en": "Chen Dongsheng",
        "founder_cn": "陈东升",
        "country": "🇨🇳 中国",
        "hq": "北京",
        "founded_year": 1996,
        "industry": "人寿保险、资产管理与高端医养康宁实体社区",
        "revenue_m": "51,921"
    },
    {
        "rank": 298,
        "name_cn": "巴拉特石油公司",
        "name_en": "Bharat Petroleum Corporation Limited (BPCL)",
        "founder_en": "Rangoon Oil Co. / Government of India Nationalization",
        "founder_cn": "仰光石油改制设立 / 印度政府国有化整合",
        "country": "🇮🇳 印度",
        "hq": "孟买",
        "founded_year": 1860,
        "industry": "原油精炼与成品油加油站零售网络",
        "revenue_m": "51,895"
    },
    {
        "rank": 299,
        "name_cn": "广州汽车工业集团有限公司",
        "name_en": "Guangzhou Automobile Industry Group (GAC Group)",
        "founder_en": "Guangzhou Municipal People's Government",
        "founder_cn": "广州市人民政府 (广州汽车工业总公司演变)",
        "country": "🇨🇳 中国",
        "hq": "广东 广州",
        "founded_year": 1997,
        "industry": "广汽传祺/埃安纯电整车制造与合资汽车生产",
        "revenue_m": "51,837"
    },
    {
        "rank": 300,
        "name_cn": "软银集团",
        "name_en": "SoftBank Group Corp.",
        "founder_en": "Masayoshi Son",
        "founder_cn": "孙正义",
        "country": "🇯🇵 日本",
        "hq": "东京",
        "founded_year": 1981,
        "industry": "全球科技战略投资 (愿景基金) 与半导体IP (Arm)",
        "revenue_m": "51,746"
    }
]
